// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module inference_relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer8_out_dout,
        layer8_out_num_data_valid,
        layer8_out_fifo_cap,
        layer8_out_empty_n,
        layer8_out_read,
        layer9_out_din,
        layer9_out_num_data_valid,
        layer9_out_fifo_cap,
        layer9_out_full_n,
        layer9_out_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [127:0] layer8_out_dout;
input  [1:0] layer8_out_num_data_valid;
input  [1:0] layer8_out_fifo_cap;
input   layer8_out_empty_n;
output   layer8_out_read;
output  [127:0] layer9_out_din;
input  [1:0] layer9_out_num_data_valid;
input  [1:0] layer9_out_fifo_cap;
input   layer9_out_full_n;
output   layer9_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer8_out_read;
reg layer9_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer8_out_blk_n;
reg    layer9_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [6:0] trunc_ln44_2_fu_135_p1;
reg   [6:0] trunc_ln44_2_reg_732;
reg   [6:0] trunc_ln44_s_reg_737;
reg   [6:0] trunc_ln44_35_reg_742;
reg   [6:0] trunc_ln44_36_reg_747;
reg   [6:0] trunc_ln44_37_reg_752;
reg   [6:0] trunc_ln44_38_reg_757;
reg   [6:0] trunc_ln44_39_reg_762;
reg   [6:0] trunc_ln44_40_reg_767;
reg   [6:0] trunc_ln44_41_reg_772;
reg   [6:0] trunc_ln44_42_reg_777;
reg   [6:0] trunc_ln44_43_reg_782;
reg   [6:0] trunc_ln44_44_reg_787;
reg   [6:0] trunc_ln44_45_reg_792;
reg   [6:0] trunc_ln44_46_reg_797;
reg   [6:0] trunc_ln44_47_reg_802;
reg   [6:0] trunc_ln_reg_807;
wire   [0:0] icmp_ln1649_fu_439_p2;
reg   [0:0] icmp_ln1649_reg_812;
wire   [0:0] icmp_ln1649_32_fu_445_p2;
reg   [0:0] icmp_ln1649_32_reg_817;
wire   [0:0] icmp_ln1649_33_fu_451_p2;
reg   [0:0] icmp_ln1649_33_reg_822;
wire   [0:0] icmp_ln1649_34_fu_457_p2;
reg   [0:0] icmp_ln1649_34_reg_827;
wire   [0:0] icmp_ln1649_35_fu_463_p2;
reg   [0:0] icmp_ln1649_35_reg_832;
wire   [0:0] icmp_ln1649_36_fu_469_p2;
reg   [0:0] icmp_ln1649_36_reg_837;
wire   [0:0] icmp_ln1649_37_fu_475_p2;
reg   [0:0] icmp_ln1649_37_reg_842;
wire   [0:0] icmp_ln1649_38_fu_481_p2;
reg   [0:0] icmp_ln1649_38_reg_847;
wire   [0:0] icmp_ln1649_39_fu_487_p2;
reg   [0:0] icmp_ln1649_39_reg_852;
wire   [0:0] icmp_ln1649_40_fu_493_p2;
reg   [0:0] icmp_ln1649_40_reg_857;
wire   [0:0] icmp_ln1649_41_fu_499_p2;
reg   [0:0] icmp_ln1649_41_reg_862;
wire   [0:0] icmp_ln1649_42_fu_505_p2;
reg   [0:0] icmp_ln1649_42_reg_867;
wire   [0:0] icmp_ln1649_43_fu_511_p2;
reg   [0:0] icmp_ln1649_43_reg_872;
wire   [0:0] icmp_ln1649_44_fu_517_p2;
reg   [0:0] icmp_ln1649_44_reg_877;
wire   [0:0] icmp_ln1649_45_fu_523_p2;
reg   [0:0] icmp_ln1649_45_reg_882;
wire   [0:0] icmp_ln1649_46_fu_529_p2;
reg   [0:0] icmp_ln1649_46_reg_887;
reg    ap_block_state1;
wire   [7:0] in_data_data_fu_131_p1;
wire   [7:0] in_data_data_22_fu_159_p4;
wire   [7:0] in_data_data_23_fu_179_p4;
wire   [7:0] in_data_data_24_fu_199_p4;
wire   [7:0] in_data_data_25_fu_219_p4;
wire   [7:0] in_data_data_26_fu_239_p4;
wire   [7:0] in_data_data_27_fu_259_p4;
wire   [7:0] in_data_data_28_fu_279_p4;
wire   [7:0] tmp_fu_299_p4;
wire   [7:0] tmp_s_fu_319_p4;
wire   [7:0] tmp_21_fu_339_p4;
wire   [7:0] tmp_22_fu_359_p4;
wire   [7:0] tmp_23_fu_379_p4;
wire   [7:0] tmp_24_fu_399_p4;
wire   [7:0] trunc_ln44_33_fu_139_p4;
wire   [7:0] trunc_ln44_34_fu_149_p4;
wire   [6:0] select_ln51_fu_535_p3;
wire   [6:0] select_ln51_32_fu_545_p3;
wire   [6:0] select_ln51_33_fu_555_p3;
wire   [6:0] select_ln51_34_fu_565_p3;
wire   [6:0] select_ln51_35_fu_575_p3;
wire   [6:0] select_ln51_36_fu_585_p3;
wire   [6:0] select_ln51_37_fu_595_p3;
wire   [6:0] select_ln51_38_fu_605_p3;
wire   [6:0] select_ln51_39_fu_615_p3;
wire   [6:0] select_ln51_40_fu_625_p3;
wire   [6:0] select_ln51_41_fu_635_p3;
wire   [6:0] select_ln51_42_fu_645_p3;
wire   [6:0] select_ln51_43_fu_655_p3;
wire   [6:0] select_ln51_44_fu_665_p3;
wire   [6:0] select_ln51_45_fu_675_p3;
wire   [6:0] select_ln51_46_fu_685_p3;
wire   [7:0] zext_ln1649_44_fu_681_p1;
wire   [7:0] zext_ln1649_43_fu_671_p1;
wire   [7:0] zext_ln1649_42_fu_661_p1;
wire   [7:0] zext_ln1649_41_fu_651_p1;
wire   [7:0] zext_ln1649_40_fu_641_p1;
wire   [7:0] zext_ln1649_39_fu_631_p1;
wire   [7:0] zext_ln1649_38_fu_621_p1;
wire   [7:0] zext_ln1649_37_fu_611_p1;
wire   [7:0] zext_ln1649_36_fu_601_p1;
wire   [7:0] zext_ln1649_35_fu_591_p1;
wire   [7:0] zext_ln1649_34_fu_581_p1;
wire   [7:0] zext_ln1649_33_fu_571_p1;
wire   [7:0] zext_ln1649_32_fu_561_p1;
wire   [7:0] zext_ln1649_31_fu_551_p1;
wire   [7:0] zext_ln1649_fu_541_p1;
wire   [126:0] or_ln57_s_fu_691_p17;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer9_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln1649_32_reg_817 <= icmp_ln1649_32_fu_445_p2;
        icmp_ln1649_33_reg_822 <= icmp_ln1649_33_fu_451_p2;
        icmp_ln1649_34_reg_827 <= icmp_ln1649_34_fu_457_p2;
        icmp_ln1649_35_reg_832 <= icmp_ln1649_35_fu_463_p2;
        icmp_ln1649_36_reg_837 <= icmp_ln1649_36_fu_469_p2;
        icmp_ln1649_37_reg_842 <= icmp_ln1649_37_fu_475_p2;
        icmp_ln1649_38_reg_847 <= icmp_ln1649_38_fu_481_p2;
        icmp_ln1649_39_reg_852 <= icmp_ln1649_39_fu_487_p2;
        icmp_ln1649_40_reg_857 <= icmp_ln1649_40_fu_493_p2;
        icmp_ln1649_41_reg_862 <= icmp_ln1649_41_fu_499_p2;
        icmp_ln1649_42_reg_867 <= icmp_ln1649_42_fu_505_p2;
        icmp_ln1649_43_reg_872 <= icmp_ln1649_43_fu_511_p2;
        icmp_ln1649_44_reg_877 <= icmp_ln1649_44_fu_517_p2;
        icmp_ln1649_45_reg_882 <= icmp_ln1649_45_fu_523_p2;
        icmp_ln1649_46_reg_887 <= icmp_ln1649_46_fu_529_p2;
        icmp_ln1649_reg_812 <= icmp_ln1649_fu_439_p2;
        trunc_ln44_2_reg_732 <= trunc_ln44_2_fu_135_p1;
        trunc_ln44_35_reg_742 <= {{layer8_out_dout[22:16]}};
        trunc_ln44_36_reg_747 <= {{layer8_out_dout[30:24]}};
        trunc_ln44_37_reg_752 <= {{layer8_out_dout[38:32]}};
        trunc_ln44_38_reg_757 <= {{layer8_out_dout[46:40]}};
        trunc_ln44_39_reg_762 <= {{layer8_out_dout[54:48]}};
        trunc_ln44_40_reg_767 <= {{layer8_out_dout[62:56]}};
        trunc_ln44_41_reg_772 <= {{layer8_out_dout[70:64]}};
        trunc_ln44_42_reg_777 <= {{layer8_out_dout[78:72]}};
        trunc_ln44_43_reg_782 <= {{layer8_out_dout[86:80]}};
        trunc_ln44_44_reg_787 <= {{layer8_out_dout[94:88]}};
        trunc_ln44_45_reg_792 <= {{layer8_out_dout[102:96]}};
        trunc_ln44_46_reg_797 <= {{layer8_out_dout[110:104]}};
        trunc_ln44_47_reg_802 <= {{layer8_out_dout[118:112]}};
        trunc_ln44_s_reg_737 <= {{layer8_out_dout[14:8]}};
        trunc_ln_reg_807 <= {{layer8_out_dout[126:120]}};
    end
end

always @ (*) begin
    if (((real_start == 1'b0) | (layer8_out_empty_n == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer9_out_full_n == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer9_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer9_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer8_out_blk_n = layer8_out_empty_n;
    end else begin
        layer8_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (layer8_out_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer8_out_read = 1'b1;
    end else begin
        layer8_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer9_out_blk_n = layer9_out_full_n;
    end else begin
        layer9_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer9_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        layer9_out_write = 1'b1;
    end else begin
        layer9_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (layer8_out_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((layer9_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer8_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign icmp_ln1649_32_fu_445_p2 = (($signed(in_data_data_22_fu_159_p4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_33_fu_451_p2 = (($signed(in_data_data_23_fu_179_p4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_34_fu_457_p2 = (($signed(in_data_data_24_fu_199_p4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_35_fu_463_p2 = (($signed(in_data_data_25_fu_219_p4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_36_fu_469_p2 = (($signed(in_data_data_26_fu_239_p4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_37_fu_475_p2 = (($signed(in_data_data_27_fu_259_p4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_38_fu_481_p2 = (($signed(in_data_data_28_fu_279_p4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_39_fu_487_p2 = (($signed(tmp_fu_299_p4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_40_fu_493_p2 = (($signed(tmp_s_fu_319_p4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_41_fu_499_p2 = (($signed(tmp_21_fu_339_p4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_42_fu_505_p2 = (($signed(tmp_22_fu_359_p4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_43_fu_511_p2 = (($signed(tmp_23_fu_379_p4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_44_fu_517_p2 = (($signed(tmp_24_fu_399_p4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_45_fu_523_p2 = (($signed(trunc_ln44_33_fu_139_p4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_46_fu_529_p2 = (($signed(trunc_ln44_34_fu_149_p4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_fu_439_p2 = (($signed(in_data_data_fu_131_p1) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign in_data_data_22_fu_159_p4 = {{layer8_out_dout[15:8]}};

assign in_data_data_23_fu_179_p4 = {{layer8_out_dout[23:16]}};

assign in_data_data_24_fu_199_p4 = {{layer8_out_dout[31:24]}};

assign in_data_data_25_fu_219_p4 = {{layer8_out_dout[39:32]}};

assign in_data_data_26_fu_239_p4 = {{layer8_out_dout[47:40]}};

assign in_data_data_27_fu_259_p4 = {{layer8_out_dout[55:48]}};

assign in_data_data_28_fu_279_p4 = {{layer8_out_dout[63:56]}};

assign in_data_data_fu_131_p1 = layer8_out_dout[7:0];

assign layer9_out_din = or_ln57_s_fu_691_p17;

assign or_ln57_s_fu_691_p17 = {{{{{{{{{{{{{{{{select_ln51_46_fu_685_p3}, {zext_ln1649_44_fu_681_p1}}, {zext_ln1649_43_fu_671_p1}}, {zext_ln1649_42_fu_661_p1}}, {zext_ln1649_41_fu_651_p1}}, {zext_ln1649_40_fu_641_p1}}, {zext_ln1649_39_fu_631_p1}}, {zext_ln1649_38_fu_621_p1}}, {zext_ln1649_37_fu_611_p1}}, {zext_ln1649_36_fu_601_p1}}, {zext_ln1649_35_fu_591_p1}}, {zext_ln1649_34_fu_581_p1}}, {zext_ln1649_33_fu_571_p1}}, {zext_ln1649_32_fu_561_p1}}, {zext_ln1649_31_fu_551_p1}}, {zext_ln1649_fu_541_p1}};

assign select_ln51_32_fu_545_p3 = ((icmp_ln1649_32_reg_817[0:0] == 1'b1) ? trunc_ln44_s_reg_737 : 7'd0);

assign select_ln51_33_fu_555_p3 = ((icmp_ln1649_33_reg_822[0:0] == 1'b1) ? trunc_ln44_35_reg_742 : 7'd0);

assign select_ln51_34_fu_565_p3 = ((icmp_ln1649_34_reg_827[0:0] == 1'b1) ? trunc_ln44_36_reg_747 : 7'd0);

assign select_ln51_35_fu_575_p3 = ((icmp_ln1649_35_reg_832[0:0] == 1'b1) ? trunc_ln44_37_reg_752 : 7'd0);

assign select_ln51_36_fu_585_p3 = ((icmp_ln1649_36_reg_837[0:0] == 1'b1) ? trunc_ln44_38_reg_757 : 7'd0);

assign select_ln51_37_fu_595_p3 = ((icmp_ln1649_37_reg_842[0:0] == 1'b1) ? trunc_ln44_39_reg_762 : 7'd0);

assign select_ln51_38_fu_605_p3 = ((icmp_ln1649_38_reg_847[0:0] == 1'b1) ? trunc_ln44_40_reg_767 : 7'd0);

assign select_ln51_39_fu_615_p3 = ((icmp_ln1649_39_reg_852[0:0] == 1'b1) ? trunc_ln44_41_reg_772 : 7'd0);

assign select_ln51_40_fu_625_p3 = ((icmp_ln1649_40_reg_857[0:0] == 1'b1) ? trunc_ln44_42_reg_777 : 7'd0);

assign select_ln51_41_fu_635_p3 = ((icmp_ln1649_41_reg_862[0:0] == 1'b1) ? trunc_ln44_43_reg_782 : 7'd0);

assign select_ln51_42_fu_645_p3 = ((icmp_ln1649_42_reg_867[0:0] == 1'b1) ? trunc_ln44_44_reg_787 : 7'd0);

assign select_ln51_43_fu_655_p3 = ((icmp_ln1649_43_reg_872[0:0] == 1'b1) ? trunc_ln44_45_reg_792 : 7'd0);

assign select_ln51_44_fu_665_p3 = ((icmp_ln1649_44_reg_877[0:0] == 1'b1) ? trunc_ln44_46_reg_797 : 7'd0);

assign select_ln51_45_fu_675_p3 = ((icmp_ln1649_45_reg_882[0:0] == 1'b1) ? trunc_ln44_47_reg_802 : 7'd0);

assign select_ln51_46_fu_685_p3 = ((icmp_ln1649_46_reg_887[0:0] == 1'b1) ? trunc_ln_reg_807 : 7'd0);

assign select_ln51_fu_535_p3 = ((icmp_ln1649_reg_812[0:0] == 1'b1) ? trunc_ln44_2_reg_732 : 7'd0);

assign start_out = real_start;

assign tmp_21_fu_339_p4 = {{layer8_out_dout[87:80]}};

assign tmp_22_fu_359_p4 = {{layer8_out_dout[95:88]}};

assign tmp_23_fu_379_p4 = {{layer8_out_dout[103:96]}};

assign tmp_24_fu_399_p4 = {{layer8_out_dout[111:104]}};

assign tmp_fu_299_p4 = {{layer8_out_dout[71:64]}};

assign tmp_s_fu_319_p4 = {{layer8_out_dout[79:72]}};

assign trunc_ln44_2_fu_135_p1 = layer8_out_dout[6:0];

assign trunc_ln44_33_fu_139_p4 = {{layer8_out_dout[119:112]}};

assign trunc_ln44_34_fu_149_p4 = {{layer8_out_dout[127:120]}};

assign zext_ln1649_31_fu_551_p1 = select_ln51_32_fu_545_p3;

assign zext_ln1649_32_fu_561_p1 = select_ln51_33_fu_555_p3;

assign zext_ln1649_33_fu_571_p1 = select_ln51_34_fu_565_p3;

assign zext_ln1649_34_fu_581_p1 = select_ln51_35_fu_575_p3;

assign zext_ln1649_35_fu_591_p1 = select_ln51_36_fu_585_p3;

assign zext_ln1649_36_fu_601_p1 = select_ln51_37_fu_595_p3;

assign zext_ln1649_37_fu_611_p1 = select_ln51_38_fu_605_p3;

assign zext_ln1649_38_fu_621_p1 = select_ln51_39_fu_615_p3;

assign zext_ln1649_39_fu_631_p1 = select_ln51_40_fu_625_p3;

assign zext_ln1649_40_fu_641_p1 = select_ln51_41_fu_635_p3;

assign zext_ln1649_41_fu_651_p1 = select_ln51_42_fu_645_p3;

assign zext_ln1649_42_fu_661_p1 = select_ln51_43_fu_655_p3;

assign zext_ln1649_43_fu_671_p1 = select_ln51_44_fu_665_p3;

assign zext_ln1649_44_fu_681_p1 = select_ln51_45_fu_675_p3;

assign zext_ln1649_fu_541_p1 = select_ln51_fu_535_p3;

endmodule //inference_relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_s
