// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module inference_myproject (
        ap_start,
        start_full_n,
        start_out,
        start_write,
        internal_input_dout,
        internal_input_empty_n,
        internal_input_read,
        internal_output_din,
        internal_output_full_n,
        internal_output_write,
        ap_clk,
        ap_rst,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input   ap_start;
input   start_full_n;
output   start_out;
output   start_write;
input  [143:0] internal_input_dout;
input   internal_input_empty_n;
output   internal_input_read;
output  [7:0] internal_output_din;
input   internal_output_full_n;
output   internal_output_write;
input   ap_clk;
input   ap_rst;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

reg start_write;

reg    real_start;
reg    start_once_reg;
wire    internal_ap_ready;
wire    dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_ap_start;
wire    dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_ap_done;
wire    dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_ap_continue;
wire    dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_ap_idle;
wire    dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_ap_ready;
wire    dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_internal_input_read;
wire   [255:0] dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_layer2_out_din;
wire    dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_layer2_out_write;
wire    dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_start_out;
wire    dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_start_write;
wire    normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_ap_start;
wire    normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_ap_done;
wire    normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_ap_continue;
wire    normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_ap_idle;
wire    normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_ap_ready;
wire    normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_start_out;
wire    normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_start_write;
wire    normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_layer2_out_read;
wire   [255:0] normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_layer4_out_din;
wire    normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_layer4_out_write;
wire    relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_ap_start;
wire    relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_ap_done;
wire    relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_ap_continue;
wire    relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_ap_idle;
wire    relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_ap_ready;
wire    relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_start_out;
wire    relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_start_write;
wire    relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_layer4_out_read;
wire   [255:0] relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_layer5_out_din;
wire    relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_layer5_out_write;
wire    dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_ap_start;
wire    dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_ap_done;
wire    dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_ap_continue;
wire    dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_ap_idle;
wire    dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_ap_ready;
wire    dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_layer5_out_read;
wire   [127:0] dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_layer6_out_din;
wire    dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_layer6_out_write;
wire    dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_start_out;
wire    dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_start_write;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_ap_start;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_ap_done;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_ap_continue;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_ap_idle;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_ap_ready;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_start_out;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_start_write;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_layer6_out_read;
wire   [127:0] normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_layer8_out_din;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_layer8_out_write;
wire    relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_ap_start;
wire    relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_ap_done;
wire    relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_ap_continue;
wire    relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_ap_idle;
wire    relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_ap_ready;
wire    relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_start_out;
wire    relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_start_write;
wire    relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_layer8_out_read;
wire   [127:0] relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_layer9_out_din;
wire    relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_layer9_out_write;
wire    dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_ap_start;
wire    dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_ap_done;
wire    dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_ap_continue;
wire    dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_ap_idle;
wire    dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_ap_ready;
wire    dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_layer9_out_read;
wire   [7:0] dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_layer10_out_din;
wire    dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_layer10_out_write;
wire    dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_start_out;
wire    dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_start_write;
wire    sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_ap_start;
wire    sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_ap_done;
wire    sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_ap_continue;
wire    sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_ap_idle;
wire    sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_ap_ready;
wire    sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_layer10_out_read;
wire   [7:0] sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_internal_output_din;
wire    sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_internal_output_write;
wire    layer2_out_full_n;
wire   [255:0] layer2_out_dout;
wire   [1:0] layer2_out_num_data_valid;
wire   [1:0] layer2_out_fifo_cap;
wire    layer2_out_empty_n;
wire    layer4_out_full_n;
wire   [255:0] layer4_out_dout;
wire   [1:0] layer4_out_num_data_valid;
wire   [1:0] layer4_out_fifo_cap;
wire    layer4_out_empty_n;
wire    layer5_out_full_n;
wire   [255:0] layer5_out_dout;
wire   [1:0] layer5_out_num_data_valid;
wire   [1:0] layer5_out_fifo_cap;
wire    layer5_out_empty_n;
wire    layer6_out_full_n;
wire   [127:0] layer6_out_dout;
wire   [1:0] layer6_out_num_data_valid;
wire   [1:0] layer6_out_fifo_cap;
wire    layer6_out_empty_n;
wire    layer8_out_full_n;
wire   [127:0] layer8_out_dout;
wire   [1:0] layer8_out_num_data_valid;
wire   [1:0] layer8_out_fifo_cap;
wire    layer8_out_empty_n;
wire    layer9_out_full_n;
wire   [127:0] layer9_out_dout;
wire   [1:0] layer9_out_num_data_valid;
wire   [1:0] layer9_out_fifo_cap;
wire    layer9_out_empty_n;
wire    layer10_out_full_n;
wire   [7:0] layer10_out_dout;
wire   [1:0] layer10_out_num_data_valid;
wire   [1:0] layer10_out_fifo_cap;
wire    layer10_out_empty_n;
wire    ap_sync_ready;
wire   [0:0] start_for_normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_din;
wire    start_for_normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_full_n;
wire   [0:0] start_for_normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_dout;
wire    start_for_normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_din;
wire    start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_dout;
wire    start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_empty_n;
wire   [0:0] start_for_dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_din;
wire    start_for_dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_full_n;
wire   [0:0] start_for_dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_dout;
wire    start_for_dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_empty_n;
wire   [0:0] start_for_normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_din;
wire    start_for_normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_full_n;
wire   [0:0] start_for_normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_dout;
wire    start_for_normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_din;
wire    start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_dout;
wire    start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_empty_n;
wire   [0:0] start_for_dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_din;
wire    start_for_dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_full_n;
wire   [0:0] start_for_dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_dout;
wire    start_for_dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_empty_n;
wire   [0:0] start_for_sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_din;
wire    start_for_sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_full_n;
wire   [0:0] start_for_sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_dout;
wire    start_for_sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
end

inference_dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_s dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_ap_start),
    .start_full_n(start_for_normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_full_n),
    .ap_done(dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_ap_done),
    .ap_continue(dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_ap_continue),
    .ap_idle(dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_ap_idle),
    .ap_ready(dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_ap_ready),
    .internal_input_dout(internal_input_dout),
    .internal_input_num_data_valid(2'd0),
    .internal_input_fifo_cap(2'd0),
    .internal_input_empty_n(internal_input_empty_n),
    .internal_input_read(dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_internal_input_read),
    .layer2_out_din(dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_layer2_out_din),
    .layer2_out_num_data_valid(layer2_out_num_data_valid),
    .layer2_out_fifo_cap(layer2_out_fifo_cap),
    .layer2_out_full_n(layer2_out_full_n),
    .layer2_out_write(dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_layer2_out_write),
    .start_out(dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_start_out),
    .start_write(dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_start_write)
);

inference_normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_s normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_full_n),
    .ap_done(normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_ap_done),
    .ap_continue(normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_ap_continue),
    .ap_idle(normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_ap_idle),
    .ap_ready(normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_ap_ready),
    .start_out(normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_start_out),
    .start_write(normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_start_write),
    .layer2_out_dout(layer2_out_dout),
    .layer2_out_num_data_valid(layer2_out_num_data_valid),
    .layer2_out_fifo_cap(layer2_out_fifo_cap),
    .layer2_out_empty_n(layer2_out_empty_n),
    .layer2_out_read(normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_layer2_out_read),
    .layer4_out_din(normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_layer4_out_din),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .layer4_out_full_n(layer4_out_full_n),
    .layer4_out_write(normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_layer4_out_write)
);

inference_relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_s relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_ap_start),
    .start_full_n(start_for_dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_full_n),
    .ap_done(relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_ap_ready),
    .start_out(relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_start_out),
    .start_write(relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_start_write),
    .layer4_out_dout(layer4_out_dout),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .layer4_out_empty_n(layer4_out_empty_n),
    .layer4_out_read(relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_layer4_out_read),
    .layer5_out_din(relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_layer5_out_din),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap),
    .layer5_out_full_n(layer5_out_full_n),
    .layer5_out_write(relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_layer5_out_write)
);

inference_dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_s dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_ap_start),
    .start_full_n(start_for_normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_full_n),
    .ap_done(dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_ap_done),
    .ap_continue(dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_ap_continue),
    .ap_idle(dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_ap_idle),
    .ap_ready(dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_ap_ready),
    .layer5_out_dout(layer5_out_dout),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap),
    .layer5_out_empty_n(layer5_out_empty_n),
    .layer5_out_read(dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_layer5_out_read),
    .layer6_out_din(dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_layer6_out_din),
    .layer6_out_num_data_valid(layer6_out_num_data_valid),
    .layer6_out_fifo_cap(layer6_out_fifo_cap),
    .layer6_out_full_n(layer6_out_full_n),
    .layer6_out_write(dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_layer6_out_write),
    .start_out(dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_start_out),
    .start_write(dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_start_write)
);

inference_normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_s normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_full_n),
    .ap_done(normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_ap_done),
    .ap_continue(normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_ap_continue),
    .ap_idle(normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_ap_idle),
    .ap_ready(normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_ap_ready),
    .start_out(normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_start_out),
    .start_write(normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_start_write),
    .layer6_out_dout(layer6_out_dout),
    .layer6_out_num_data_valid(layer6_out_num_data_valid),
    .layer6_out_fifo_cap(layer6_out_fifo_cap),
    .layer6_out_empty_n(layer6_out_empty_n),
    .layer6_out_read(normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_layer6_out_read),
    .layer8_out_din(normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_layer8_out_din),
    .layer8_out_num_data_valid(layer8_out_num_data_valid),
    .layer8_out_fifo_cap(layer8_out_fifo_cap),
    .layer8_out_full_n(layer8_out_full_n),
    .layer8_out_write(normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_layer8_out_write)
);

inference_relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_s relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_ap_start),
    .start_full_n(start_for_dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_full_n),
    .ap_done(relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_ap_ready),
    .start_out(relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_start_out),
    .start_write(relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_start_write),
    .layer8_out_dout(layer8_out_dout),
    .layer8_out_num_data_valid(layer8_out_num_data_valid),
    .layer8_out_fifo_cap(layer8_out_fifo_cap),
    .layer8_out_empty_n(layer8_out_empty_n),
    .layer8_out_read(relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_layer8_out_read),
    .layer9_out_din(relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_layer9_out_din),
    .layer9_out_num_data_valid(layer9_out_num_data_valid),
    .layer9_out_fifo_cap(layer9_out_fifo_cap),
    .layer9_out_full_n(layer9_out_full_n),
    .layer9_out_write(relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_layer9_out_write)
);

inference_dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_s dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_ap_start),
    .start_full_n(start_for_sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_full_n),
    .ap_done(dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_ap_done),
    .ap_continue(dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_ap_continue),
    .ap_idle(dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_ap_idle),
    .ap_ready(dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_ap_ready),
    .layer9_out_dout(layer9_out_dout),
    .layer9_out_num_data_valid(layer9_out_num_data_valid),
    .layer9_out_fifo_cap(layer9_out_fifo_cap),
    .layer9_out_empty_n(layer9_out_empty_n),
    .layer9_out_read(dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_layer9_out_read),
    .layer10_out_din(dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_layer10_out_din),
    .layer10_out_num_data_valid(layer10_out_num_data_valid),
    .layer10_out_fifo_cap(layer10_out_fifo_cap),
    .layer10_out_full_n(layer10_out_full_n),
    .layer10_out_write(dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_layer10_out_write),
    .start_out(dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_start_out),
    .start_write(dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_start_write)
);

inference_sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_s sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_ap_start),
    .ap_done(sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_ap_done),
    .ap_continue(sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_ap_continue),
    .ap_idle(sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_ap_idle),
    .ap_ready(sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_ap_ready),
    .layer10_out_dout(layer10_out_dout),
    .layer10_out_num_data_valid(layer10_out_num_data_valid),
    .layer10_out_fifo_cap(layer10_out_fifo_cap),
    .layer10_out_empty_n(layer10_out_empty_n),
    .layer10_out_read(sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_layer10_out_read),
    .internal_output_din(sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_internal_output_din),
    .internal_output_num_data_valid(2'd0),
    .internal_output_fifo_cap(2'd0),
    .internal_output_full_n(internal_output_full_n),
    .internal_output_write(sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_internal_output_write)
);

inference_fifo_w256_d1_S layer2_out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_layer2_out_din),
    .if_full_n(layer2_out_full_n),
    .if_write(dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_layer2_out_write),
    .if_dout(layer2_out_dout),
    .if_num_data_valid(layer2_out_num_data_valid),
    .if_fifo_cap(layer2_out_fifo_cap),
    .if_empty_n(layer2_out_empty_n),
    .if_read(normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_layer2_out_read)
);

inference_fifo_w256_d1_S layer4_out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_layer4_out_din),
    .if_full_n(layer4_out_full_n),
    .if_write(normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_layer4_out_write),
    .if_dout(layer4_out_dout),
    .if_num_data_valid(layer4_out_num_data_valid),
    .if_fifo_cap(layer4_out_fifo_cap),
    .if_empty_n(layer4_out_empty_n),
    .if_read(relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_layer4_out_read)
);

inference_fifo_w256_d1_S layer5_out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_layer5_out_din),
    .if_full_n(layer5_out_full_n),
    .if_write(relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_layer5_out_write),
    .if_dout(layer5_out_dout),
    .if_num_data_valid(layer5_out_num_data_valid),
    .if_fifo_cap(layer5_out_fifo_cap),
    .if_empty_n(layer5_out_empty_n),
    .if_read(dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_layer5_out_read)
);

inference_fifo_w128_d1_S layer6_out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_layer6_out_din),
    .if_full_n(layer6_out_full_n),
    .if_write(dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_layer6_out_write),
    .if_dout(layer6_out_dout),
    .if_num_data_valid(layer6_out_num_data_valid),
    .if_fifo_cap(layer6_out_fifo_cap),
    .if_empty_n(layer6_out_empty_n),
    .if_read(normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_layer6_out_read)
);

inference_fifo_w128_d1_S layer8_out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_layer8_out_din),
    .if_full_n(layer8_out_full_n),
    .if_write(normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_layer8_out_write),
    .if_dout(layer8_out_dout),
    .if_num_data_valid(layer8_out_num_data_valid),
    .if_fifo_cap(layer8_out_fifo_cap),
    .if_empty_n(layer8_out_empty_n),
    .if_read(relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_layer8_out_read)
);

inference_fifo_w128_d1_S layer9_out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_layer9_out_din),
    .if_full_n(layer9_out_full_n),
    .if_write(relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_layer9_out_write),
    .if_dout(layer9_out_dout),
    .if_num_data_valid(layer9_out_num_data_valid),
    .if_fifo_cap(layer9_out_fifo_cap),
    .if_empty_n(layer9_out_empty_n),
    .if_read(dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_layer9_out_read)
);

inference_fifo_w8_d1_S layer10_out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_layer10_out_din),
    .if_full_n(layer10_out_full_n),
    .if_write(dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_layer10_out_write),
    .if_dout(layer10_out_dout),
    .if_num_data_valid(layer10_out_num_data_valid),
    .if_fifo_cap(layer10_out_fifo_cap),
    .if_empty_n(layer10_out_empty_n),
    .if_read(sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_layer10_out_read)
);

inference_start_for_normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0 start_for_normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_din),
    .if_full_n(start_for_normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_full_n),
    .if_write(dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_start_write),
    .if_dout(start_for_normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_dout),
    .if_empty_n(start_for_normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_empty_n),
    .if_read(normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_ap_ready)
);

inference_start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0 start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_full_n),
    .if_write(normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_empty_n),
    .if_read(relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_ap_ready)
);

inference_start_for_dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0 start_for_dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_din),
    .if_full_n(start_for_dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_full_n),
    .if_write(relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_start_write),
    .if_dout(start_for_dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_dout),
    .if_empty_n(start_for_dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_empty_n),
    .if_read(dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_ap_ready)
);

inference_start_for_normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0 start_for_normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_din),
    .if_full_n(start_for_normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_full_n),
    .if_write(dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_start_write),
    .if_dout(start_for_normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_dout),
    .if_empty_n(start_for_normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_empty_n),
    .if_read(normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_ap_ready)
);

inference_start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0 start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_full_n),
    .if_write(normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_empty_n),
    .if_read(relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_ap_ready)
);

inference_start_for_dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0 start_for_dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_din),
    .if_full_n(start_for_dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_full_n),
    .if_write(relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_start_write),
    .if_dout(start_for_dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_dout),
    .if_empty_n(start_for_dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_empty_n),
    .if_read(dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_ap_ready)
);

inference_start_for_sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0 start_for_sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_din),
    .if_full_n(start_for_sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_full_n),
    .if_write(dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_start_write),
    .if_dout(start_for_sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_dout),
    .if_empty_n(start_for_sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_empty_n),
    .if_read(sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

assign ap_done = sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_ap_done;

assign ap_idle = (sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_ap_idle & relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_ap_idle & relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_ap_idle & normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_ap_idle & normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_ap_idle & dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_ap_idle & dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_ap_idle & dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_ap_idle);

assign ap_ready = dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_ap_ready;

assign ap_sync_ready = dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_ap_ready;

assign dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_ap_continue = 1'b1;

assign dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_ap_start = start_for_dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_empty_n;

assign dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_ap_continue = 1'b1;

assign dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_ap_start = real_start;

assign dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_ap_continue = 1'b1;

assign dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_ap_start = start_for_dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_empty_n;

assign internal_ap_ready = ap_sync_ready;

assign internal_input_read = dense_array_ap_fixed_18u_array_ap_fixed_8_2_5_3_0_32u_config2_U0_internal_input_read;

assign internal_output_din = sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_internal_output_din;

assign internal_output_write = sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_internal_output_write;

assign normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_ap_continue = 1'b1;

assign normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_ap_start = start_for_normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_empty_n;

assign normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_ap_continue = 1'b1;

assign normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_ap_start = start_for_normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_empty_n;

assign relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_ap_start = start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_empty_n;

assign relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_ap_start = start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_empty_n;

assign sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_ap_continue = ap_continue;

assign sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_ap_start = start_for_sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_empty_n;

assign start_for_dense_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_1u_config10_U0_din = 1'b1;

assign start_for_dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_U0_din = 1'b1;

assign start_for_normalize_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_config8_U0_din = 1'b1;

assign start_for_normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_U0_din = 1'b1;

assign start_for_sigmoid_array_array_ap_fixed_8_2_5_3_0_1u_sigmoid_config11_U0_din = 1'b1;

assign start_out = real_start;

endmodule //inference_myproject
