// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module inference_dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer5_out_dout,
        layer5_out_num_data_valid,
        layer5_out_fifo_cap,
        layer5_out_empty_n,
        layer5_out_read,
        layer6_out_din,
        layer6_out_num_data_valid,
        layer6_out_fifo_cap,
        layer6_out_full_n,
        layer6_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [255:0] layer5_out_dout;
input  [1:0] layer5_out_num_data_valid;
input  [1:0] layer5_out_fifo_cap;
input   layer5_out_empty_n;
output   layer5_out_read;
output  [127:0] layer6_out_din;
input  [1:0] layer6_out_num_data_valid;
input  [1:0] layer6_out_fifo_cap;
input   layer6_out_full_n;
output   layer6_out_write;
output   start_out;
output   start_write;

reg ap_done;
reg ap_idle;
reg layer5_out_read;
reg layer6_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire   [0:0] icmp_ln124_fu_1460_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
reg   [0:0] ap_phi_mux_do_init_phi_fu_341_p6;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
reg   [0:0] icmp_ln124_reg_2778;
reg   [0:0] icmp_ln124_reg_2778_pp0_iter4_reg;
reg    ap_block_state7_pp0_stage0_iter5;
reg    ap_enable_reg_pp0_iter5;
reg    ap_block_pp0_stage0_11001;
wire   [5:0] outidx_address0;
reg    outidx_ce0;
wire   [0:0] outidx_q0;
wire   [8:0] w6_V_address0;
reg    w6_V_ce0;
wire   [7:0] w6_V_q0;
wire   [8:0] w6_V_address1;
reg    w6_V_ce1;
wire   [7:0] w6_V_q1;
wire   [8:0] w6_V_address2;
reg    w6_V_ce2;
wire   [7:0] w6_V_q2;
wire   [8:0] w6_V_address3;
reg    w6_V_ce3;
wire   [7:0] w6_V_q3;
wire   [8:0] w6_V_address4;
reg    w6_V_ce4;
wire   [7:0] w6_V_q4;
wire   [8:0] w6_V_address5;
reg    w6_V_ce5;
wire   [7:0] w6_V_q5;
wire   [8:0] w6_V_address6;
reg    w6_V_ce6;
wire   [7:0] w6_V_q6;
wire   [8:0] w6_V_address7;
reg    w6_V_ce7;
wire   [7:0] w6_V_q7;
reg    layer5_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer6_out_blk_n;
reg   [0:0] do_init_reg_337;
reg   [5:0] ir83_reg_353;
reg   [7:0] data_V_28_phi_reg_816;
reg   [7:0] data_V_27_phi_reg_828;
reg   [7:0] data_V_26_phi_reg_840;
reg   [7:0] data_V_25_phi_reg_852;
reg   [7:0] data_V_24_phi_reg_864;
reg   [7:0] data_V_23_phi_reg_876;
reg   [7:0] data_V_22_phi_reg_888;
reg   [7:0] data_V_21_phi_reg_900;
reg   [7:0] data_V_20_phi_reg_912;
reg   [7:0] data_V_19_phi_reg_924;
reg   [7:0] data_V_18_phi_reg_936;
reg   [7:0] data_V_17_phi_reg_948;
reg   [7:0] data_V_16_phi_reg_960;
reg   [7:0] data_V_15_phi_reg_972;
reg   [7:0] data_V_14_phi_reg_984;
reg   [7:0] data_V_13_phi_reg_996;
reg   [7:0] data_V_12_phi_reg_1008;
reg   [7:0] data_V_11_phi_reg_1020;
reg   [7:0] data_V_10_phi_reg_1032;
reg   [7:0] data_V_29_phi_reg_1044;
reg   [7:0] data_V_9_phi_reg_1056;
reg   [7:0] data_V_8_phi_reg_1068;
reg   [7:0] data_V_7_phi_reg_1080;
reg   [7:0] data_V_6_phi_reg_1092;
reg   [7:0] data_V_5_phi_reg_1104;
reg   [7:0] data_V_4_phi_reg_1116;
reg   [7:0] data_V_3_phi_reg_1128;
reg   [7:0] data_V_2_phi_reg_1140;
reg   [7:0] data_V_1_phi_reg_1152;
reg   [7:0] data_V_30_phi_reg_1164;
reg   [7:0] data_V_31_phi_reg_1176;
reg   [7:0] p_phi_reg_1188;
reg   [4:0] in_index84_reg_1200;
reg   [7:0] acc_V82_reg_1214;
reg   [7:0] acc_V_180_reg_1229;
reg   [7:0] acc_V_278_reg_1244;
reg   [7:0] acc_V_376_reg_1259;
reg   [7:0] acc_V_474_reg_1274;
reg   [7:0] acc_V_572_reg_1289;
reg   [7:0] acc_V_670_reg_1304;
reg   [7:0] acc_V_768_reg_1319;
reg   [7:0] acc_V_866_reg_1334;
reg   [7:0] acc_V_964_reg_1349;
reg   [7:0] acc_V_1062_reg_1364;
reg   [7:0] acc_V_1160_reg_1379;
reg   [7:0] acc_V_1258_reg_1394;
reg   [7:0] acc_V_1356_reg_1409;
reg   [7:0] acc_V_1454_reg_1424;
reg   [7:0] acc_V_1552_reg_1439;
wire   [5:0] ir_fu_1454_p2;
reg   [5:0] ir_reg_2773;
reg   [0:0] icmp_ln124_reg_2778_pp0_iter1_reg;
reg   [0:0] icmp_ln124_reg_2778_pp0_iter2_reg;
reg   [0:0] icmp_ln124_reg_2778_pp0_iter3_reg;
reg   [0:0] out_index_reg_2827;
reg   [0:0] out_index_reg_2827_pp0_iter3_reg;
reg   [0:0] out_index_reg_2827_pp0_iter4_reg;
wire   [7:0] a_V_fu_1905_p34;
reg   [7:0] a_V_reg_2871;
reg  signed [7:0] w_V_reg_2876;
reg    ap_enable_reg_pp0_iter2;
reg  signed [7:0] w_V_1_reg_2881;
reg  signed [7:0] w_V_2_reg_2886;
reg  signed [7:0] w_V_3_reg_2891;
reg  signed [7:0] w_V_4_reg_2896;
reg  signed [7:0] w_V_5_reg_2901;
reg  signed [7:0] w_V_6_reg_2906;
reg  signed [7:0] w_V_7_reg_2911;
wire   [4:0] in_index_fu_1995_p3;
reg   [4:0] in_index_reg_2916;
reg  signed [7:0] rhs_reg_2921;
reg  signed [7:0] rhs_reg_2921_pp0_iter4_reg;
reg  signed [7:0] rhs_1_reg_2927;
reg  signed [7:0] rhs_1_reg_2927_pp0_iter4_reg;
reg  signed [7:0] rhs_2_reg_2933;
reg  signed [7:0] rhs_2_reg_2933_pp0_iter4_reg;
reg  signed [7:0] rhs_3_reg_2939;
reg  signed [7:0] rhs_3_reg_2939_pp0_iter4_reg;
reg  signed [7:0] rhs_4_reg_2945;
reg  signed [7:0] rhs_4_reg_2945_pp0_iter4_reg;
reg  signed [7:0] rhs_5_reg_2951;
reg  signed [7:0] rhs_5_reg_2951_pp0_iter4_reg;
reg  signed [7:0] rhs_6_reg_2957;
reg  signed [7:0] rhs_6_reg_2957_pp0_iter4_reg;
reg  signed [7:0] rhs_7_reg_2963;
reg  signed [7:0] rhs_7_reg_2963_pp0_iter4_reg;
wire   [8:0] sub_ln1420_fu_2169_p2;
reg   [8:0] sub_ln1420_reg_2969;
wire   [7:0] acc_V_18_fu_2175_p2;
reg   [7:0] acc_V_18_reg_2974;
wire   [8:0] sub_ln1420_1_fu_2191_p2;
reg   [8:0] sub_ln1420_1_reg_2980;
wire   [7:0] acc_V_20_fu_2197_p2;
reg   [7:0] acc_V_20_reg_2985;
wire   [8:0] sub_ln1420_2_fu_2213_p2;
reg   [8:0] sub_ln1420_2_reg_2991;
wire   [7:0] acc_V_23_fu_2219_p2;
reg   [7:0] acc_V_23_reg_2996;
wire   [8:0] sub_ln1420_3_fu_2235_p2;
reg   [8:0] sub_ln1420_3_reg_3002;
wire   [7:0] acc_V_26_fu_2241_p2;
reg   [7:0] acc_V_26_reg_3007;
wire   [8:0] sub_ln1420_4_fu_2257_p2;
reg   [8:0] sub_ln1420_4_reg_3013;
wire   [7:0] acc_V_29_fu_2263_p2;
reg   [7:0] acc_V_29_reg_3018;
wire   [8:0] sub_ln1420_5_fu_2279_p2;
reg   [8:0] sub_ln1420_5_reg_3024;
wire   [7:0] acc_V_32_fu_2285_p2;
reg   [7:0] acc_V_32_reg_3029;
wire   [8:0] sub_ln1420_6_fu_2301_p2;
reg   [8:0] sub_ln1420_6_reg_3035;
wire   [7:0] acc_V_35_fu_2307_p2;
reg   [7:0] acc_V_35_reg_3040;
wire   [8:0] sub_ln1420_7_fu_2323_p2;
reg   [8:0] sub_ln1420_7_reg_3046;
wire   [7:0] acc_V_38_fu_2329_p2;
reg   [7:0] acc_V_38_reg_3051;
wire   [7:0] acc_V_40_fu_2372_p3;
wire   [7:0] acc_V_39_fu_2378_p3;
wire   [7:0] acc_V_42_fu_2422_p3;
wire   [7:0] acc_V_41_fu_2428_p3;
wire   [7:0] acc_V_44_fu_2472_p3;
wire   [7:0] acc_V_43_fu_2478_p3;
wire   [7:0] acc_V_46_fu_2522_p3;
wire   [7:0] acc_V_45_fu_2528_p3;
wire   [7:0] acc_V_48_fu_2572_p3;
wire   [7:0] acc_V_47_fu_2578_p3;
wire   [7:0] acc_V_50_fu_2622_p3;
wire   [7:0] acc_V_49_fu_2628_p3;
wire   [7:0] acc_V_52_fu_2672_p3;
wire   [7:0] acc_V_51_fu_2678_p3;
wire   [7:0] acc_V_54_fu_2722_p3;
wire   [7:0] acc_V_53_fu_2728_p3;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg   [5:0] ap_phi_mux_ir83_phi_fu_357_p6;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_28_phi_reg_816;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_27_phi_reg_828;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_26_phi_reg_840;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_25_phi_reg_852;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_24_phi_reg_864;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_23_phi_reg_876;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_22_phi_reg_888;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_21_phi_reg_900;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_20_phi_reg_912;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_19_phi_reg_924;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_18_phi_reg_936;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_17_phi_reg_948;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_16_phi_reg_960;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_15_phi_reg_972;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_14_phi_reg_984;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_13_phi_reg_996;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_12_phi_reg_1008;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_11_phi_reg_1020;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_10_phi_reg_1032;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_29_phi_reg_1044;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_9_phi_reg_1056;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_8_phi_reg_1068;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_7_phi_reg_1080;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_6_phi_reg_1092;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_5_phi_reg_1104;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_4_phi_reg_1116;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_3_phi_reg_1128;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_2_phi_reg_1140;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_1_phi_reg_1152;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_30_phi_reg_1164;
wire   [7:0] ap_phi_reg_pp0_iter1_data_V_31_phi_reg_1176;
wire   [7:0] data_V_fu_1466_p1;
wire   [7:0] ap_phi_reg_pp0_iter1_p_phi_reg_1188;
reg   [4:0] ap_phi_mux_in_index84_phi_fu_1204_p6;
reg   [7:0] ap_phi_mux_acc_V82_phi_fu_1218_p6;
reg   [7:0] ap_phi_mux_acc_V_180_phi_fu_1233_p6;
reg   [7:0] ap_phi_mux_acc_V_278_phi_fu_1248_p6;
reg   [7:0] ap_phi_mux_acc_V_376_phi_fu_1263_p6;
reg   [7:0] ap_phi_mux_acc_V_474_phi_fu_1278_p6;
reg   [7:0] ap_phi_mux_acc_V_572_phi_fu_1293_p6;
reg   [7:0] ap_phi_mux_acc_V_670_phi_fu_1308_p6;
reg   [7:0] ap_phi_mux_acc_V_768_phi_fu_1323_p6;
reg   [7:0] ap_phi_mux_acc_V_866_phi_fu_1338_p6;
reg   [7:0] ap_phi_mux_acc_V_964_phi_fu_1353_p6;
reg   [7:0] ap_phi_mux_acc_V_1062_phi_fu_1368_p6;
reg   [7:0] ap_phi_mux_acc_V_1160_phi_fu_1383_p6;
reg   [7:0] ap_phi_mux_acc_V_1258_phi_fu_1398_p6;
reg   [7:0] ap_phi_mux_acc_V_1356_phi_fu_1413_p6;
reg   [7:0] ap_phi_mux_acc_V_1454_phi_fu_1428_p6;
reg   [7:0] ap_phi_mux_acc_V_1552_phi_fu_1443_p6;
wire   [63:0] zext_ln124_fu_1816_p1;
wire   [63:0] p_cast239_fu_1830_p1;
wire   [63:0] p_cast240_cast_cast_fu_1843_p1;
wire   [63:0] p_cast241_cast_cast_cast_cast_cast_fu_1852_p1;
wire   [63:0] p_cast242_cast_cast_fu_1865_p1;
wire   [63:0] p_cast243_fu_1878_p1;
wire   [63:0] p_cast244_cast_cast_cast_cast_cast_fu_1887_p1;
wire   [63:0] p_cast245_cast_cast_cast_cast_cast_fu_1896_p1;
reg    ap_block_pp0_stage0_01001;
wire  signed [6:0] tmp_fu_1822_p3;
wire   [6:0] ir83_cast_fu_1812_p1;
wire  signed [7:0] p_cast240_cast_fu_1835_p3;
wire  signed [7:0] p_cast241_cast_cast_cast_cast_fu_1848_p1;
wire   [8:0] p_cast242_cast_fu_1857_p3;
wire   [8:0] tmp_2_fu_1870_p3;
wire  signed [8:0] p_cast244_cast_cast_cast_cast_fu_1883_p1;
wire  signed [8:0] p_cast245_cast_cast_cast_cast_fu_1892_p1;
wire   [5:0] zext_ln124_1_fu_1901_p1;
wire   [5:0] in_index_1_fu_1975_p2;
wire   [0:0] tmp_3_fu_1987_p3;
wire   [4:0] add_ln109_fu_1981_p2;
wire  signed [7:0] mul_ln1270_fu_2009_p1;
wire  signed [12:0] sext_ln1273_37_fu_2006_p1;
wire   [12:0] mul_ln1270_fu_2009_p2;
wire  signed [7:0] mul_ln1270_3_fu_2028_p1;
wire   [12:0] mul_ln1270_3_fu_2028_p2;
wire  signed [7:0] mul_ln1270_4_fu_2047_p1;
wire   [12:0] mul_ln1270_4_fu_2047_p2;
wire  signed [7:0] mul_ln1270_5_fu_2066_p1;
wire   [12:0] mul_ln1270_5_fu_2066_p2;
wire  signed [7:0] mul_ln1270_6_fu_2085_p1;
wire   [12:0] mul_ln1270_6_fu_2085_p2;
wire  signed [7:0] mul_ln1270_7_fu_2104_p1;
wire   [12:0] mul_ln1270_7_fu_2104_p2;
wire  signed [7:0] mul_ln1270_8_fu_2123_p1;
wire   [12:0] mul_ln1270_8_fu_2123_p2;
wire  signed [7:0] mul_ln1270_9_fu_2142_p1;
wire   [12:0] mul_ln1270_9_fu_2142_p2;
wire  signed [7:0] lhs_fu_2158_p3;
wire  signed [8:0] sext_ln813_fu_2165_p1;
wire  signed [7:0] lhs_1_fu_2180_p3;
wire  signed [8:0] sext_ln813_3_fu_2187_p1;
wire  signed [7:0] lhs_2_fu_2202_p3;
wire  signed [8:0] sext_ln813_5_fu_2209_p1;
wire  signed [7:0] lhs_3_fu_2224_p3;
wire  signed [8:0] sext_ln813_7_fu_2231_p1;
wire  signed [7:0] lhs_4_fu_2246_p3;
wire  signed [8:0] sext_ln813_9_fu_2253_p1;
wire  signed [7:0] lhs_5_fu_2268_p3;
wire  signed [8:0] sext_ln813_11_fu_2275_p1;
wire  signed [7:0] lhs_6_fu_2290_p3;
wire  signed [8:0] sext_ln813_13_fu_2297_p1;
wire  signed [7:0] lhs_7_fu_2312_p3;
wire  signed [8:0] sext_ln813_15_fu_2319_p1;
wire  signed [8:0] sext_ln813_2_fu_2334_p1;
wire   [0:0] icmp_ln1420_fu_2337_p2;
wire   [7:0] select_ln808_fu_2342_p3;
wire   [7:0] select_ln808_1_fu_2349_p3;
wire   [7:0] acc_V_17_fu_2356_p3;
wire   [7:0] acc_V_16_fu_2364_p3;
wire  signed [8:0] sext_ln813_4_fu_2384_p1;
wire   [0:0] icmp_ln1420_1_fu_2387_p2;
wire   [7:0] select_ln808_2_fu_2392_p3;
wire   [7:0] select_ln808_3_fu_2399_p3;
wire   [7:0] acc_V_19_fu_2406_p3;
wire   [7:0] acc_V_fu_2414_p3;
wire  signed [8:0] sext_ln813_6_fu_2434_p1;
wire   [0:0] icmp_ln1420_2_fu_2437_p2;
wire   [7:0] select_ln808_4_fu_2442_p3;
wire   [7:0] select_ln808_5_fu_2449_p3;
wire   [7:0] acc_V_22_fu_2456_p3;
wire   [7:0] acc_V_21_fu_2464_p3;
wire  signed [8:0] sext_ln813_8_fu_2484_p1;
wire   [0:0] icmp_ln1420_3_fu_2487_p2;
wire   [7:0] select_ln808_6_fu_2492_p3;
wire   [7:0] select_ln808_7_fu_2499_p3;
wire   [7:0] acc_V_25_fu_2506_p3;
wire   [7:0] acc_V_24_fu_2514_p3;
wire  signed [8:0] sext_ln813_10_fu_2534_p1;
wire   [0:0] icmp_ln1420_4_fu_2537_p2;
wire   [7:0] select_ln808_8_fu_2542_p3;
wire   [7:0] select_ln808_9_fu_2549_p3;
wire   [7:0] acc_V_28_fu_2556_p3;
wire   [7:0] acc_V_27_fu_2564_p3;
wire  signed [8:0] sext_ln813_12_fu_2584_p1;
wire   [0:0] icmp_ln1420_5_fu_2587_p2;
wire   [7:0] select_ln808_10_fu_2592_p3;
wire   [7:0] select_ln808_11_fu_2599_p3;
wire   [7:0] acc_V_31_fu_2606_p3;
wire   [7:0] acc_V_30_fu_2614_p3;
wire  signed [8:0] sext_ln813_14_fu_2634_p1;
wire   [0:0] icmp_ln1420_6_fu_2637_p2;
wire   [7:0] select_ln808_12_fu_2642_p3;
wire   [7:0] select_ln808_13_fu_2649_p3;
wire   [7:0] acc_V_34_fu_2656_p3;
wire   [7:0] acc_V_33_fu_2664_p3;
wire  signed [8:0] sext_ln813_16_fu_2684_p1;
wire   [0:0] icmp_ln1420_7_fu_2687_p2;
wire   [7:0] select_ln808_14_fu_2692_p3;
wire   [7:0] select_ln808_15_fu_2699_p3;
wire   [7:0] acc_V_37_fu_2706_p3;
wire   [7:0] acc_V_36_fu_2714_p3;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_idle_pp0_0to4;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_138;
reg    ap_condition_484;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

inference_dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_s_outidx_ROM_AUdEe #(
    .DataWidth( 1 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
outidx_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(outidx_address0),
    .ce0(outidx_ce0),
    .q0(outidx_q0)
);

inference_dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_s_w6_V_ROM_AUTOeOg #(
    .DataWidth( 8 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
w6_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w6_V_address0),
    .ce0(w6_V_ce0),
    .q0(w6_V_q0),
    .address1(w6_V_address1),
    .ce1(w6_V_ce1),
    .q1(w6_V_q1),
    .address2(w6_V_address2),
    .ce2(w6_V_ce2),
    .q2(w6_V_q2),
    .address3(w6_V_address3),
    .ce3(w6_V_ce3),
    .q3(w6_V_q3),
    .address4(w6_V_address4),
    .ce4(w6_V_ce4),
    .q4(w6_V_q4),
    .address5(w6_V_address5),
    .ce5(w6_V_ce5),
    .q5(w6_V_q5),
    .address6(w6_V_address6),
    .ce6(w6_V_ce6),
    .q6(w6_V_q6),
    .address7(w6_V_address7),
    .ce7(w6_V_ce7),
    .q7(w6_V_q7)
);

inference_mux_325_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 8 ))
mux_325_8_1_1_U52(
    .din0(p_phi_reg_1188),
    .din1(data_V_1_phi_reg_1152),
    .din2(data_V_2_phi_reg_1140),
    .din3(data_V_3_phi_reg_1128),
    .din4(data_V_4_phi_reg_1116),
    .din5(data_V_5_phi_reg_1104),
    .din6(data_V_6_phi_reg_1092),
    .din7(data_V_7_phi_reg_1080),
    .din8(data_V_8_phi_reg_1068),
    .din9(data_V_9_phi_reg_1056),
    .din10(data_V_29_phi_reg_1044),
    .din11(data_V_10_phi_reg_1032),
    .din12(data_V_11_phi_reg_1020),
    .din13(data_V_12_phi_reg_1008),
    .din14(data_V_13_phi_reg_996),
    .din15(data_V_14_phi_reg_984),
    .din16(data_V_15_phi_reg_972),
    .din17(data_V_16_phi_reg_960),
    .din18(data_V_17_phi_reg_948),
    .din19(data_V_18_phi_reg_936),
    .din20(data_V_19_phi_reg_924),
    .din21(data_V_20_phi_reg_912),
    .din22(data_V_21_phi_reg_900),
    .din23(data_V_22_phi_reg_888),
    .din24(data_V_23_phi_reg_876),
    .din25(data_V_24_phi_reg_864),
    .din26(data_V_25_phi_reg_852),
    .din27(data_V_26_phi_reg_840),
    .din28(data_V_27_phi_reg_828),
    .din29(data_V_28_phi_reg_816),
    .din30(data_V_31_phi_reg_1176),
    .din31(data_V_30_phi_reg_1164),
    .din32(ap_phi_mux_in_index84_phi_fu_1204_p6),
    .dout(a_V_fu_1905_p34)
);

inference_mul_8s_8s_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_8s_8s_13_1_1_U53(
    .din0(w_V_reg_2876),
    .din1(mul_ln1270_fu_2009_p1),
    .dout(mul_ln1270_fu_2009_p2)
);

inference_mul_8s_8s_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_8s_8s_13_1_1_U54(
    .din0(w_V_1_reg_2881),
    .din1(mul_ln1270_3_fu_2028_p1),
    .dout(mul_ln1270_3_fu_2028_p2)
);

inference_mul_8s_8s_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_8s_8s_13_1_1_U55(
    .din0(w_V_2_reg_2886),
    .din1(mul_ln1270_4_fu_2047_p1),
    .dout(mul_ln1270_4_fu_2047_p2)
);

inference_mul_8s_8s_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_8s_8s_13_1_1_U56(
    .din0(w_V_3_reg_2891),
    .din1(mul_ln1270_5_fu_2066_p1),
    .dout(mul_ln1270_5_fu_2066_p2)
);

inference_mul_8s_8s_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_8s_8s_13_1_1_U57(
    .din0(w_V_4_reg_2896),
    .din1(mul_ln1270_6_fu_2085_p1),
    .dout(mul_ln1270_6_fu_2085_p2)
);

inference_mul_8s_8s_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_8s_8s_13_1_1_U58(
    .din0(w_V_5_reg_2901),
    .din1(mul_ln1270_7_fu_2104_p1),
    .dout(mul_ln1270_7_fu_2104_p2)
);

inference_mul_8s_8s_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_8s_8s_13_1_1_U59(
    .din0(w_V_6_reg_2906),
    .din1(mul_ln1270_8_fu_2123_p1),
    .dout(mul_ln1270_8_fu_2123_p2)
);

inference_mul_8s_8s_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_8s_8s_13_1_1_U60(
    .din0(w_V_7_reg_2911),
    .din1(mul_ln1270_9_fu_2142_p1),
    .dout(mul_ln1270_9_fu_2142_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= real_start;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0))) begin
        acc_V82_reg_1214 <= acc_V_39_fu_2378_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V82_reg_1214 <= 8'd255;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0))) begin
        acc_V_1062_reg_1364 <= acc_V_49_fu_2628_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_1062_reg_1364 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0))) begin
        acc_V_1160_reg_1379 <= acc_V_50_fu_2622_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_1160_reg_1379 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0))) begin
        acc_V_1258_reg_1394 <= acc_V_51_fu_2678_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_1258_reg_1394 <= 8'd255;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0))) begin
        acc_V_1356_reg_1409 <= acc_V_52_fu_2672_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_1356_reg_1409 <= 8'd255;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0))) begin
        acc_V_1454_reg_1424 <= acc_V_53_fu_2728_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_1454_reg_1424 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0))) begin
        acc_V_1552_reg_1439 <= acc_V_54_fu_2722_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_1552_reg_1439 <= 8'd255;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0))) begin
        acc_V_180_reg_1229 <= acc_V_40_fu_2372_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_180_reg_1229 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0))) begin
        acc_V_278_reg_1244 <= acc_V_41_fu_2428_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_278_reg_1244 <= 8'd255;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0))) begin
        acc_V_376_reg_1259 <= acc_V_42_fu_2422_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_376_reg_1259 <= 8'd255;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0))) begin
        acc_V_474_reg_1274 <= acc_V_43_fu_2478_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_474_reg_1274 <= 8'd255;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0))) begin
        acc_V_572_reg_1289 <= acc_V_44_fu_2472_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_572_reg_1289 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0))) begin
        acc_V_670_reg_1304 <= acc_V_45_fu_2528_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_670_reg_1304 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0))) begin
        acc_V_768_reg_1319 <= acc_V_46_fu_2522_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_768_reg_1319 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0))) begin
        acc_V_866_reg_1334 <= acc_V_47_fu_2578_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_866_reg_1334 <= 8'd255;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0))) begin
        acc_V_964_reg_1349 <= acc_V_48_fu_2572_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_964_reg_1349 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_10_phi_reg_1032 <= data_V_10_phi_reg_1032;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_10_phi_reg_1032 <= {{layer5_out_dout[95:88]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_10_phi_reg_1032 <= ap_phi_reg_pp0_iter1_data_V_10_phi_reg_1032;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_11_phi_reg_1020 <= data_V_11_phi_reg_1020;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_11_phi_reg_1020 <= {{layer5_out_dout[103:96]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_11_phi_reg_1020 <= ap_phi_reg_pp0_iter1_data_V_11_phi_reg_1020;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_12_phi_reg_1008 <= data_V_12_phi_reg_1008;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_12_phi_reg_1008 <= {{layer5_out_dout[111:104]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_12_phi_reg_1008 <= ap_phi_reg_pp0_iter1_data_V_12_phi_reg_1008;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_13_phi_reg_996 <= data_V_13_phi_reg_996;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_13_phi_reg_996 <= {{layer5_out_dout[119:112]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_13_phi_reg_996 <= ap_phi_reg_pp0_iter1_data_V_13_phi_reg_996;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_14_phi_reg_984 <= data_V_14_phi_reg_984;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_14_phi_reg_984 <= {{layer5_out_dout[127:120]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_14_phi_reg_984 <= ap_phi_reg_pp0_iter1_data_V_14_phi_reg_984;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_15_phi_reg_972 <= data_V_15_phi_reg_972;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_15_phi_reg_972 <= {{layer5_out_dout[135:128]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_15_phi_reg_972 <= ap_phi_reg_pp0_iter1_data_V_15_phi_reg_972;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_16_phi_reg_960 <= data_V_16_phi_reg_960;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_16_phi_reg_960 <= {{layer5_out_dout[143:136]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_16_phi_reg_960 <= ap_phi_reg_pp0_iter1_data_V_16_phi_reg_960;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_17_phi_reg_948 <= data_V_17_phi_reg_948;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_17_phi_reg_948 <= {{layer5_out_dout[151:144]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_17_phi_reg_948 <= ap_phi_reg_pp0_iter1_data_V_17_phi_reg_948;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_18_phi_reg_936 <= data_V_18_phi_reg_936;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_18_phi_reg_936 <= {{layer5_out_dout[159:152]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_18_phi_reg_936 <= ap_phi_reg_pp0_iter1_data_V_18_phi_reg_936;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_19_phi_reg_924 <= data_V_19_phi_reg_924;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_19_phi_reg_924 <= {{layer5_out_dout[167:160]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_19_phi_reg_924 <= ap_phi_reg_pp0_iter1_data_V_19_phi_reg_924;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_1_phi_reg_1152 <= data_V_1_phi_reg_1152;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_1_phi_reg_1152 <= {{layer5_out_dout[15:8]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_1_phi_reg_1152 <= ap_phi_reg_pp0_iter1_data_V_1_phi_reg_1152;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_20_phi_reg_912 <= data_V_20_phi_reg_912;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_20_phi_reg_912 <= {{layer5_out_dout[175:168]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_20_phi_reg_912 <= ap_phi_reg_pp0_iter1_data_V_20_phi_reg_912;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_21_phi_reg_900 <= data_V_21_phi_reg_900;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_21_phi_reg_900 <= {{layer5_out_dout[183:176]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_21_phi_reg_900 <= ap_phi_reg_pp0_iter1_data_V_21_phi_reg_900;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_22_phi_reg_888 <= data_V_22_phi_reg_888;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_22_phi_reg_888 <= {{layer5_out_dout[191:184]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_22_phi_reg_888 <= ap_phi_reg_pp0_iter1_data_V_22_phi_reg_888;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_23_phi_reg_876 <= data_V_23_phi_reg_876;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_23_phi_reg_876 <= {{layer5_out_dout[199:192]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_23_phi_reg_876 <= ap_phi_reg_pp0_iter1_data_V_23_phi_reg_876;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_24_phi_reg_864 <= data_V_24_phi_reg_864;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_24_phi_reg_864 <= {{layer5_out_dout[207:200]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_24_phi_reg_864 <= ap_phi_reg_pp0_iter1_data_V_24_phi_reg_864;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_25_phi_reg_852 <= data_V_25_phi_reg_852;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_25_phi_reg_852 <= {{layer5_out_dout[215:208]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_25_phi_reg_852 <= ap_phi_reg_pp0_iter1_data_V_25_phi_reg_852;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_26_phi_reg_840 <= data_V_26_phi_reg_840;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_26_phi_reg_840 <= {{layer5_out_dout[223:216]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_26_phi_reg_840 <= ap_phi_reg_pp0_iter1_data_V_26_phi_reg_840;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_27_phi_reg_828 <= data_V_27_phi_reg_828;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_27_phi_reg_828 <= {{layer5_out_dout[231:224]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_27_phi_reg_828 <= ap_phi_reg_pp0_iter1_data_V_27_phi_reg_828;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_28_phi_reg_816 <= data_V_28_phi_reg_816;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_28_phi_reg_816 <= {{layer5_out_dout[239:232]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_28_phi_reg_816 <= ap_phi_reg_pp0_iter1_data_V_28_phi_reg_816;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_29_phi_reg_1044 <= data_V_29_phi_reg_1044;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_29_phi_reg_1044 <= {{layer5_out_dout[87:80]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_29_phi_reg_1044 <= ap_phi_reg_pp0_iter1_data_V_29_phi_reg_1044;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_2_phi_reg_1140 <= data_V_2_phi_reg_1140;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_2_phi_reg_1140 <= {{layer5_out_dout[23:16]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_2_phi_reg_1140 <= ap_phi_reg_pp0_iter1_data_V_2_phi_reg_1140;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_30_phi_reg_1164 <= data_V_30_phi_reg_1164;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_30_phi_reg_1164 <= {{layer5_out_dout[255:248]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_30_phi_reg_1164 <= ap_phi_reg_pp0_iter1_data_V_30_phi_reg_1164;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_31_phi_reg_1176 <= data_V_31_phi_reg_1176;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_31_phi_reg_1176 <= {{layer5_out_dout[247:240]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_31_phi_reg_1176 <= ap_phi_reg_pp0_iter1_data_V_31_phi_reg_1176;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_3_phi_reg_1128 <= data_V_3_phi_reg_1128;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_3_phi_reg_1128 <= {{layer5_out_dout[31:24]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_3_phi_reg_1128 <= ap_phi_reg_pp0_iter1_data_V_3_phi_reg_1128;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_4_phi_reg_1116 <= data_V_4_phi_reg_1116;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_4_phi_reg_1116 <= {{layer5_out_dout[39:32]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_4_phi_reg_1116 <= ap_phi_reg_pp0_iter1_data_V_4_phi_reg_1116;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_5_phi_reg_1104 <= data_V_5_phi_reg_1104;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_5_phi_reg_1104 <= {{layer5_out_dout[47:40]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_5_phi_reg_1104 <= ap_phi_reg_pp0_iter1_data_V_5_phi_reg_1104;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_6_phi_reg_1092 <= data_V_6_phi_reg_1092;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_6_phi_reg_1092 <= {{layer5_out_dout[55:48]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_6_phi_reg_1092 <= ap_phi_reg_pp0_iter1_data_V_6_phi_reg_1092;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_7_phi_reg_1080 <= data_V_7_phi_reg_1080;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_7_phi_reg_1080 <= {{layer5_out_dout[63:56]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_7_phi_reg_1080 <= ap_phi_reg_pp0_iter1_data_V_7_phi_reg_1080;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_8_phi_reg_1068 <= data_V_8_phi_reg_1068;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_8_phi_reg_1068 <= {{layer5_out_dout[71:64]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_8_phi_reg_1068 <= ap_phi_reg_pp0_iter1_data_V_8_phi_reg_1068;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            data_V_9_phi_reg_1056 <= data_V_9_phi_reg_1056;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            data_V_9_phi_reg_1056 <= {{layer5_out_dout[79:72]}};
        end else if ((1'b1 == 1'b1)) begin
            data_V_9_phi_reg_1056 <= ap_phi_reg_pp0_iter1_data_V_9_phi_reg_1056;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter1_reg == 1'd0))) begin
        do_init_reg_337 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter1_reg == 1'd1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        do_init_reg_337 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter2_reg == 1'd0))) begin
        in_index84_reg_1200 <= in_index_reg_2916;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter2_reg == 1'd1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_index84_reg_1200 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln124_reg_2778 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ir83_reg_353 <= ir_reg_2773;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln124_reg_2778 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        ir83_reg_353 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_484)) begin
        if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd0)) begin
            p_phi_reg_1188 <= p_phi_reg_1188;
        end else if ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1)) begin
            p_phi_reg_1188 <= data_V_fu_1466_p1;
        end else if ((1'b1 == 1'b1)) begin
            p_phi_reg_1188 <= ap_phi_reg_pp0_iter1_p_phi_reg_1188;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        a_V_reg_2871 <= a_V_fu_1905_p34;
        acc_V_18_reg_2974 <= acc_V_18_fu_2175_p2;
        acc_V_20_reg_2985 <= acc_V_20_fu_2197_p2;
        acc_V_23_reg_2996 <= acc_V_23_fu_2219_p2;
        acc_V_26_reg_3007 <= acc_V_26_fu_2241_p2;
        acc_V_29_reg_3018 <= acc_V_29_fu_2263_p2;
        acc_V_32_reg_3029 <= acc_V_32_fu_2285_p2;
        acc_V_35_reg_3040 <= acc_V_35_fu_2307_p2;
        acc_V_38_reg_3051 <= acc_V_38_fu_2329_p2;
        icmp_ln124_reg_2778_pp0_iter2_reg <= icmp_ln124_reg_2778_pp0_iter1_reg;
        icmp_ln124_reg_2778_pp0_iter3_reg <= icmp_ln124_reg_2778_pp0_iter2_reg;
        icmp_ln124_reg_2778_pp0_iter4_reg <= icmp_ln124_reg_2778_pp0_iter3_reg;
        out_index_reg_2827 <= outidx_q0;
        out_index_reg_2827_pp0_iter3_reg <= out_index_reg_2827;
        out_index_reg_2827_pp0_iter4_reg <= out_index_reg_2827_pp0_iter3_reg;
        rhs_1_reg_2927 <= {{mul_ln1270_3_fu_2028_p2[12:5]}};
        rhs_1_reg_2927_pp0_iter4_reg <= rhs_1_reg_2927;
        rhs_2_reg_2933 <= {{mul_ln1270_4_fu_2047_p2[12:5]}};
        rhs_2_reg_2933_pp0_iter4_reg <= rhs_2_reg_2933;
        rhs_3_reg_2939 <= {{mul_ln1270_5_fu_2066_p2[12:5]}};
        rhs_3_reg_2939_pp0_iter4_reg <= rhs_3_reg_2939;
        rhs_4_reg_2945 <= {{mul_ln1270_6_fu_2085_p2[12:5]}};
        rhs_4_reg_2945_pp0_iter4_reg <= rhs_4_reg_2945;
        rhs_5_reg_2951 <= {{mul_ln1270_7_fu_2104_p2[12:5]}};
        rhs_5_reg_2951_pp0_iter4_reg <= rhs_5_reg_2951;
        rhs_6_reg_2957 <= {{mul_ln1270_8_fu_2123_p2[12:5]}};
        rhs_6_reg_2957_pp0_iter4_reg <= rhs_6_reg_2957;
        rhs_7_reg_2963 <= {{mul_ln1270_9_fu_2142_p2[12:5]}};
        rhs_7_reg_2963_pp0_iter4_reg <= rhs_7_reg_2963;
        rhs_reg_2921 <= {{mul_ln1270_fu_2009_p2[12:5]}};
        rhs_reg_2921_pp0_iter4_reg <= rhs_reg_2921;
        sub_ln1420_1_reg_2980 <= sub_ln1420_1_fu_2191_p2;
        sub_ln1420_2_reg_2991 <= sub_ln1420_2_fu_2213_p2;
        sub_ln1420_3_reg_3002 <= sub_ln1420_3_fu_2235_p2;
        sub_ln1420_4_reg_3013 <= sub_ln1420_4_fu_2257_p2;
        sub_ln1420_5_reg_3024 <= sub_ln1420_5_fu_2279_p2;
        sub_ln1420_6_reg_3035 <= sub_ln1420_6_fu_2301_p2;
        sub_ln1420_7_reg_3046 <= sub_ln1420_7_fu_2323_p2;
        sub_ln1420_reg_2969 <= sub_ln1420_fu_2169_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln124_reg_2778 <= icmp_ln124_fu_1460_p2;
        icmp_ln124_reg_2778_pp0_iter1_reg <= icmp_ln124_reg_2778;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        in_index_reg_2916 <= in_index_fu_1995_p3;
        w_V_1_reg_2881 <= w6_V_q6;
        w_V_2_reg_2886 <= w6_V_q5;
        w_V_3_reg_2891 <= w6_V_q4;
        w_V_4_reg_2896 <= w6_V_q3;
        w_V_5_reg_2901 <= w6_V_q2;
        w_V_6_reg_2906 <= w6_V_q1;
        w_V_7_reg_2911 <= w6_V_q0;
        w_V_reg_2876 <= w6_V_q7;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ir_reg_2773 <= ir_fu_1454_p2;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0_0to4 = 1'b1;
    end else begin
        ap_idle_pp0_0to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) begin
            ap_phi_mux_acc_V82_phi_fu_1218_p6 = 8'd255;
        end else if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0)) begin
            ap_phi_mux_acc_V82_phi_fu_1218_p6 = acc_V_39_fu_2378_p3;
        end else begin
            ap_phi_mux_acc_V82_phi_fu_1218_p6 = acc_V82_reg_1214;
        end
    end else begin
        ap_phi_mux_acc_V82_phi_fu_1218_p6 = acc_V82_reg_1214;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) begin
            ap_phi_mux_acc_V_1062_phi_fu_1368_p6 = 8'd0;
        end else if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0)) begin
            ap_phi_mux_acc_V_1062_phi_fu_1368_p6 = acc_V_49_fu_2628_p3;
        end else begin
            ap_phi_mux_acc_V_1062_phi_fu_1368_p6 = acc_V_1062_reg_1364;
        end
    end else begin
        ap_phi_mux_acc_V_1062_phi_fu_1368_p6 = acc_V_1062_reg_1364;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) begin
            ap_phi_mux_acc_V_1160_phi_fu_1383_p6 = 8'd0;
        end else if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0)) begin
            ap_phi_mux_acc_V_1160_phi_fu_1383_p6 = acc_V_50_fu_2622_p3;
        end else begin
            ap_phi_mux_acc_V_1160_phi_fu_1383_p6 = acc_V_1160_reg_1379;
        end
    end else begin
        ap_phi_mux_acc_V_1160_phi_fu_1383_p6 = acc_V_1160_reg_1379;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) begin
            ap_phi_mux_acc_V_1258_phi_fu_1398_p6 = 8'd255;
        end else if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0)) begin
            ap_phi_mux_acc_V_1258_phi_fu_1398_p6 = acc_V_51_fu_2678_p3;
        end else begin
            ap_phi_mux_acc_V_1258_phi_fu_1398_p6 = acc_V_1258_reg_1394;
        end
    end else begin
        ap_phi_mux_acc_V_1258_phi_fu_1398_p6 = acc_V_1258_reg_1394;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) begin
            ap_phi_mux_acc_V_1356_phi_fu_1413_p6 = 8'd255;
        end else if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0)) begin
            ap_phi_mux_acc_V_1356_phi_fu_1413_p6 = acc_V_52_fu_2672_p3;
        end else begin
            ap_phi_mux_acc_V_1356_phi_fu_1413_p6 = acc_V_1356_reg_1409;
        end
    end else begin
        ap_phi_mux_acc_V_1356_phi_fu_1413_p6 = acc_V_1356_reg_1409;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) begin
            ap_phi_mux_acc_V_1454_phi_fu_1428_p6 = 8'd0;
        end else if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0)) begin
            ap_phi_mux_acc_V_1454_phi_fu_1428_p6 = acc_V_53_fu_2728_p3;
        end else begin
            ap_phi_mux_acc_V_1454_phi_fu_1428_p6 = acc_V_1454_reg_1424;
        end
    end else begin
        ap_phi_mux_acc_V_1454_phi_fu_1428_p6 = acc_V_1454_reg_1424;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) begin
            ap_phi_mux_acc_V_1552_phi_fu_1443_p6 = 8'd255;
        end else if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0)) begin
            ap_phi_mux_acc_V_1552_phi_fu_1443_p6 = acc_V_54_fu_2722_p3;
        end else begin
            ap_phi_mux_acc_V_1552_phi_fu_1443_p6 = acc_V_1552_reg_1439;
        end
    end else begin
        ap_phi_mux_acc_V_1552_phi_fu_1443_p6 = acc_V_1552_reg_1439;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) begin
            ap_phi_mux_acc_V_180_phi_fu_1233_p6 = 8'd0;
        end else if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0)) begin
            ap_phi_mux_acc_V_180_phi_fu_1233_p6 = acc_V_40_fu_2372_p3;
        end else begin
            ap_phi_mux_acc_V_180_phi_fu_1233_p6 = acc_V_180_reg_1229;
        end
    end else begin
        ap_phi_mux_acc_V_180_phi_fu_1233_p6 = acc_V_180_reg_1229;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) begin
            ap_phi_mux_acc_V_278_phi_fu_1248_p6 = 8'd255;
        end else if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0)) begin
            ap_phi_mux_acc_V_278_phi_fu_1248_p6 = acc_V_41_fu_2428_p3;
        end else begin
            ap_phi_mux_acc_V_278_phi_fu_1248_p6 = acc_V_278_reg_1244;
        end
    end else begin
        ap_phi_mux_acc_V_278_phi_fu_1248_p6 = acc_V_278_reg_1244;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) begin
            ap_phi_mux_acc_V_376_phi_fu_1263_p6 = 8'd255;
        end else if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0)) begin
            ap_phi_mux_acc_V_376_phi_fu_1263_p6 = acc_V_42_fu_2422_p3;
        end else begin
            ap_phi_mux_acc_V_376_phi_fu_1263_p6 = acc_V_376_reg_1259;
        end
    end else begin
        ap_phi_mux_acc_V_376_phi_fu_1263_p6 = acc_V_376_reg_1259;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) begin
            ap_phi_mux_acc_V_474_phi_fu_1278_p6 = 8'd255;
        end else if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0)) begin
            ap_phi_mux_acc_V_474_phi_fu_1278_p6 = acc_V_43_fu_2478_p3;
        end else begin
            ap_phi_mux_acc_V_474_phi_fu_1278_p6 = acc_V_474_reg_1274;
        end
    end else begin
        ap_phi_mux_acc_V_474_phi_fu_1278_p6 = acc_V_474_reg_1274;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) begin
            ap_phi_mux_acc_V_572_phi_fu_1293_p6 = 8'd0;
        end else if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0)) begin
            ap_phi_mux_acc_V_572_phi_fu_1293_p6 = acc_V_44_fu_2472_p3;
        end else begin
            ap_phi_mux_acc_V_572_phi_fu_1293_p6 = acc_V_572_reg_1289;
        end
    end else begin
        ap_phi_mux_acc_V_572_phi_fu_1293_p6 = acc_V_572_reg_1289;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) begin
            ap_phi_mux_acc_V_670_phi_fu_1308_p6 = 8'd0;
        end else if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0)) begin
            ap_phi_mux_acc_V_670_phi_fu_1308_p6 = acc_V_45_fu_2528_p3;
        end else begin
            ap_phi_mux_acc_V_670_phi_fu_1308_p6 = acc_V_670_reg_1304;
        end
    end else begin
        ap_phi_mux_acc_V_670_phi_fu_1308_p6 = acc_V_670_reg_1304;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) begin
            ap_phi_mux_acc_V_768_phi_fu_1323_p6 = 8'd0;
        end else if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0)) begin
            ap_phi_mux_acc_V_768_phi_fu_1323_p6 = acc_V_46_fu_2522_p3;
        end else begin
            ap_phi_mux_acc_V_768_phi_fu_1323_p6 = acc_V_768_reg_1319;
        end
    end else begin
        ap_phi_mux_acc_V_768_phi_fu_1323_p6 = acc_V_768_reg_1319;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) begin
            ap_phi_mux_acc_V_866_phi_fu_1338_p6 = 8'd255;
        end else if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0)) begin
            ap_phi_mux_acc_V_866_phi_fu_1338_p6 = acc_V_47_fu_2578_p3;
        end else begin
            ap_phi_mux_acc_V_866_phi_fu_1338_p6 = acc_V_866_reg_1334;
        end
    end else begin
        ap_phi_mux_acc_V_866_phi_fu_1338_p6 = acc_V_866_reg_1334;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1)) begin
            ap_phi_mux_acc_V_964_phi_fu_1353_p6 = 8'd0;
        end else if ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd0)) begin
            ap_phi_mux_acc_V_964_phi_fu_1353_p6 = acc_V_48_fu_2572_p3;
        end else begin
            ap_phi_mux_acc_V_964_phi_fu_1353_p6 = acc_V_964_reg_1349;
        end
    end else begin
        ap_phi_mux_acc_V_964_phi_fu_1353_p6 = acc_V_964_reg_1349;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln124_reg_2778_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_do_init_phi_fu_341_p6 = 1'd1;
        end else if ((icmp_ln124_reg_2778_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_do_init_phi_fu_341_p6 = 1'd0;
        end else begin
            ap_phi_mux_do_init_phi_fu_341_p6 = do_init_reg_337;
        end
    end else begin
        ap_phi_mux_do_init_phi_fu_341_p6 = do_init_reg_337;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if ((icmp_ln124_reg_2778_pp0_iter2_reg == 1'd1)) begin
            ap_phi_mux_in_index84_phi_fu_1204_p6 = 5'd0;
        end else if ((icmp_ln124_reg_2778_pp0_iter2_reg == 1'd0)) begin
            ap_phi_mux_in_index84_phi_fu_1204_p6 = in_index_reg_2916;
        end else begin
            ap_phi_mux_in_index84_phi_fu_1204_p6 = in_index84_reg_1200;
        end
    end else begin
        ap_phi_mux_in_index84_phi_fu_1204_p6 = in_index84_reg_1200;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_138)) begin
        if ((icmp_ln124_reg_2778 == 1'd1)) begin
            ap_phi_mux_ir83_phi_fu_357_p6 = 6'd0;
        end else if ((icmp_ln124_reg_2778 == 1'd0)) begin
            ap_phi_mux_ir83_phi_fu_357_p6 = ir_reg_2773;
        end else begin
            ap_phi_mux_ir83_phi_fu_357_p6 = ir83_reg_353;
        end
    end else begin
        ap_phi_mux_ir83_phi_fu_357_p6 = ir83_reg_353;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (ap_idle_pp0_0to4 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln124_fu_1460_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer5_out_blk_n = layer5_out_empty_n;
    end else begin
        layer5_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer5_out_read = 1'b1;
    end else begin
        layer5_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1))) begin
        layer6_out_blk_n = layer6_out_full_n;
    end else begin
        layer6_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1))) begin
        layer6_out_write = 1'b1;
    end else begin
        layer6_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        outidx_ce0 = 1'b1;
    end else begin
        outidx_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w6_V_ce0 = 1'b1;
    end else begin
        w6_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w6_V_ce1 = 1'b1;
    end else begin
        w6_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w6_V_ce2 = 1'b1;
    end else begin
        w6_V_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w6_V_ce3 = 1'b1;
    end else begin
        w6_V_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w6_V_ce4 = 1'b1;
    end else begin
        w6_V_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w6_V_ce5 = 1'b1;
    end else begin
        w6_V_ce5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w6_V_ce6 = 1'b1;
    end else begin
        w6_V_ce6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w6_V_ce7 = 1'b1;
    end else begin
        w6_V_ce7 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_V_16_fu_2364_p3 = ((icmp_ln1420_fu_2337_p2[0:0] == 1'b1) ? select_ln808_1_fu_2349_p3 : acc_V82_reg_1214);

assign acc_V_17_fu_2356_p3 = ((icmp_ln1420_fu_2337_p2[0:0] == 1'b1) ? select_ln808_fu_2342_p3 : acc_V_180_reg_1229);

assign acc_V_18_fu_2175_p2 = ($signed(rhs_reg_2921) + $signed(lhs_fu_2158_p3));

assign acc_V_19_fu_2406_p3 = ((icmp_ln1420_1_fu_2387_p2[0:0] == 1'b1) ? select_ln808_2_fu_2392_p3 : acc_V_376_reg_1259);

assign acc_V_20_fu_2197_p2 = ($signed(rhs_1_reg_2927) + $signed(lhs_1_fu_2180_p3));

assign acc_V_21_fu_2464_p3 = ((icmp_ln1420_2_fu_2437_p2[0:0] == 1'b1) ? select_ln808_5_fu_2449_p3 : acc_V_474_reg_1274);

assign acc_V_22_fu_2456_p3 = ((icmp_ln1420_2_fu_2437_p2[0:0] == 1'b1) ? select_ln808_4_fu_2442_p3 : acc_V_572_reg_1289);

assign acc_V_23_fu_2219_p2 = ($signed(rhs_2_reg_2933) + $signed(lhs_2_fu_2202_p3));

assign acc_V_24_fu_2514_p3 = ((icmp_ln1420_3_fu_2487_p2[0:0] == 1'b1) ? select_ln808_7_fu_2499_p3 : acc_V_670_reg_1304);

assign acc_V_25_fu_2506_p3 = ((icmp_ln1420_3_fu_2487_p2[0:0] == 1'b1) ? select_ln808_6_fu_2492_p3 : acc_V_768_reg_1319);

assign acc_V_26_fu_2241_p2 = ($signed(rhs_3_reg_2939) + $signed(lhs_3_fu_2224_p3));

assign acc_V_27_fu_2564_p3 = ((icmp_ln1420_4_fu_2537_p2[0:0] == 1'b1) ? select_ln808_9_fu_2549_p3 : acc_V_866_reg_1334);

assign acc_V_28_fu_2556_p3 = ((icmp_ln1420_4_fu_2537_p2[0:0] == 1'b1) ? select_ln808_8_fu_2542_p3 : acc_V_964_reg_1349);

assign acc_V_29_fu_2263_p2 = ($signed(rhs_4_reg_2945) + $signed(lhs_4_fu_2246_p3));

assign acc_V_30_fu_2614_p3 = ((icmp_ln1420_5_fu_2587_p2[0:0] == 1'b1) ? select_ln808_11_fu_2599_p3 : acc_V_1062_reg_1364);

assign acc_V_31_fu_2606_p3 = ((icmp_ln1420_5_fu_2587_p2[0:0] == 1'b1) ? select_ln808_10_fu_2592_p3 : acc_V_1160_reg_1379);

assign acc_V_32_fu_2285_p2 = ($signed(rhs_5_reg_2951) + $signed(lhs_5_fu_2268_p3));

assign acc_V_33_fu_2664_p3 = ((icmp_ln1420_6_fu_2637_p2[0:0] == 1'b1) ? select_ln808_13_fu_2649_p3 : acc_V_1258_reg_1394);

assign acc_V_34_fu_2656_p3 = ((icmp_ln1420_6_fu_2637_p2[0:0] == 1'b1) ? select_ln808_12_fu_2642_p3 : acc_V_1356_reg_1409);

assign acc_V_35_fu_2307_p2 = ($signed(rhs_6_reg_2957) + $signed(lhs_6_fu_2290_p3));

assign acc_V_36_fu_2714_p3 = ((icmp_ln1420_7_fu_2687_p2[0:0] == 1'b1) ? select_ln808_15_fu_2699_p3 : acc_V_1454_reg_1424);

assign acc_V_37_fu_2706_p3 = ((icmp_ln1420_7_fu_2687_p2[0:0] == 1'b1) ? select_ln808_14_fu_2692_p3 : acc_V_1552_reg_1439);

assign acc_V_38_fu_2329_p2 = ($signed(rhs_7_reg_2963) + $signed(lhs_7_fu_2312_p3));

assign acc_V_39_fu_2378_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_16_fu_2364_p3 : acc_V_18_reg_2974);

assign acc_V_40_fu_2372_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_18_reg_2974 : acc_V_17_fu_2356_p3);

assign acc_V_41_fu_2428_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_fu_2414_p3 : acc_V_20_reg_2985);

assign acc_V_42_fu_2422_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_20_reg_2985 : acc_V_19_fu_2406_p3);

assign acc_V_43_fu_2478_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_21_fu_2464_p3 : acc_V_23_reg_2996);

assign acc_V_44_fu_2472_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_23_reg_2996 : acc_V_22_fu_2456_p3);

assign acc_V_45_fu_2528_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_24_fu_2514_p3 : acc_V_26_reg_3007);

assign acc_V_46_fu_2522_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_26_reg_3007 : acc_V_25_fu_2506_p3);

assign acc_V_47_fu_2578_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_27_fu_2564_p3 : acc_V_29_reg_3018);

assign acc_V_48_fu_2572_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_29_reg_3018 : acc_V_28_fu_2556_p3);

assign acc_V_49_fu_2628_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_30_fu_2614_p3 : acc_V_32_reg_3029);

assign acc_V_50_fu_2622_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_32_reg_3029 : acc_V_31_fu_2606_p3);

assign acc_V_51_fu_2678_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_33_fu_2664_p3 : acc_V_35_reg_3040);

assign acc_V_52_fu_2672_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_35_reg_3040 : acc_V_34_fu_2656_p3);

assign acc_V_53_fu_2728_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_36_fu_2714_p3 : acc_V_38_reg_3051);

assign acc_V_54_fu_2722_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_38_reg_3051 : acc_V_37_fu_2706_p3);

assign acc_V_fu_2414_p3 = ((icmp_ln1420_1_fu_2387_p2[0:0] == 1'b1) ? select_ln808_3_fu_2399_p3 : acc_V_278_reg_1244);

assign add_ln109_fu_1981_p2 = (ap_phi_mux_in_index84_phi_fu_1204_p6 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1) & (layer6_out_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1) & (layer5_out_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1) & (layer6_out_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1) & (layer5_out_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1) & (layer6_out_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1) & (layer5_out_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((ap_phi_mux_do_init_phi_fu_341_p6 == 1'd1) & (layer5_out_empty_n == 1'b0));
end

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter5 = ((icmp_ln124_reg_2778_pp0_iter4_reg == 1'd1) & (layer6_out_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_138 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_484 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = real_start;

assign ap_phi_reg_pp0_iter1_data_V_10_phi_reg_1032 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_11_phi_reg_1020 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_12_phi_reg_1008 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_13_phi_reg_996 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_14_phi_reg_984 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_15_phi_reg_972 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_16_phi_reg_960 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_17_phi_reg_948 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_18_phi_reg_936 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_19_phi_reg_924 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_1_phi_reg_1152 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_20_phi_reg_912 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_21_phi_reg_900 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_22_phi_reg_888 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_23_phi_reg_876 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_24_phi_reg_864 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_25_phi_reg_852 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_26_phi_reg_840 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_27_phi_reg_828 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_28_phi_reg_816 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_29_phi_reg_1044 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_2_phi_reg_1140 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_30_phi_reg_1164 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_31_phi_reg_1176 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_3_phi_reg_1128 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_4_phi_reg_1116 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_5_phi_reg_1104 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_6_phi_reg_1092 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_7_phi_reg_1080 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_8_phi_reg_1068 = 'bx;

assign ap_phi_reg_pp0_iter1_data_V_9_phi_reg_1056 = 'bx;

assign ap_phi_reg_pp0_iter1_p_phi_reg_1188 = 'bx;

assign ap_ready = internal_ap_ready;

assign data_V_fu_1466_p1 = layer5_out_dout[7:0];

assign icmp_ln124_fu_1460_p2 = ((ap_phi_mux_ir83_phi_fu_357_p6 == 6'd63) ? 1'b1 : 1'b0);

assign icmp_ln1420_1_fu_2387_p2 = ((sext_ln813_4_fu_2384_p1 == sub_ln1420_1_reg_2980) ? 1'b1 : 1'b0);

assign icmp_ln1420_2_fu_2437_p2 = ((sext_ln813_6_fu_2434_p1 == sub_ln1420_2_reg_2991) ? 1'b1 : 1'b0);

assign icmp_ln1420_3_fu_2487_p2 = ((sext_ln813_8_fu_2484_p1 == sub_ln1420_3_reg_3002) ? 1'b1 : 1'b0);

assign icmp_ln1420_4_fu_2537_p2 = ((sext_ln813_10_fu_2534_p1 == sub_ln1420_4_reg_3013) ? 1'b1 : 1'b0);

assign icmp_ln1420_5_fu_2587_p2 = ((sext_ln813_12_fu_2584_p1 == sub_ln1420_5_reg_3024) ? 1'b1 : 1'b0);

assign icmp_ln1420_6_fu_2637_p2 = ((sext_ln813_14_fu_2634_p1 == sub_ln1420_6_reg_3035) ? 1'b1 : 1'b0);

assign icmp_ln1420_7_fu_2687_p2 = ((sext_ln813_16_fu_2684_p1 == sub_ln1420_7_reg_3046) ? 1'b1 : 1'b0);

assign icmp_ln1420_fu_2337_p2 = ((sext_ln813_2_fu_2334_p1 == sub_ln1420_reg_2969) ? 1'b1 : 1'b0);

assign in_index_1_fu_1975_p2 = (zext_ln124_1_fu_1901_p1 + 6'd1);

assign in_index_fu_1995_p3 = ((tmp_3_fu_1987_p3[0:0] == 1'b1) ? 5'd0 : add_ln109_fu_1981_p2);

assign ir83_cast_fu_1812_p1 = ir83_reg_353;

assign ir_fu_1454_p2 = (ap_phi_mux_ir83_phi_fu_357_p6 + 6'd1);

assign layer6_out_din = {{{{{{{{{{{{{{{{acc_V_54_fu_2722_p3}, {acc_V_53_fu_2728_p3}}, {acc_V_52_fu_2672_p3}}, {acc_V_51_fu_2678_p3}}, {acc_V_50_fu_2622_p3}}, {acc_V_49_fu_2628_p3}}, {acc_V_48_fu_2572_p3}}, {acc_V_47_fu_2578_p3}}, {acc_V_46_fu_2522_p3}}, {acc_V_45_fu_2528_p3}}, {acc_V_44_fu_2472_p3}}, {acc_V_43_fu_2478_p3}}, {acc_V_42_fu_2422_p3}}, {acc_V_41_fu_2428_p3}}, {acc_V_40_fu_2372_p3}}, {acc_V_39_fu_2378_p3}};

assign lhs_1_fu_2180_p3 = ((out_index_reg_2827_pp0_iter3_reg[0:0] == 1'b1) ? ap_phi_mux_acc_V_376_phi_fu_1263_p6 : ap_phi_mux_acc_V_278_phi_fu_1248_p6);

assign lhs_2_fu_2202_p3 = ((out_index_reg_2827_pp0_iter3_reg[0:0] == 1'b1) ? ap_phi_mux_acc_V_572_phi_fu_1293_p6 : ap_phi_mux_acc_V_474_phi_fu_1278_p6);

assign lhs_3_fu_2224_p3 = ((out_index_reg_2827_pp0_iter3_reg[0:0] == 1'b1) ? ap_phi_mux_acc_V_768_phi_fu_1323_p6 : ap_phi_mux_acc_V_670_phi_fu_1308_p6);

assign lhs_4_fu_2246_p3 = ((out_index_reg_2827_pp0_iter3_reg[0:0] == 1'b1) ? ap_phi_mux_acc_V_964_phi_fu_1353_p6 : ap_phi_mux_acc_V_866_phi_fu_1338_p6);

assign lhs_5_fu_2268_p3 = ((out_index_reg_2827_pp0_iter3_reg[0:0] == 1'b1) ? ap_phi_mux_acc_V_1160_phi_fu_1383_p6 : ap_phi_mux_acc_V_1062_phi_fu_1368_p6);

assign lhs_6_fu_2290_p3 = ((out_index_reg_2827_pp0_iter3_reg[0:0] == 1'b1) ? ap_phi_mux_acc_V_1356_phi_fu_1413_p6 : ap_phi_mux_acc_V_1258_phi_fu_1398_p6);

assign lhs_7_fu_2312_p3 = ((out_index_reg_2827_pp0_iter3_reg[0:0] == 1'b1) ? ap_phi_mux_acc_V_1552_phi_fu_1443_p6 : ap_phi_mux_acc_V_1454_phi_fu_1428_p6);

assign lhs_fu_2158_p3 = ((out_index_reg_2827_pp0_iter3_reg[0:0] == 1'b1) ? ap_phi_mux_acc_V_180_phi_fu_1233_p6 : ap_phi_mux_acc_V82_phi_fu_1218_p6);

assign mul_ln1270_3_fu_2028_p1 = sext_ln1273_37_fu_2006_p1;

assign mul_ln1270_4_fu_2047_p1 = sext_ln1273_37_fu_2006_p1;

assign mul_ln1270_5_fu_2066_p1 = sext_ln1273_37_fu_2006_p1;

assign mul_ln1270_6_fu_2085_p1 = sext_ln1273_37_fu_2006_p1;

assign mul_ln1270_7_fu_2104_p1 = sext_ln1273_37_fu_2006_p1;

assign mul_ln1270_8_fu_2123_p1 = sext_ln1273_37_fu_2006_p1;

assign mul_ln1270_9_fu_2142_p1 = sext_ln1273_37_fu_2006_p1;

assign mul_ln1270_fu_2009_p1 = sext_ln1273_37_fu_2006_p1;

assign outidx_address0 = zext_ln124_fu_1816_p1;

assign p_cast239_fu_1830_p1 = $unsigned(tmp_fu_1822_p3);

assign p_cast240_cast_cast_fu_1843_p1 = $unsigned(p_cast240_cast_fu_1835_p3);

assign p_cast240_cast_fu_1835_p3 = {{1'd1}, {ir83_cast_fu_1812_p1}};

assign p_cast241_cast_cast_cast_cast_cast_fu_1852_p1 = $unsigned(p_cast241_cast_cast_cast_cast_fu_1848_p1);

assign p_cast241_cast_cast_cast_cast_fu_1848_p1 = tmp_fu_1822_p3;

assign p_cast242_cast_cast_fu_1865_p1 = p_cast242_cast_fu_1857_p3;

assign p_cast242_cast_fu_1857_p3 = {{2'd2}, {ir83_cast_fu_1812_p1}};

assign p_cast243_fu_1878_p1 = tmp_2_fu_1870_p3;

assign p_cast244_cast_cast_cast_cast_cast_fu_1887_p1 = $unsigned(p_cast244_cast_cast_cast_cast_fu_1883_p1);

assign p_cast244_cast_cast_cast_cast_fu_1883_p1 = p_cast240_cast_fu_1835_p3;

assign p_cast245_cast_cast_cast_cast_cast_fu_1896_p1 = $unsigned(p_cast245_cast_cast_cast_cast_fu_1892_p1);

assign p_cast245_cast_cast_cast_cast_fu_1892_p1 = tmp_fu_1822_p3;

assign select_ln808_10_fu_2592_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? 8'd0 : acc_V_1160_reg_1379);

assign select_ln808_11_fu_2599_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_1062_reg_1364 : 8'd0);

assign select_ln808_12_fu_2642_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? 8'd0 : acc_V_1356_reg_1409);

assign select_ln808_13_fu_2649_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_1258_reg_1394 : 8'd0);

assign select_ln808_14_fu_2692_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? 8'd0 : acc_V_1552_reg_1439);

assign select_ln808_15_fu_2699_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_1454_reg_1424 : 8'd0);

assign select_ln808_1_fu_2349_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V82_reg_1214 : 8'd0);

assign select_ln808_2_fu_2392_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? 8'd0 : acc_V_376_reg_1259);

assign select_ln808_3_fu_2399_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_278_reg_1244 : 8'd0);

assign select_ln808_4_fu_2442_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? 8'd0 : acc_V_572_reg_1289);

assign select_ln808_5_fu_2449_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_474_reg_1274 : 8'd0);

assign select_ln808_6_fu_2492_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? 8'd0 : acc_V_768_reg_1319);

assign select_ln808_7_fu_2499_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_670_reg_1304 : 8'd0);

assign select_ln808_8_fu_2542_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? 8'd0 : acc_V_964_reg_1349);

assign select_ln808_9_fu_2549_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? acc_V_866_reg_1334 : 8'd0);

assign select_ln808_fu_2342_p3 = ((out_index_reg_2827_pp0_iter4_reg[0:0] == 1'b1) ? 8'd0 : acc_V_180_reg_1229);

assign sext_ln1273_37_fu_2006_p1 = $signed(a_V_reg_2871);

assign sext_ln813_10_fu_2534_p1 = rhs_4_reg_2945_pp0_iter4_reg;

assign sext_ln813_11_fu_2275_p1 = lhs_5_fu_2268_p3;

assign sext_ln813_12_fu_2584_p1 = rhs_5_reg_2951_pp0_iter4_reg;

assign sext_ln813_13_fu_2297_p1 = lhs_6_fu_2290_p3;

assign sext_ln813_14_fu_2634_p1 = rhs_6_reg_2957_pp0_iter4_reg;

assign sext_ln813_15_fu_2319_p1 = lhs_7_fu_2312_p3;

assign sext_ln813_16_fu_2684_p1 = rhs_7_reg_2963_pp0_iter4_reg;

assign sext_ln813_2_fu_2334_p1 = rhs_reg_2921_pp0_iter4_reg;

assign sext_ln813_3_fu_2187_p1 = lhs_1_fu_2180_p3;

assign sext_ln813_4_fu_2384_p1 = rhs_1_reg_2927_pp0_iter4_reg;

assign sext_ln813_5_fu_2209_p1 = lhs_2_fu_2202_p3;

assign sext_ln813_6_fu_2434_p1 = rhs_2_reg_2933_pp0_iter4_reg;

assign sext_ln813_7_fu_2231_p1 = lhs_3_fu_2224_p3;

assign sext_ln813_8_fu_2484_p1 = rhs_3_reg_2939_pp0_iter4_reg;

assign sext_ln813_9_fu_2253_p1 = lhs_4_fu_2246_p3;

assign sext_ln813_fu_2165_p1 = lhs_fu_2158_p3;

assign start_out = real_start;

assign sub_ln1420_1_fu_2191_p2 = ($signed(9'd0) - $signed(sext_ln813_3_fu_2187_p1));

assign sub_ln1420_2_fu_2213_p2 = ($signed(9'd0) - $signed(sext_ln813_5_fu_2209_p1));

assign sub_ln1420_3_fu_2235_p2 = ($signed(9'd0) - $signed(sext_ln813_7_fu_2231_p1));

assign sub_ln1420_4_fu_2257_p2 = ($signed(9'd0) - $signed(sext_ln813_9_fu_2253_p1));

assign sub_ln1420_5_fu_2279_p2 = ($signed(9'd0) - $signed(sext_ln813_11_fu_2275_p1));

assign sub_ln1420_6_fu_2301_p2 = ($signed(9'd0) - $signed(sext_ln813_13_fu_2297_p1));

assign sub_ln1420_7_fu_2323_p2 = ($signed(9'd0) - $signed(sext_ln813_15_fu_2319_p1));

assign sub_ln1420_fu_2169_p2 = ($signed(9'd0) - $signed(sext_ln813_fu_2165_p1));

assign tmp_2_fu_1870_p3 = {{3'd5}, {ir83_reg_353}};

assign tmp_3_fu_1987_p3 = in_index_1_fu_1975_p2[32'd5];

assign tmp_fu_1822_p3 = {{1'd1}, {ir83_reg_353}};

assign w6_V_address0 = p_cast245_cast_cast_cast_cast_cast_fu_1896_p1;

assign w6_V_address1 = p_cast244_cast_cast_cast_cast_cast_fu_1887_p1;

assign w6_V_address2 = p_cast243_fu_1878_p1;

assign w6_V_address3 = p_cast242_cast_cast_fu_1865_p1;

assign w6_V_address4 = p_cast241_cast_cast_cast_cast_cast_fu_1852_p1;

assign w6_V_address5 = p_cast240_cast_cast_fu_1843_p1;

assign w6_V_address6 = p_cast239_fu_1830_p1;

assign w6_V_address7 = zext_ln124_fu_1816_p1;

assign zext_ln124_1_fu_1901_p1 = ap_phi_mux_in_index84_phi_fu_1204_p6;

assign zext_ln124_fu_1816_p1 = ir83_reg_353;

endmodule //inference_dense_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_16u_config6_s
