-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity inference is
port (
    input_r_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    input_r_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    input_r_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    input_r_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
    input_r_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    input_r_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    input_r_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
    result : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    input_r_TVALID : IN STD_LOGIC;
    input_r_TREADY : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    result_ap_vld : OUT STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of inference is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "inference_inference,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.898350,HLS_SYN_LAT=113,HLS_SYN_TPT=72,HLS_SYN_MEM=9,HLS_SYN_DSP=0,HLS_SYN_FF=6243,HLS_SYN_LUT=10525,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal Loop_VITIS_LOOP_86_1_proc1_U0_ap_start : STD_LOGIC;
    signal Loop_VITIS_LOOP_86_1_proc1_U0_ap_done : STD_LOGIC;
    signal Loop_VITIS_LOOP_86_1_proc1_U0_ap_continue : STD_LOGIC;
    signal Loop_VITIS_LOOP_86_1_proc1_U0_ap_idle : STD_LOGIC;
    signal Loop_VITIS_LOOP_86_1_proc1_U0_ap_ready : STD_LOGIC;
    signal Loop_VITIS_LOOP_86_1_proc1_U0_features_in_data_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal Loop_VITIS_LOOP_86_1_proc1_U0_features_in_data_V_write : STD_LOGIC;
    signal Loop_VITIS_LOOP_86_1_proc1_U0_start_out : STD_LOGIC;
    signal Loop_VITIS_LOOP_86_1_proc1_U0_start_write : STD_LOGIC;
    signal Loop_VITIS_LOOP_86_1_proc1_U0_input_r_TREADY : STD_LOGIC;
    signal Block_inference_for_cond_i_exit_proc2_U0_ap_start : STD_LOGIC;
    signal Block_inference_for_cond_i_exit_proc2_U0_ap_done : STD_LOGIC;
    signal Block_inference_for_cond_i_exit_proc2_U0_ap_continue : STD_LOGIC;
    signal Block_inference_for_cond_i_exit_proc2_U0_ap_idle : STD_LOGIC;
    signal Block_inference_for_cond_i_exit_proc2_U0_ap_ready : STD_LOGIC;
    signal Block_inference_for_cond_i_exit_proc2_U0_start_out : STD_LOGIC;
    signal Block_inference_for_cond_i_exit_proc2_U0_start_write : STD_LOGIC;
    signal Block_inference_for_cond_i_exit_proc2_U0_features_in_data_V_read : STD_LOGIC;
    signal Block_inference_for_cond_i_exit_proc2_U0_internal_input_din : STD_LOGIC_VECTOR (143 downto 0);
    signal Block_inference_for_cond_i_exit_proc2_U0_internal_input_write : STD_LOGIC;
    signal myproject_U0_ap_start : STD_LOGIC;
    signal myproject_U0_start_out : STD_LOGIC;
    signal myproject_U0_start_write : STD_LOGIC;
    signal myproject_U0_internal_input_read : STD_LOGIC;
    signal myproject_U0_internal_output_din : STD_LOGIC_VECTOR (7 downto 0);
    signal myproject_U0_internal_output_write : STD_LOGIC;
    signal myproject_U0_ap_done : STD_LOGIC;
    signal myproject_U0_ap_ready : STD_LOGIC;
    signal myproject_U0_ap_idle : STD_LOGIC;
    signal myproject_U0_ap_continue : STD_LOGIC;
    signal Block_inference_for_cond_i_exit13_proc3_U0_ap_start : STD_LOGIC;
    signal Block_inference_for_cond_i_exit13_proc3_U0_ap_done : STD_LOGIC;
    signal Block_inference_for_cond_i_exit13_proc3_U0_ap_continue : STD_LOGIC;
    signal Block_inference_for_cond_i_exit13_proc3_U0_ap_idle : STD_LOGIC;
    signal Block_inference_for_cond_i_exit13_proc3_U0_ap_ready : STD_LOGIC;
    signal Block_inference_for_cond_i_exit13_proc3_U0_internal_output_read : STD_LOGIC;
    signal Block_inference_for_cond_i_exit13_proc3_U0_result : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_inference_for_cond_i_exit13_proc3_U0_result_ap_vld : STD_LOGIC;
    signal features_in_data_V_full_n : STD_LOGIC;
    signal features_in_data_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal features_in_data_V_num_data_valid : STD_LOGIC_VECTOR (5 downto 0);
    signal features_in_data_V_fifo_cap : STD_LOGIC_VECTOR (5 downto 0);
    signal features_in_data_V_empty_n : STD_LOGIC;
    signal internal_input_full_n : STD_LOGIC;
    signal internal_input_dout : STD_LOGIC_VECTOR (143 downto 0);
    signal internal_input_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal internal_input_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal internal_input_empty_n : STD_LOGIC;
    signal internal_output_full_n : STD_LOGIC;
    signal internal_output_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal internal_output_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal internal_output_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal internal_output_empty_n : STD_LOGIC;
    signal start_for_Block_inference_for_cond_i_exit_proc2_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Block_inference_for_cond_i_exit_proc2_U0_full_n : STD_LOGIC;
    signal start_for_Block_inference_for_cond_i_exit_proc2_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Block_inference_for_cond_i_exit_proc2_U0_empty_n : STD_LOGIC;
    signal start_for_myproject_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_myproject_U0_full_n : STD_LOGIC;
    signal start_for_myproject_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_myproject_U0_empty_n : STD_LOGIC;
    signal start_for_Block_inference_for_cond_i_exit13_proc3_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Block_inference_for_cond_i_exit13_proc3_U0_full_n : STD_LOGIC;
    signal start_for_Block_inference_for_cond_i_exit13_proc3_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Block_inference_for_cond_i_exit13_proc3_U0_empty_n : STD_LOGIC;

    component inference_Loop_VITIS_LOOP_86_1_proc1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_r_TVALID : IN STD_LOGIC;
        features_in_data_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        features_in_data_V_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
        features_in_data_V_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0);
        features_in_data_V_full_n : IN STD_LOGIC;
        features_in_data_V_write : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        input_r_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        input_r_TREADY : OUT STD_LOGIC;
        input_r_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        input_r_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        input_r_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
        input_r_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        input_r_TID : IN STD_LOGIC_VECTOR (4 downto 0);
        input_r_TDEST : IN STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component inference_Block_inference_for_cond_i_exit_proc2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        features_in_data_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        features_in_data_V_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
        features_in_data_V_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0);
        features_in_data_V_empty_n : IN STD_LOGIC;
        features_in_data_V_read : OUT STD_LOGIC;
        internal_input_din : OUT STD_LOGIC_VECTOR (143 downto 0);
        internal_input_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        internal_input_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        internal_input_full_n : IN STD_LOGIC;
        internal_input_write : OUT STD_LOGIC );
    end component;


    component inference_myproject IS
    port (
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        internal_input_dout : IN STD_LOGIC_VECTOR (143 downto 0);
        internal_input_empty_n : IN STD_LOGIC;
        internal_input_read : OUT STD_LOGIC;
        internal_output_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        internal_output_full_n : IN STD_LOGIC;
        internal_output_write : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component inference_Block_inference_for_cond_i_exit13_proc3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        internal_output_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        internal_output_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        internal_output_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        internal_output_empty_n : IN STD_LOGIC;
        internal_output_read : OUT STD_LOGIC;
        result : OUT STD_LOGIC_VECTOR (31 downto 0);
        result_ap_vld : OUT STD_LOGIC );
    end component;


    component inference_fifo_w8_d18_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (5 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (5 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component inference_fifo_w144_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (143 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (143 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component inference_fifo_w8_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component inference_start_for_Block_inference_for_cond_i_exit_proc2_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component inference_start_for_myproject_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component inference_start_for_Block_inference_for_cond_i_exit13_proc3_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    Loop_VITIS_LOOP_86_1_proc1_U0 : component inference_Loop_VITIS_LOOP_86_1_proc1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Loop_VITIS_LOOP_86_1_proc1_U0_ap_start,
        start_full_n => start_for_Block_inference_for_cond_i_exit_proc2_U0_full_n,
        ap_done => Loop_VITIS_LOOP_86_1_proc1_U0_ap_done,
        ap_continue => Loop_VITIS_LOOP_86_1_proc1_U0_ap_continue,
        ap_idle => Loop_VITIS_LOOP_86_1_proc1_U0_ap_idle,
        ap_ready => Loop_VITIS_LOOP_86_1_proc1_U0_ap_ready,
        input_r_TVALID => input_r_TVALID,
        features_in_data_V_din => Loop_VITIS_LOOP_86_1_proc1_U0_features_in_data_V_din,
        features_in_data_V_num_data_valid => features_in_data_V_num_data_valid,
        features_in_data_V_fifo_cap => features_in_data_V_fifo_cap,
        features_in_data_V_full_n => features_in_data_V_full_n,
        features_in_data_V_write => Loop_VITIS_LOOP_86_1_proc1_U0_features_in_data_V_write,
        start_out => Loop_VITIS_LOOP_86_1_proc1_U0_start_out,
        start_write => Loop_VITIS_LOOP_86_1_proc1_U0_start_write,
        input_r_TDATA => input_r_TDATA,
        input_r_TREADY => Loop_VITIS_LOOP_86_1_proc1_U0_input_r_TREADY,
        input_r_TKEEP => input_r_TKEEP,
        input_r_TSTRB => input_r_TSTRB,
        input_r_TUSER => input_r_TUSER,
        input_r_TLAST => input_r_TLAST,
        input_r_TID => input_r_TID,
        input_r_TDEST => input_r_TDEST);

    Block_inference_for_cond_i_exit_proc2_U0 : component inference_Block_inference_for_cond_i_exit_proc2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Block_inference_for_cond_i_exit_proc2_U0_ap_start,
        start_full_n => start_for_myproject_U0_full_n,
        ap_done => Block_inference_for_cond_i_exit_proc2_U0_ap_done,
        ap_continue => Block_inference_for_cond_i_exit_proc2_U0_ap_continue,
        ap_idle => Block_inference_for_cond_i_exit_proc2_U0_ap_idle,
        ap_ready => Block_inference_for_cond_i_exit_proc2_U0_ap_ready,
        start_out => Block_inference_for_cond_i_exit_proc2_U0_start_out,
        start_write => Block_inference_for_cond_i_exit_proc2_U0_start_write,
        features_in_data_V_dout => features_in_data_V_dout,
        features_in_data_V_num_data_valid => features_in_data_V_num_data_valid,
        features_in_data_V_fifo_cap => features_in_data_V_fifo_cap,
        features_in_data_V_empty_n => features_in_data_V_empty_n,
        features_in_data_V_read => Block_inference_for_cond_i_exit_proc2_U0_features_in_data_V_read,
        internal_input_din => Block_inference_for_cond_i_exit_proc2_U0_internal_input_din,
        internal_input_num_data_valid => internal_input_num_data_valid,
        internal_input_fifo_cap => internal_input_fifo_cap,
        internal_input_full_n => internal_input_full_n,
        internal_input_write => Block_inference_for_cond_i_exit_proc2_U0_internal_input_write);

    myproject_U0 : component inference_myproject
    port map (
        ap_start => myproject_U0_ap_start,
        start_full_n => start_for_Block_inference_for_cond_i_exit13_proc3_U0_full_n,
        start_out => myproject_U0_start_out,
        start_write => myproject_U0_start_write,
        internal_input_dout => internal_input_dout,
        internal_input_empty_n => internal_input_empty_n,
        internal_input_read => myproject_U0_internal_input_read,
        internal_output_din => myproject_U0_internal_output_din,
        internal_output_full_n => internal_output_full_n,
        internal_output_write => myproject_U0_internal_output_write,
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_done => myproject_U0_ap_done,
        ap_ready => myproject_U0_ap_ready,
        ap_idle => myproject_U0_ap_idle,
        ap_continue => myproject_U0_ap_continue);

    Block_inference_for_cond_i_exit13_proc3_U0 : component inference_Block_inference_for_cond_i_exit13_proc3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Block_inference_for_cond_i_exit13_proc3_U0_ap_start,
        ap_done => Block_inference_for_cond_i_exit13_proc3_U0_ap_done,
        ap_continue => Block_inference_for_cond_i_exit13_proc3_U0_ap_continue,
        ap_idle => Block_inference_for_cond_i_exit13_proc3_U0_ap_idle,
        ap_ready => Block_inference_for_cond_i_exit13_proc3_U0_ap_ready,
        internal_output_dout => internal_output_dout,
        internal_output_num_data_valid => internal_output_num_data_valid,
        internal_output_fifo_cap => internal_output_fifo_cap,
        internal_output_empty_n => internal_output_empty_n,
        internal_output_read => Block_inference_for_cond_i_exit13_proc3_U0_internal_output_read,
        result => Block_inference_for_cond_i_exit13_proc3_U0_result,
        result_ap_vld => Block_inference_for_cond_i_exit13_proc3_U0_result_ap_vld);

    features_in_data_V_U : component inference_fifo_w8_d18_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_86_1_proc1_U0_features_in_data_V_din,
        if_full_n => features_in_data_V_full_n,
        if_write => Loop_VITIS_LOOP_86_1_proc1_U0_features_in_data_V_write,
        if_dout => features_in_data_V_dout,
        if_num_data_valid => features_in_data_V_num_data_valid,
        if_fifo_cap => features_in_data_V_fifo_cap,
        if_empty_n => features_in_data_V_empty_n,
        if_read => Block_inference_for_cond_i_exit_proc2_U0_features_in_data_V_read);

    internal_input_U : component inference_fifo_w144_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_inference_for_cond_i_exit_proc2_U0_internal_input_din,
        if_full_n => internal_input_full_n,
        if_write => Block_inference_for_cond_i_exit_proc2_U0_internal_input_write,
        if_dout => internal_input_dout,
        if_num_data_valid => internal_input_num_data_valid,
        if_fifo_cap => internal_input_fifo_cap,
        if_empty_n => internal_input_empty_n,
        if_read => myproject_U0_internal_input_read);

    internal_output_U : component inference_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => myproject_U0_internal_output_din,
        if_full_n => internal_output_full_n,
        if_write => myproject_U0_internal_output_write,
        if_dout => internal_output_dout,
        if_num_data_valid => internal_output_num_data_valid,
        if_fifo_cap => internal_output_fifo_cap,
        if_empty_n => internal_output_empty_n,
        if_read => Block_inference_for_cond_i_exit13_proc3_U0_internal_output_read);

    start_for_Block_inference_for_cond_i_exit_proc2_U0_U : component inference_start_for_Block_inference_for_cond_i_exit_proc2_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_Block_inference_for_cond_i_exit_proc2_U0_din,
        if_full_n => start_for_Block_inference_for_cond_i_exit_proc2_U0_full_n,
        if_write => Loop_VITIS_LOOP_86_1_proc1_U0_start_write,
        if_dout => start_for_Block_inference_for_cond_i_exit_proc2_U0_dout,
        if_empty_n => start_for_Block_inference_for_cond_i_exit_proc2_U0_empty_n,
        if_read => Block_inference_for_cond_i_exit_proc2_U0_ap_ready);

    start_for_myproject_U0_U : component inference_start_for_myproject_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_myproject_U0_din,
        if_full_n => start_for_myproject_U0_full_n,
        if_write => Block_inference_for_cond_i_exit_proc2_U0_start_write,
        if_dout => start_for_myproject_U0_dout,
        if_empty_n => start_for_myproject_U0_empty_n,
        if_read => myproject_U0_ap_ready);

    start_for_Block_inference_for_cond_i_exit13_proc3_U0_U : component inference_start_for_Block_inference_for_cond_i_exit13_proc3_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_Block_inference_for_cond_i_exit13_proc3_U0_din,
        if_full_n => start_for_Block_inference_for_cond_i_exit13_proc3_U0_full_n,
        if_write => myproject_U0_start_write,
        if_dout => start_for_Block_inference_for_cond_i_exit13_proc3_U0_dout,
        if_empty_n => start_for_Block_inference_for_cond_i_exit13_proc3_U0_empty_n,
        if_read => Block_inference_for_cond_i_exit13_proc3_U0_ap_ready);




    Block_inference_for_cond_i_exit13_proc3_U0_ap_continue <= ap_const_logic_1;
    Block_inference_for_cond_i_exit13_proc3_U0_ap_start <= start_for_Block_inference_for_cond_i_exit13_proc3_U0_empty_n;
    Block_inference_for_cond_i_exit_proc2_U0_ap_continue <= ap_const_logic_1;
    Block_inference_for_cond_i_exit_proc2_U0_ap_start <= start_for_Block_inference_for_cond_i_exit_proc2_U0_empty_n;
    Loop_VITIS_LOOP_86_1_proc1_U0_ap_continue <= ap_const_logic_1;
    Loop_VITIS_LOOP_86_1_proc1_U0_ap_start <= ap_start;
    ap_done <= Block_inference_for_cond_i_exit13_proc3_U0_ap_done;
    ap_idle <= (myproject_U0_ap_idle and Loop_VITIS_LOOP_86_1_proc1_U0_ap_idle and Block_inference_for_cond_i_exit_proc2_U0_ap_idle and Block_inference_for_cond_i_exit13_proc3_U0_ap_idle);
    ap_ready <= Loop_VITIS_LOOP_86_1_proc1_U0_ap_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    input_r_TREADY <= Loop_VITIS_LOOP_86_1_proc1_U0_input_r_TREADY;
    myproject_U0_ap_continue <= ap_const_logic_1;
    myproject_U0_ap_start <= start_for_myproject_U0_empty_n;
    result <= Block_inference_for_cond_i_exit13_proc3_U0_result;
    result_ap_vld <= Block_inference_for_cond_i_exit13_proc3_U0_result_ap_vld;
    start_for_Block_inference_for_cond_i_exit13_proc3_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_Block_inference_for_cond_i_exit_proc2_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_myproject_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
