-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity inference_normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer2_out_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    layer2_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer2_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer2_out_empty_n : IN STD_LOGIC;
    layer2_out_read : OUT STD_LOGIC;
    layer4_out_din : OUT STD_LOGIC_VECTOR (255 downto 0);
    layer4_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer4_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer4_out_full_n : IN STD_LOGIC;
    layer4_out_write : OUT STD_LOGIC );
end;


architecture behav of inference_normalize_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_config4_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (12 downto 0) := "0000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (12 downto 0) := "0000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (12 downto 0) := "0000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (12 downto 0) := "0000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (12 downto 0) := "0000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (12 downto 0) := "0000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (12 downto 0) := "0001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (12 downto 0) := "0010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (12 downto 0) := "0100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv13_D : STD_LOGIC_VECTOR (12 downto 0) := "0000000001101";
    constant ap_const_lv14_1A : STD_LOGIC_VECTOR (13 downto 0) := "00000000011010";
    constant ap_const_lv13_17 : STD_LOGIC_VECTOR (12 downto 0) := "0000000010111";
    constant ap_const_lv12_D : STD_LOGIC_VECTOR (11 downto 0) := "000000001101";
    constant ap_const_lv13_1B : STD_LOGIC_VECTOR (12 downto 0) := "0000000011011";
    constant ap_const_lv14_27 : STD_LOGIC_VECTOR (13 downto 0) := "00000000100111";
    constant ap_const_lv14_29 : STD_LOGIC_VECTOR (13 downto 0) := "00000000101001";
    constant ap_const_lv14_36 : STD_LOGIC_VECTOR (13 downto 0) := "00000000110110";
    constant ap_const_lv32_F8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_57 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_87 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000111";
    constant ap_const_lv32_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010000";
    constant ap_const_lv32_97 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010111";
    constant ap_const_lv32_98 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110000";
    constant ap_const_lv32_B7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110111";
    constant ap_const_lv32_B8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_C7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000111";
    constant ap_const_lv32_D8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv11_780 : STD_LOGIC_VECTOR (10 downto 0) := "11110000000";
    constant ap_const_lv32_88 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001000";
    constant ap_const_lv32_8F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_A7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100111";
    constant ap_const_lv32_A8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101000";
    constant ap_const_lv32_AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101111";
    constant ap_const_lv32_C8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001000";
    constant ap_const_lv32_CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001111";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_D7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010111";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_E7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100111";
    constant ap_const_lv32_E8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101000";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv13_1DC0 : STD_LOGIC_VECTOR (12 downto 0) := "1110111000000";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_F7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv12_E80 : STD_LOGIC_VECTOR (11 downto 0) := "111010000000";
    constant ap_const_lv13_1C40 : STD_LOGIC_VECTOR (12 downto 0) := "1110001000000";
    constant ap_const_lv12_E40 : STD_LOGIC_VECTOR (11 downto 0) := "111001000000";
    constant ap_const_lv13_140 : STD_LOGIC_VECTOR (12 downto 0) := "0000101000000";
    constant ap_const_lv10_300 : STD_LOGIC_VECTOR (9 downto 0) := "1100000000";
    constant ap_const_lv9_140 : STD_LOGIC_VECTOR (8 downto 0) := "101000000";
    constant ap_const_lv13_100 : STD_LOGIC_VECTOR (12 downto 0) := "0000100000000";
    constant ap_const_lv11_540 : STD_LOGIC_VECTOR (10 downto 0) := "10101000000";
    constant ap_const_lv13_1D80 : STD_LOGIC_VECTOR (12 downto 0) := "1110110000000";
    constant ap_const_lv13_1A00 : STD_LOGIC_VECTOR (12 downto 0) := "1101000000000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv12_80 : STD_LOGIC_VECTOR (11 downto 0) := "000010000000";
    constant ap_const_lv13_1E80 : STD_LOGIC_VECTOR (12 downto 0) := "1111010000000";
    constant ap_const_lv13_1BC0 : STD_LOGIC_VECTOR (12 downto 0) := "1101111000000";
    constant ap_const_lv14_80 : STD_LOGIC_VECTOR (13 downto 0) := "00000010000000";
    constant ap_const_lv14_3480 : STD_LOGIC_VECTOR (13 downto 0) := "11010010000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv14_3BC0 : STD_LOGIC_VECTOR (13 downto 0) := "11101111000000";
    constant ap_const_lv14_3380 : STD_LOGIC_VECTOR (13 downto 0) := "11001110000000";
    constant ap_const_lv14_3040 : STD_LOGIC_VECTOR (13 downto 0) := "11000001000000";
    constant ap_const_lv14_3580 : STD_LOGIC_VECTOR (13 downto 0) := "11010110000000";
    constant ap_const_lv14_3B80 : STD_LOGIC_VECTOR (13 downto 0) := "11101110000000";
    constant ap_const_lv14_3940 : STD_LOGIC_VECTOR (13 downto 0) := "11100101000000";
    constant ap_const_lv14_3AC0 : STD_LOGIC_VECTOR (13 downto 0) := "11101011000000";
    constant ap_const_lv14_100 : STD_LOGIC_VECTOR (13 downto 0) := "00000100000000";
    constant ap_const_lv13_1C80 : STD_LOGIC_VECTOR (12 downto 0) := "1110010000000";
    constant ap_const_lv14_3640 : STD_LOGIC_VECTOR (13 downto 0) := "11011001000000";
    constant ap_const_lv14_3180 : STD_LOGIC_VECTOR (13 downto 0) := "11000110000000";
    constant ap_const_lv14_3C40 : STD_LOGIC_VECTOR (13 downto 0) := "11110001000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer2_out_blk_n : STD_LOGIC;
    signal layer4_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal grp_fu_317_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal reg_326 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal reg_332 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal a_V_fu_354_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_V_reg_1991 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_V_13_reg_1996 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_V_1_reg_2001 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_V_2_reg_2006 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_V_3_reg_2011 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_V_4_reg_2016 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_V_5_reg_2022 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_V_6_reg_2027 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_V_7_reg_2032 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_V_8_reg_2038 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_V_9_reg_2043 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_V_10_reg_2049 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_V_11_reg_2054 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_V_12_reg_2059 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_reg_2064 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_reg_2070 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_reg_2076 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_reg_2082 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_8_reg_2088 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_10_reg_2094 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_13_reg_2100 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_15_reg_2106 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_17_reg_2112 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_8_reg_2118 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_20_reg_2123 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_23_reg_2129 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_25_reg_2135 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_26_reg_2141 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_27_reg_2147 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_28_reg_2153 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_16_reg_2159 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_30_reg_2164 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_3_reg_2170 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln818_5_reg_2175 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln818_6_reg_2180 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln818_s_reg_2185 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln818_10_reg_2190 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln818_11_reg_2195 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln818_12_reg_2200 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln818_14_reg_2205 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_1_reg_2210 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_2215 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln_reg_2220 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal trunc_ln818_1_reg_2225 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_2_reg_2230 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln818_4_reg_2235 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln818_7_reg_2240 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln818_9_reg_2245 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln46_7_reg_2250 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln46_9_reg_2255 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_13_reg_2260 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln818_15_reg_2265 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln46_2_reg_2270 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln46_3_reg_2275 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln46_4_reg_2280 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln46_5_reg_2285 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln46_6_reg_2290 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln46_8_reg_2295 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln46_s_reg_2300 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln46_1_reg_2305 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln46_10_reg_2310 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_31_reg_2315 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal grp_fu_317_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln1270_fu_724_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln1270_1_fu_1144_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln1270_2_fu_1158_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln1347_fu_1178_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln1270_4_fu_1198_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln1270_6_fu_1218_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln1347_3_fu_1238_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln1347_5_fu_1248_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln1270_9_fu_1268_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln1270_10_fu_1298_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln1347_6_fu_1658_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_317_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_19_fu_578_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_17_fu_588_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1270_5_fu_596_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln1347_fu_600_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_29_fu_676_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_32_fu_686_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln1270_11_fu_694_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln1347_14_fu_698_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln1273_2_fu_728_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1273_3_fu_739_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1273_2_fu_735_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln1273_3_fu_746_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal r_V_5_fu_750_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln1273_4_fu_762_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln1273_5_fu_773_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1273_4_fu_769_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln1273_5_fu_780_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_7_fu_784_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ret_V_4_fu_790_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln1273_6_fu_806_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1273_7_fu_817_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1273_6_fu_813_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln1273_7_fu_824_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal r_V_9_fu_828_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ret_V_6_fu_834_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln1273_16_fu_850_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln1273_17_fu_861_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1273_17_fu_857_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln1273_18_fu_868_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_15_fu_872_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ret_V_12_fu_878_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln1273_18_fu_894_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1273_19_fu_905_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1347_1_fu_912_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln1347_18_fu_916_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1347_2_fu_922_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln1273_19_fu_901_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ret_V_15_fu_926_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln1273_20_fu_945_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1270_7_fu_942_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln1347_20_fu_956_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln1347_fu_962_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln1273_20_fu_952_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ret_V_16_fu_966_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln1273_21_fu_982_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln1273_22_fu_993_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1273_21_fu_989_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln1273_22_fu_1000_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_22_fu_1004_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ret_V_18_fu_1010_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln1273_25_fu_1029_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln1270_8_fu_1026_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln1347_25_fu_1040_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1347_4_fu_1046_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln1273_25_fu_1036_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal ret_V_20_fu_1050_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln1273_26_fu_1066_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln1273_27_fu_1077_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1273_26_fu_1073_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln1273_27_fu_1084_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_28_fu_1088_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ret_V_23_fu_1094_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ret_V_2_fu_756_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ret_V_fu_1128_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ret_V_3_fu_1162_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ret_V_5_fu_1182_p0 : STD_LOGIC_VECTOR (11 downto 0);
    signal ret_V_5_fu_1182_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ret_V_13_fu_1202_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ret_V_14_fu_1222_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ret_V_17_fu_1242_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_V_21_fu_1262_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_V_22_fu_1282_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln_fu_1302_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln1273_1_fu_1313_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1273_fu_1309_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln1273_1_fu_1320_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal r_V_2_fu_1324_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln1273_8_fu_1336_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1273_9_fu_1347_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1273_8_fu_1343_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln1273_9_fu_1354_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal r_V_10_fu_1358_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln813_fu_1364_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln1273_s_fu_1374_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1273_10_fu_1385_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1273_10_fu_1381_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln1273_11_fu_1392_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal r_V_11_fu_1396_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln813_1_fu_1402_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln1273_11_fu_1415_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln1273_12_fu_1422_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln1270_3_fu_1412_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln1347_10_fu_1426_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln1273_12_fu_1438_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln1273_13_fu_1449_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_13_fu_1445_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln1273_14_fu_1456_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal r_V_13_fu_1460_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln1273_14_fu_1472_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln1273_15_fu_1483_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_15_fu_1479_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln1273_16_fu_1490_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal r_V_14_fu_1494_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln1273_23_fu_1506_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln1273_24_fu_1517_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1273_23_fu_1513_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln1273_24_fu_1524_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal r_V_23_fu_1528_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln1273_28_fu_1540_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln1273_29_fu_1551_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_28_fu_1547_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln1273_29_fu_1558_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal r_V_29_fu_1562_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_V_25_fu_1574_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln1273_30_fu_1590_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln1273_31_fu_1601_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1273_30_fu_1597_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln1273_31_fu_1608_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal r_V_31_fu_1612_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln1273_32_fu_1624_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln1273_33_fu_1635_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1273_32_fu_1631_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln1273_33_fu_1642_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal r_V_33_fu_1646_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_V_7_fu_1368_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_V_8_fu_1406_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_V_9_fu_1432_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_V_10_fu_1466_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_V_11_fu_1500_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_V_19_fu_1534_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_V_24_fu_1568_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_V_26_fu_1618_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_V_27_fu_1652_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_V_1_fu_1330_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_V_28_fu_1765_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_32_fu_1781_p5 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln46_fu_1789_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_33_fu_1793_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln46_1_fu_1800_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_34_fu_1804_p3 : STD_LOGIC_VECTOR (38 downto 0);
    signal sext_ln46_2_fu_1811_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_35_fu_1815_p3 : STD_LOGIC_VECTOR (45 downto 0);
    signal sext_ln46_3_fu_1822_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_36_fu_1826_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal sext_ln46_4_fu_1833_p1 : STD_LOGIC_VECTOR (55 downto 0);
    signal tmp_37_fu_1837_p8 : STD_LOGIC_VECTOR (102 downto 0);
    signal sext_ln46_5_fu_1849_p1 : STD_LOGIC_VECTOR (103 downto 0);
    signal tmp_38_fu_1853_p3 : STD_LOGIC_VECTOR (110 downto 0);
    signal sext_ln46_6_fu_1860_p1 : STD_LOGIC_VECTOR (111 downto 0);
    signal tmp_39_fu_1864_p3 : STD_LOGIC_VECTOR (116 downto 0);
    signal sext_ln46_7_fu_1871_p1 : STD_LOGIC_VECTOR (119 downto 0);
    signal tmp_40_fu_1875_p3 : STD_LOGIC_VECTOR (126 downto 0);
    signal sext_ln46_8_fu_1882_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_41_fu_1886_p3 : STD_LOGIC_VECTOR (133 downto 0);
    signal sext_ln46_9_fu_1893_p1 : STD_LOGIC_VECTOR (135 downto 0);
    signal tmp_42_fu_1897_p3 : STD_LOGIC_VECTOR (141 downto 0);
    signal sext_ln46_10_fu_1904_p1 : STD_LOGIC_VECTOR (143 downto 0);
    signal tmp_43_fu_1908_p4 : STD_LOGIC_VECTOR (158 downto 0);
    signal sext_ln46_11_fu_1916_p1 : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_44_fu_1920_p4 : STD_LOGIC_VECTOR (174 downto 0);
    signal sext_ln46_12_fu_1928_p1 : STD_LOGIC_VECTOR (175 downto 0);
    signal tmp_45_fu_1932_p4 : STD_LOGIC_VECTOR (190 downto 0);
    signal sext_ln46_13_fu_1940_p1 : STD_LOGIC_VECTOR (191 downto 0);
    signal tmp_46_fu_1944_p3 : STD_LOGIC_VECTOR (198 downto 0);
    signal sext_ln46_14_fu_1951_p1 : STD_LOGIC_VECTOR (199 downto 0);
    signal tmp_47_fu_1955_p4 : STD_LOGIC_VECTOR (214 downto 0);
    signal sext_ln46_15_fu_1963_p1 : STD_LOGIC_VECTOR (215 downto 0);
    signal tmp_48_fu_1967_p4 : STD_LOGIC_VECTOR (230 downto 0);
    signal trunc_ln46_11_fu_1771_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln46_16_fu_1975_p1 : STD_LOGIC_VECTOR (231 downto 0);
    signal sext_ln818_fu_1762_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component inference_mul_8s_7ns_14_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (13 downto 0) );
    end component;



begin
    mul_8s_7ns_14_1_1_U46 : component inference_mul_8s_7ns_14_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        dout_WIDTH => 14)
    port map (
        din0 => grp_fu_317_p0,
        din1 => grp_fu_317_p1,
        dout => grp_fu_317_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((layer4_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                a_V_10_reg_2049 <= layer2_out_dout(191 downto 184);
                a_V_11_reg_2054 <= layer2_out_dout(199 downto 192);
                a_V_12_reg_2059 <= layer2_out_dout(223 downto 216);
                a_V_13_reg_1996 <= layer2_out_dout(255 downto 248);
                a_V_1_reg_2001 <= layer2_out_dout(23 downto 16);
                a_V_2_reg_2006 <= layer2_out_dout(39 downto 32);
                a_V_3_reg_2011 <= layer2_out_dout(55 downto 48);
                a_V_4_reg_2016 <= layer2_out_dout(87 downto 80);
                a_V_5_reg_2022 <= layer2_out_dout(119 downto 112);
                a_V_6_reg_2027 <= layer2_out_dout(135 downto 128);
                a_V_7_reg_2032 <= layer2_out_dout(151 downto 144);
                a_V_8_reg_2038 <= layer2_out_dout(159 downto 152);
                a_V_9_reg_2043 <= layer2_out_dout(183 downto 176);
                a_V_reg_1991 <= a_V_fu_354_p1;
                tmp_10_reg_2094 <= layer2_out_dout(79 downto 72);
                tmp_13_reg_2100 <= layer2_out_dout(95 downto 88);
                tmp_15_reg_2106 <= layer2_out_dout(103 downto 96);
                tmp_17_reg_2112 <= layer2_out_dout(111 downto 104);
                tmp_20_reg_2123 <= layer2_out_dout(143 downto 136);
                tmp_23_reg_2129 <= layer2_out_dout(167 downto 160);
                tmp_25_reg_2135 <= layer2_out_dout(175 downto 168);
                tmp_26_reg_2141 <= layer2_out_dout(207 downto 200);
                tmp_27_reg_2147 <= layer2_out_dout(215 downto 208);
                tmp_28_reg_2153 <= layer2_out_dout(231 downto 224);
                tmp_2_reg_2070 <= layer2_out_dout(31 downto 24);
                tmp_30_reg_2164 <= layer2_out_dout(247 downto 240);
                tmp_4_reg_2076 <= layer2_out_dout(47 downto 40);
                tmp_6_reg_2082 <= layer2_out_dout(63 downto 56);
                tmp_8_reg_2088 <= layer2_out_dout(71 downto 64);
                tmp_reg_2064 <= layer2_out_dout(15 downto 8);
                trunc_ln818_16_reg_2159 <= add_ln1347_14_fu_698_p2(12 downto 6);
                trunc_ln818_8_reg_2118 <= add_ln1347_fu_600_p2(10 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state7))) then
                reg_326 <= grp_fu_317_p2(13 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then
                reg_332 <= grp_fu_317_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                tmp_1_reg_2210 <= r_V_5_fu_750_p2(6 downto 6);
                tmp_s_reg_2215 <= ret_V_2_fu_756_p2(11 downto 7);
                trunc_ln818_10_reg_2190 <= ret_V_16_fu_966_p2(11 downto 6);
                trunc_ln818_11_reg_2195 <= ret_V_18_fu_1010_p2(12 downto 6);
                trunc_ln818_12_reg_2200 <= ret_V_20_fu_1050_p2(12 downto 6);
                trunc_ln818_14_reg_2205 <= ret_V_23_fu_1094_p2(12 downto 6);
                trunc_ln818_3_reg_2170 <= ret_V_4_fu_790_p2(12 downto 6);
                trunc_ln818_5_reg_2175 <= ret_V_6_fu_834_p2(11 downto 6);
                trunc_ln818_6_reg_2180 <= ret_V_12_fu_878_p2(12 downto 6);
                trunc_ln818_s_reg_2185 <= ret_V_15_fu_926_p2(11 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                tmp_31_reg_2315 <= ret_V_1_fu_1330_p2(13 downto 6);
                trunc_ln46_10_reg_2310 <= ret_V_27_fu_1652_p2(13 downto 6);
                trunc_ln46_1_reg_2305 <= ret_V_26_fu_1618_p2(13 downto 6);
                trunc_ln46_2_reg_2270 <= ret_V_7_fu_1368_p2(13 downto 6);
                trunc_ln46_3_reg_2275 <= ret_V_8_fu_1406_p2(13 downto 6);
                trunc_ln46_4_reg_2280 <= ret_V_9_fu_1432_p2(13 downto 6);
                trunc_ln46_5_reg_2285 <= ret_V_10_fu_1466_p2(13 downto 6);
                trunc_ln46_6_reg_2290 <= ret_V_11_fu_1500_p2(13 downto 6);
                trunc_ln46_8_reg_2295 <= ret_V_19_fu_1534_p2(13 downto 6);
                trunc_ln46_s_reg_2300 <= ret_V_24_fu_1568_p2(13 downto 6);
                trunc_ln818_15_reg_2265 <= ret_V_25_fu_1574_p2(12 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                trunc_ln46_7_reg_2250 <= ret_V_17_fu_1242_p2(13 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                trunc_ln46_9_reg_2255 <= ret_V_21_fu_1262_p2(13 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                trunc_ln818_13_reg_2260 <= ret_V_22_fu_1282_p2(12 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                trunc_ln818_1_reg_2225 <= grp_fu_317_p2(13 downto 6);
                trunc_ln_reg_2220 <= ret_V_fu_1128_p2(12 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                trunc_ln818_2_reg_2230 <= ret_V_3_fu_1162_p2(12 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                trunc_ln818_4_reg_2235 <= ret_V_5_fu_1182_p2(11 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                trunc_ln818_7_reg_2240 <= ret_V_13_fu_1202_p2(12 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                trunc_ln818_9_reg_2245 <= ret_V_14_fu_1222_p2(12 downto 6);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, layer2_out_empty_n, layer4_out_full_n, ap_CS_fsm_state13)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((layer2_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                if (((layer4_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXX";
        end case;
    end process;
    a_V_fu_354_p1 <= layer2_out_dout(8 - 1 downto 0);
    add_ln1347_10_fu_1426_p2 <= std_logic_vector(signed(sext_ln1273_12_fu_1422_p1) + signed(sext_ln1270_3_fu_1412_p1));
    add_ln1347_14_fu_698_p2 <= std_logic_vector(signed(sext_ln1270_11_fu_694_p1) + signed(ap_const_lv13_1DC0));
    add_ln1347_18_fu_916_p2 <= std_logic_vector(signed(sext_ln1347_1_fu_912_p1) + signed(ap_const_lv10_300));
    add_ln1347_20_fu_956_p2 <= std_logic_vector(signed(sext_ln1270_7_fu_942_p1) + signed(ap_const_lv9_140));
    add_ln1347_25_fu_1040_p2 <= std_logic_vector(signed(sext_ln1270_8_fu_1026_p1) + signed(ap_const_lv11_540));
    add_ln1347_fu_600_p2 <= std_logic_vector(signed(sext_ln1270_5_fu_596_p1) + signed(ap_const_lv11_780));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;

    ap_ST_fsm_state13_blk_assign_proc : process(layer4_out_full_n)
    begin
        if ((layer4_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state13_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state13_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg, layer2_out_empty_n)
    begin
        if (((layer2_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(real_start, ap_done_reg, layer2_out_empty_n)
    begin
                ap_block_state1 <= ((layer2_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer4_out_full_n, ap_CS_fsm_state13)
    begin
        if (((layer4_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    grp_fu_317_p0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state12, ap_CS_fsm_state3, sext_ln1270_fu_724_p1, sext_ln1270_1_fu_1144_p1, sext_ln1270_2_fu_1158_p1, sext_ln1347_fu_1178_p1, sext_ln1270_4_fu_1198_p1, sext_ln1270_6_fu_1218_p1, sext_ln1347_3_fu_1238_p1, sext_ln1347_5_fu_1248_p1, sext_ln1270_9_fu_1268_p1, sext_ln1270_10_fu_1298_p1, sext_ln1347_6_fu_1658_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_317_p0 <= sext_ln1347_6_fu_1658_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_fu_317_p0 <= sext_ln1270_10_fu_1298_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_317_p0 <= sext_ln1270_9_fu_1268_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_fu_317_p0 <= sext_ln1347_5_fu_1248_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_317_p0 <= sext_ln1347_3_fu_1238_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_317_p0 <= sext_ln1270_6_fu_1218_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_317_p0 <= sext_ln1270_4_fu_1198_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_317_p0 <= sext_ln1347_fu_1178_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_317_p0 <= sext_ln1270_2_fu_1158_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_317_p0 <= sext_ln1270_1_fu_1144_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_317_p0 <= sext_ln1270_fu_724_p1(8 - 1 downto 0);
        else 
            grp_fu_317_p0 <= "XXXXXXXX";
        end if; 
    end process;


    grp_fu_317_p1_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state12, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_317_p1 <= ap_const_lv14_36(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_fu_317_p1 <= ap_const_lv14_29(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_317_p1 <= ap_const_lv14_27(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_317_p1 <= ap_const_lv13_1B(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_317_p1 <= ap_const_lv12_D(7 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            grp_fu_317_p1 <= ap_const_lv13_17(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_317_p1 <= ap_const_lv14_1A(7 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            grp_fu_317_p1 <= ap_const_lv13_D(7 - 1 downto 0);
        else 
            grp_fu_317_p1 <= "XXXXXXX";
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(layer4_out_full_n, ap_CS_fsm_state13)
    begin
        if (((layer4_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer2_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer2_out_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer2_out_blk_n <= layer2_out_empty_n;
        else 
            layer2_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer2_out_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer2_out_empty_n)
    begin
        if ((not(((layer2_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer2_out_read <= ap_const_logic_1;
        else 
            layer2_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer4_out_blk_n_assign_proc : process(layer4_out_full_n, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            layer4_out_blk_n <= layer4_out_full_n;
        else 
            layer4_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer4_out_din <= (((trunc_ln46_11_fu_1771_p4 & trunc_ln46_10_reg_2310) & sext_ln46_16_fu_1975_p1) & sext_ln818_fu_1762_p1);

    layer4_out_write_assign_proc : process(layer4_out_full_n, ap_CS_fsm_state13)
    begin
        if (((layer4_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            layer4_out_write <= ap_const_logic_1;
        else 
            layer4_out_write <= ap_const_logic_0;
        end if; 
    end process;

    r_V_10_fu_1358_p2 <= std_logic_vector(signed(sext_ln1273_8_fu_1343_p1) + signed(sext_ln1273_9_fu_1354_p1));
    r_V_11_fu_1396_p2 <= std_logic_vector(signed(sext_ln1273_10_fu_1381_p1) + signed(sext_ln1273_11_fu_1392_p1));
    r_V_13_fu_1460_p2 <= std_logic_vector(signed(sext_ln1273_13_fu_1445_p1) - signed(sext_ln1273_14_fu_1456_p1));
    r_V_14_fu_1494_p2 <= std_logic_vector(signed(sext_ln1273_15_fu_1479_p1) - signed(sext_ln1273_16_fu_1490_p1));
    r_V_15_fu_872_p2 <= std_logic_vector(signed(sext_ln1273_17_fu_857_p1) - signed(sext_ln1273_18_fu_868_p1));
    r_V_17_fu_588_p3 <= (tmp_19_fu_578_p4 & ap_const_lv2_0);
    r_V_22_fu_1004_p2 <= std_logic_vector(signed(sext_ln1273_21_fu_989_p1) - signed(sext_ln1273_22_fu_1000_p1));
    r_V_23_fu_1528_p2 <= std_logic_vector(signed(sext_ln1273_23_fu_1513_p1) - signed(sext_ln1273_24_fu_1524_p1));
    r_V_28_fu_1088_p2 <= std_logic_vector(signed(sext_ln1273_26_fu_1073_p1) - signed(sext_ln1273_27_fu_1084_p1));
    r_V_29_fu_1562_p2 <= std_logic_vector(signed(sext_ln1273_28_fu_1547_p1) - signed(sext_ln1273_29_fu_1558_p1));
    r_V_2_fu_1324_p2 <= std_logic_vector(signed(sext_ln1273_fu_1309_p1) - signed(sext_ln1273_1_fu_1320_p1));
    r_V_31_fu_1612_p2 <= std_logic_vector(signed(sext_ln1273_30_fu_1597_p1) - signed(sext_ln1273_31_fu_1608_p1));
    r_V_32_fu_686_p3 <= (tmp_29_fu_676_p4 & ap_const_lv4_0);
    r_V_33_fu_1646_p2 <= std_logic_vector(signed(sext_ln1273_32_fu_1631_p1) - signed(sext_ln1273_33_fu_1642_p1));
    r_V_5_fu_750_p2 <= std_logic_vector(signed(sext_ln1273_2_fu_735_p1) - signed(sext_ln1273_3_fu_746_p1));
    r_V_7_fu_784_p2 <= std_logic_vector(signed(sext_ln1273_4_fu_769_p1) - signed(sext_ln1273_5_fu_780_p1));
    r_V_9_fu_828_p2 <= std_logic_vector(signed(sext_ln1273_6_fu_813_p1) - signed(sext_ln1273_7_fu_824_p1));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    ret_V_10_fu_1466_p2 <= std_logic_vector(unsigned(r_V_13_fu_1460_p2) + unsigned(ap_const_lv14_3B80));
    ret_V_11_fu_1500_p2 <= std_logic_vector(unsigned(r_V_14_fu_1494_p2) + unsigned(ap_const_lv14_3940));
    ret_V_12_fu_878_p2 <= std_logic_vector(unsigned(r_V_15_fu_872_p2) + unsigned(ap_const_lv13_140));
    ret_V_13_fu_1202_p2 <= std_logic_vector(unsigned(reg_326) + unsigned(ap_const_lv13_1E80));
    ret_V_14_fu_1222_p2 <= std_logic_vector(unsigned(reg_326) + unsigned(ap_const_lv13_1BC0));
    ret_V_15_fu_926_p2 <= std_logic_vector(signed(sext_ln1347_2_fu_922_p1) + signed(sext_ln1273_19_fu_901_p1));
    ret_V_16_fu_966_p2 <= std_logic_vector(unsigned(zext_ln1347_fu_962_p1) + unsigned(sext_ln1273_20_fu_952_p1));
    ret_V_17_fu_1242_p2 <= std_logic_vector(unsigned(reg_332) + unsigned(ap_const_lv14_80));
    ret_V_18_fu_1010_p2 <= std_logic_vector(unsigned(r_V_22_fu_1004_p2) + unsigned(ap_const_lv13_100));
    ret_V_19_fu_1534_p2 <= std_logic_vector(unsigned(r_V_23_fu_1528_p2) + unsigned(ap_const_lv14_3AC0));
    ret_V_1_fu_1330_p2 <= std_logic_vector(unsigned(r_V_2_fu_1324_p2) + unsigned(ap_const_lv14_3BC0));
    ret_V_20_fu_1050_p2 <= std_logic_vector(signed(sext_ln1347_4_fu_1046_p1) + signed(sext_ln1273_25_fu_1036_p1));
    ret_V_21_fu_1262_p2 <= std_logic_vector(unsigned(reg_332) + unsigned(ap_const_lv14_3480));
    ret_V_22_fu_1282_p2 <= std_logic_vector(unsigned(reg_326) + unsigned(ap_const_lv13_1D80));
    ret_V_23_fu_1094_p2 <= std_logic_vector(unsigned(r_V_28_fu_1088_p2) + unsigned(ap_const_lv13_1D80));
    ret_V_24_fu_1568_p2 <= std_logic_vector(unsigned(r_V_29_fu_1562_p2) + unsigned(ap_const_lv14_100));
    ret_V_25_fu_1574_p2 <= std_logic_vector(unsigned(reg_326) + unsigned(ap_const_lv13_1C80));
    ret_V_26_fu_1618_p2 <= std_logic_vector(unsigned(r_V_31_fu_1612_p2) + unsigned(ap_const_lv14_3640));
    ret_V_27_fu_1652_p2 <= std_logic_vector(unsigned(r_V_33_fu_1646_p2) + unsigned(ap_const_lv14_3180));
    ret_V_28_fu_1765_p2 <= std_logic_vector(unsigned(reg_332) + unsigned(ap_const_lv14_3C40));
    ret_V_2_fu_756_p2 <= std_logic_vector(unsigned(r_V_5_fu_750_p2) + unsigned(ap_const_lv12_E80));
    ret_V_3_fu_1162_p2 <= std_logic_vector(unsigned(reg_326) + unsigned(ap_const_lv13_1C40));
    ret_V_4_fu_790_p2 <= std_logic_vector(unsigned(r_V_7_fu_784_p2) + unsigned(ap_const_lv13_1C40));
    ret_V_5_fu_1182_p0 <= reg_326(12 - 1 downto 0);
    ret_V_5_fu_1182_p2 <= std_logic_vector(unsigned(ret_V_5_fu_1182_p0) + unsigned(ap_const_lv12_80));
    ret_V_6_fu_834_p2 <= std_logic_vector(unsigned(r_V_9_fu_828_p2) + unsigned(ap_const_lv12_E40));
    ret_V_7_fu_1368_p2 <= std_logic_vector(signed(sext_ln813_fu_1364_p1) + signed(ap_const_lv14_3380));
    ret_V_8_fu_1406_p2 <= std_logic_vector(signed(sext_ln813_1_fu_1402_p1) + signed(ap_const_lv14_3040));
    ret_V_9_fu_1432_p2 <= std_logic_vector(unsigned(add_ln1347_10_fu_1426_p2) + unsigned(ap_const_lv14_3580));
    ret_V_fu_1128_p2 <= std_logic_vector(unsigned(reg_326) + unsigned(ap_const_lv13_1A00));
        sext_ln1270_10_fu_1298_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_V_12_reg_2059),13));

        sext_ln1270_11_fu_694_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_32_fu_686_p3),13));

        sext_ln1270_1_fu_1144_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_V_1_reg_2001),14));

        sext_ln1270_2_fu_1158_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_V_2_reg_2006),13));

        sext_ln1270_3_fu_1412_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_V_4_reg_2016),14));

        sext_ln1270_4_fu_1198_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_V_5_reg_2022),13));

        sext_ln1270_5_fu_596_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_17_fu_588_p3),11));

        sext_ln1270_6_fu_1218_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_V_6_reg_2027),13));

        sext_ln1270_7_fu_942_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_V_7_reg_2032),9));

        sext_ln1270_8_fu_1026_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_V_9_reg_2043),11));

        sext_ln1270_9_fu_1268_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_V_11_reg_2054),13));

        sext_ln1270_fu_724_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_V_reg_1991),13));

        sext_ln1273_10_fu_1381_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_s_fu_1374_p3),12));

        sext_ln1273_11_fu_1392_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_10_fu_1385_p3),12));

        sext_ln1273_12_fu_1422_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_11_fu_1415_p3),14));

        sext_ln1273_13_fu_1445_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_12_fu_1438_p3),14));

        sext_ln1273_14_fu_1456_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_13_fu_1449_p3),14));

        sext_ln1273_15_fu_1479_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_14_fu_1472_p3),14));

        sext_ln1273_16_fu_1490_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_15_fu_1483_p3),14));

        sext_ln1273_17_fu_857_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_16_fu_850_p3),13));

        sext_ln1273_18_fu_868_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_17_fu_861_p3),13));

        sext_ln1273_19_fu_901_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_18_fu_894_p3),12));

        sext_ln1273_1_fu_1320_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_1_fu_1313_p3),14));

        sext_ln1273_20_fu_952_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_20_fu_945_p3),12));

        sext_ln1273_21_fu_989_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_21_fu_982_p3),13));

        sext_ln1273_22_fu_1000_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_22_fu_993_p3),13));

        sext_ln1273_23_fu_1513_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_23_fu_1506_p3),14));

        sext_ln1273_24_fu_1524_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_24_fu_1517_p3),14));

        sext_ln1273_25_fu_1036_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_25_fu_1029_p3),13));

        sext_ln1273_26_fu_1073_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_26_fu_1066_p3),13));

        sext_ln1273_27_fu_1084_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_27_fu_1077_p3),13));

        sext_ln1273_28_fu_1547_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_28_fu_1540_p3),14));

        sext_ln1273_29_fu_1558_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_29_fu_1551_p3),14));

        sext_ln1273_2_fu_735_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_2_fu_728_p3),12));

        sext_ln1273_30_fu_1597_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_30_fu_1590_p3),14));

        sext_ln1273_31_fu_1608_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_31_fu_1601_p3),14));

        sext_ln1273_32_fu_1631_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_32_fu_1624_p3),14));

        sext_ln1273_33_fu_1642_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_33_fu_1635_p3),14));

        sext_ln1273_3_fu_746_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_3_fu_739_p3),12));

        sext_ln1273_4_fu_769_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_4_fu_762_p3),13));

        sext_ln1273_5_fu_780_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_5_fu_773_p3),13));

        sext_ln1273_6_fu_813_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_6_fu_806_p3),12));

        sext_ln1273_7_fu_824_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_7_fu_817_p3),12));

        sext_ln1273_8_fu_1343_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_8_fu_1336_p3),12));

        sext_ln1273_9_fu_1354_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_9_fu_1347_p3),12));

        sext_ln1273_fu_1309_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_1302_p3),14));

        sext_ln1347_1_fu_912_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_19_fu_905_p3),10));

        sext_ln1347_2_fu_922_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln1347_18_fu_916_p2),12));

        sext_ln1347_3_fu_1238_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_V_8_reg_2038),14));

        sext_ln1347_4_fu_1046_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln1347_25_fu_1040_p2),13));

        sext_ln1347_5_fu_1248_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_V_10_reg_2049),14));

        sext_ln1347_6_fu_1658_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_V_13_reg_1996),14));

        sext_ln1347_fu_1178_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_V_3_reg_2011),12));

        sext_ln46_10_fu_1904_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_42_fu_1897_p3),144));

        sext_ln46_11_fu_1916_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_43_fu_1908_p4),160));

        sext_ln46_12_fu_1928_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_44_fu_1920_p4),176));

        sext_ln46_13_fu_1940_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_45_fu_1932_p4),192));

        sext_ln46_14_fu_1951_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_46_fu_1944_p3),200));

        sext_ln46_15_fu_1963_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_47_fu_1955_p4),216));

        sext_ln46_16_fu_1975_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_48_fu_1967_p4),232));

        sext_ln46_1_fu_1800_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_33_fu_1793_p3),32));

        sext_ln46_2_fu_1811_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_34_fu_1804_p3),40));

        sext_ln46_3_fu_1822_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_35_fu_1815_p3),48));

        sext_ln46_4_fu_1833_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_36_fu_1826_p3),56));

        sext_ln46_5_fu_1849_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_37_fu_1837_p8),104));

        sext_ln46_6_fu_1860_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_38_fu_1853_p3),112));

        sext_ln46_7_fu_1871_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_39_fu_1864_p3),120));

        sext_ln46_8_fu_1882_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_40_fu_1875_p3),128));

        sext_ln46_9_fu_1893_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_41_fu_1886_p3),136));

        sext_ln46_fu_1789_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_32_fu_1781_p5),24));

        sext_ln813_1_fu_1402_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_11_fu_1396_p2),14));

        sext_ln813_fu_1364_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_10_fu_1358_p2),14));

        sext_ln818_fu_1762_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_reg_2220),8));

    shl_ln1273_10_fu_1385_p3 <= (tmp_10_reg_2094 & ap_const_lv1_0);
    shl_ln1273_11_fu_1415_p3 <= (a_V_4_reg_2016 & ap_const_lv5_0);
    shl_ln1273_12_fu_1438_p3 <= (tmp_13_reg_2100 & ap_const_lv5_0);
    shl_ln1273_13_fu_1449_p3 <= (tmp_13_reg_2100 & ap_const_lv3_0);
    shl_ln1273_14_fu_1472_p3 <= (tmp_15_reg_2106 & ap_const_lv5_0);
    shl_ln1273_15_fu_1483_p3 <= (tmp_15_reg_2106 & ap_const_lv3_0);
    shl_ln1273_16_fu_850_p3 <= (tmp_17_reg_2112 & ap_const_lv4_0);
    shl_ln1273_17_fu_861_p3 <= (tmp_17_reg_2112 & ap_const_lv2_0);
    shl_ln1273_18_fu_894_p3 <= (tmp_20_reg_2123 & ap_const_lv3_0);
    shl_ln1273_19_fu_905_p3 <= (tmp_20_reg_2123 & ap_const_lv1_0);
    shl_ln1273_1_fu_1313_p3 <= (tmp_reg_2064 & ap_const_lv1_0);
    shl_ln1273_20_fu_945_p3 <= (a_V_7_reg_2032 & ap_const_lv3_0);
    shl_ln1273_21_fu_982_p3 <= (tmp_23_reg_2129 & ap_const_lv4_0);
    shl_ln1273_22_fu_993_p3 <= (tmp_23_reg_2129 & ap_const_lv1_0);
    shl_ln1273_23_fu_1506_p3 <= (tmp_25_reg_2135 & ap_const_lv5_0);
    shl_ln1273_24_fu_1517_p3 <= (tmp_25_reg_2135 & ap_const_lv1_0);
    shl_ln1273_25_fu_1029_p3 <= (a_V_9_reg_2043 & ap_const_lv4_0);
    shl_ln1273_26_fu_1066_p3 <= (tmp_26_reg_2141 & ap_const_lv4_0);
    shl_ln1273_27_fu_1077_p3 <= (tmp_26_reg_2141 & ap_const_lv2_0);
    shl_ln1273_28_fu_1540_p3 <= (tmp_27_reg_2147 & ap_const_lv5_0);
    shl_ln1273_29_fu_1551_p3 <= (tmp_27_reg_2147 & ap_const_lv3_0);
    shl_ln1273_2_fu_728_p3 <= (tmp_2_reg_2070 & ap_const_lv3_0);
    shl_ln1273_30_fu_1590_p3 <= (tmp_28_reg_2153 & ap_const_lv5_0);
    shl_ln1273_31_fu_1601_p3 <= (tmp_28_reg_2153 & ap_const_lv2_0);
    shl_ln1273_32_fu_1624_p3 <= (tmp_30_reg_2164 & ap_const_lv5_0);
    shl_ln1273_33_fu_1635_p3 <= (tmp_30_reg_2164 & ap_const_lv2_0);
    shl_ln1273_3_fu_739_p3 <= (tmp_2_reg_2070 & ap_const_lv1_0);
    shl_ln1273_4_fu_762_p3 <= (tmp_4_reg_2076 & ap_const_lv4_0);
    shl_ln1273_5_fu_773_p3 <= (tmp_4_reg_2076 & ap_const_lv2_0);
    shl_ln1273_6_fu_806_p3 <= (tmp_6_reg_2082 & ap_const_lv3_0);
    shl_ln1273_7_fu_817_p3 <= (tmp_6_reg_2082 & ap_const_lv1_0);
    shl_ln1273_8_fu_1336_p3 <= (tmp_8_reg_2088 & ap_const_lv3_0);
    shl_ln1273_9_fu_1347_p3 <= (tmp_8_reg_2088 & ap_const_lv1_0);
    shl_ln1273_s_fu_1374_p3 <= (tmp_10_reg_2094 & ap_const_lv3_0);
    shl_ln_fu_1302_p3 <= (tmp_reg_2064 & ap_const_lv5_0);
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_19_fu_578_p4 <= layer2_out_dout(127 downto 120);
    tmp_29_fu_676_p4 <= layer2_out_dout(239 downto 232);
    tmp_32_fu_1781_p5 <= (((tmp_s_reg_2215 & tmp_1_reg_2210) & trunc_ln818_1_reg_2225) & tmp_31_reg_2315);
    tmp_33_fu_1793_p3 <= (trunc_ln818_2_reg_2230 & sext_ln46_fu_1789_p1);
    tmp_34_fu_1804_p3 <= (trunc_ln818_3_reg_2170 & sext_ln46_1_fu_1800_p1);
    tmp_35_fu_1815_p3 <= (trunc_ln818_4_reg_2235 & sext_ln46_2_fu_1811_p1);
    tmp_36_fu_1826_p3 <= (trunc_ln818_5_reg_2175 & sext_ln46_3_fu_1822_p1);
    tmp_37_fu_1837_p8 <= ((((((trunc_ln818_6_reg_2180 & trunc_ln46_6_reg_2290) & trunc_ln46_5_reg_2285) & trunc_ln46_4_reg_2280) & trunc_ln46_3_reg_2275) & trunc_ln46_2_reg_2270) & sext_ln46_4_fu_1833_p1);
    tmp_38_fu_1853_p3 <= (trunc_ln818_7_reg_2240 & sext_ln46_5_fu_1849_p1);
    tmp_39_fu_1864_p3 <= (trunc_ln818_8_reg_2118 & sext_ln46_6_fu_1860_p1);
    tmp_40_fu_1875_p3 <= (trunc_ln818_9_reg_2245 & sext_ln46_7_fu_1871_p1);
    tmp_41_fu_1886_p3 <= (trunc_ln818_s_reg_2185 & sext_ln46_8_fu_1882_p1);
    tmp_42_fu_1897_p3 <= (trunc_ln818_10_reg_2190 & sext_ln46_9_fu_1893_p1);
    tmp_43_fu_1908_p4 <= ((trunc_ln818_11_reg_2195 & trunc_ln46_7_reg_2250) & sext_ln46_10_fu_1904_p1);
    tmp_44_fu_1920_p4 <= ((trunc_ln818_12_reg_2200 & trunc_ln46_8_reg_2295) & sext_ln46_11_fu_1916_p1);
    tmp_45_fu_1932_p4 <= ((trunc_ln818_13_reg_2260 & trunc_ln46_9_reg_2255) & sext_ln46_12_fu_1928_p1);
    tmp_46_fu_1944_p3 <= (trunc_ln818_14_reg_2205 & sext_ln46_13_fu_1940_p1);
    tmp_47_fu_1955_p4 <= ((trunc_ln818_15_reg_2265 & trunc_ln46_s_reg_2300) & sext_ln46_14_fu_1951_p1);
    tmp_48_fu_1967_p4 <= ((trunc_ln818_16_reg_2159 & trunc_ln46_1_reg_2305) & sext_ln46_15_fu_1963_p1);
    trunc_ln46_11_fu_1771_p4 <= ret_V_28_fu_1765_p2(13 downto 6);
    zext_ln1347_fu_962_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1347_20_fu_956_p2),12));
end behav;
