-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity inference_Loop_VITIS_LOOP_86_1_proc1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_TVALID : IN STD_LOGIC;
    features_in_data_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    features_in_data_V_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
    features_in_data_V_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0);
    features_in_data_V_full_n : IN STD_LOGIC;
    features_in_data_V_write : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    input_r_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    input_r_TREADY : OUT STD_LOGIC;
    input_r_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    input_r_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    input_r_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
    input_r_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    input_r_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    input_r_TDEST : IN STD_LOGIC_VECTOR (5 downto 0) );
end;


architecture behav of inference_Loop_VITIS_LOOP_86_1_proc1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv54_0 : STD_LOGIC_VECTOR (53 downto 0) := "000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv12_433 : STD_LOGIC_VECTOR (11 downto 0) := "010000110011";
    constant ap_const_lv12_6 : STD_LOGIC_VECTOR (11 downto 0) := "000000000110";
    constant ap_const_lv12_FFA : STD_LOGIC_VECTOR (11 downto 0) := "111111111010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv12_36 : STD_LOGIC_VECTOR (11 downto 0) := "000000110110";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal icmp_ln86_fu_144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal features_in_data_V_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal input_r_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_data_V_reg_402 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_V_reg_402_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_V_reg_402_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_V_reg_402_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_V_reg_402_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_V_reg_402_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_V_reg_402_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln544_fu_173_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal trunc_ln544_reg_413 : STD_LOGIC_VECTOR (62 downto 0);
    signal p_Result_s_reg_418 : STD_LOGIC_VECTOR (0 downto 0);
    signal exp_tmp_reg_423 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln554_fu_195_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal trunc_ln554_reg_428 : STD_LOGIC_VECTOR (51 downto 0);
    signal man_V_2_fu_219_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal man_V_2_reg_433 : STD_LOGIC_VECTOR (53 downto 0);
    signal icmp_ln560_fu_226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln560_reg_438 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln560_reg_438_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln560_reg_438_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln570_fu_237_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln570_reg_445 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln570_reg_445_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sh_amt_fu_255_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sh_amt_reg_450 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln571_fu_263_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln571_reg_456 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln571_reg_456_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln572_fu_269_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln572_reg_462 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln572_reg_462_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_reg_468 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln570_fu_283_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln570_reg_473 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln574_fu_286_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln574_reg_478 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln574_reg_478_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln592_fu_300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln592_reg_488 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_295_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal ashr_ln575_reg_493 : STD_LOGIC_VECTOR (53 downto 0);
    signal select_ln571_fu_330_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln571_reg_498 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln570_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln570_reg_503 : STD_LOGIC_VECTOR (0 downto 0);
    signal h_fu_104 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln86_fu_150_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_h_1 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal grp_fu_133_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_133_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ireg_fu_169_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Result_1_fu_202_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln558_fu_209_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal man_V_1_fu_213_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal zext_ln455_fu_199_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal F2_fu_231_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln570_fu_243_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln570_fu_249_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_295_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal sext_ln570cast_fu_305_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln593_fu_308_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln560_fu_320_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln571_fu_325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln592_fu_313_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln571_fu_337_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln571_fu_341_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_355_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln575_fu_352_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln574_1_fu_362_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln574_fu_370_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln570_fu_377_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_133_ce : STD_LOGIC;
    signal grp_fu_295_ce : STD_LOGIC;
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal regslice_both_input_r_V_data_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal input_r_TVALID_int_regslice : STD_LOGIC;
    signal input_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_input_r_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_r_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_input_r_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_r_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_r_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_input_r_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_r_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_r_V_user_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TUSER_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_input_r_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_r_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_r_V_last_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_input_r_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_r_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_r_V_id_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TID_int_regslice : STD_LOGIC_VECTOR (4 downto 0);
    signal regslice_both_input_r_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_r_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_r_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal input_r_TDEST_int_regslice : STD_LOGIC_VECTOR (5 downto 0);
    signal regslice_both_input_r_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_r_V_dest_V_U_ack_in : STD_LOGIC;
    signal ap_condition_209 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component inference_fpext_32ns_64_3_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component inference_ashr_54ns_32ns_54_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        OP : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (53 downto 0);
        din1 : IN STD_LOGIC_VECTOR (53 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (53 downto 0) );
    end component;


    component inference_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component inference_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    fpext_32ns_64_3_no_dsp_1_U1 : component inference_fpext_32ns_64_3_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_133_p0,
        ce => grp_fu_133_ce,
        dout => grp_fu_133_p1);

    ashr_54ns_32ns_54_2_1_U2 : component inference_ashr_54ns_32ns_54_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        OP => 2,
        din0_WIDTH => 54,
        din1_WIDTH => 32,
        dout_WIDTH => 54)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => man_V_2_reg_433,
        din1 => grp_fu_295_p1,
        ce => grp_fu_295_ce,
        dout => grp_fu_295_p2);

    flow_control_loop_pipe_U : component inference_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);

    regslice_both_input_r_V_data_V_U : component inference_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => input_r_TDATA,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_data_V_U_ack_in,
        data_out => input_r_TDATA_int_regslice,
        vld_out => input_r_TVALID_int_regslice,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_data_V_U_apdone_blk);

    regslice_both_input_r_V_keep_V_U : component inference_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => input_r_TKEEP,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_keep_V_U_ack_in,
        data_out => input_r_TKEEP_int_regslice,
        vld_out => regslice_both_input_r_V_keep_V_U_vld_out,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_keep_V_U_apdone_blk);

    regslice_both_input_r_V_strb_V_U : component inference_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => input_r_TSTRB,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_strb_V_U_ack_in,
        data_out => input_r_TSTRB_int_regslice,
        vld_out => regslice_both_input_r_V_strb_V_U_vld_out,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_strb_V_U_apdone_blk);

    regslice_both_input_r_V_user_V_U : component inference_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => input_r_TUSER,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_user_V_U_ack_in,
        data_out => input_r_TUSER_int_regslice,
        vld_out => regslice_both_input_r_V_user_V_U_vld_out,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_user_V_U_apdone_blk);

    regslice_both_input_r_V_last_V_U : component inference_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => input_r_TLAST,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_last_V_U_ack_in,
        data_out => input_r_TLAST_int_regslice,
        vld_out => regslice_both_input_r_V_last_V_U_vld_out,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_last_V_U_apdone_blk);

    regslice_both_input_r_V_id_V_U : component inference_regslice_both
    generic map (
        DataWidth => 5)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => input_r_TID,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_id_V_U_ack_in,
        data_out => input_r_TID_int_regslice,
        vld_out => regslice_both_input_r_V_id_V_U_vld_out,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_id_V_U_apdone_blk);

    regslice_both_input_r_V_dest_V_U : component inference_regslice_both
    generic map (
        DataWidth => 6)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => input_r_TDEST,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_V_dest_V_U_ack_in,
        data_out => input_r_TDEST_int_regslice,
        vld_out => regslice_both_input_r_V_dest_V_U_vld_out,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    h_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_209)) then
                if ((icmp_ln86_fu_144_p2 = ap_const_lv1_0)) then 
                    h_fu_104 <= add_ln86_fu_150_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    h_fu_104 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln560_reg_438_pp0_iter5_reg = ap_const_lv1_0))) then
                and_ln570_reg_503 <= and_ln570_fu_347_p2;
                ashr_ln575_reg_493 <= grp_fu_295_p2;
                select_ln571_reg_498 <= select_ln571_fu_330_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                tmp_data_V_reg_402_pp0_iter1_reg <= tmp_data_V_reg_402;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                exp_tmp_reg_423 <= ireg_fu_169_p1(62 downto 52);
                icmp_ln560_reg_438 <= icmp_ln560_fu_226_p2;
                icmp_ln560_reg_438_pp0_iter5_reg <= icmp_ln560_reg_438;
                icmp_ln560_reg_438_pp0_iter6_reg <= icmp_ln560_reg_438_pp0_iter5_reg;
                icmp_ln570_reg_445 <= icmp_ln570_fu_237_p2;
                icmp_ln570_reg_445_pp0_iter5_reg <= icmp_ln570_reg_445;
                icmp_ln571_reg_456 <= icmp_ln571_fu_263_p2;
                icmp_ln571_reg_456_pp0_iter5_reg <= icmp_ln571_reg_456;
                icmp_ln574_reg_478_pp0_iter6_reg <= icmp_ln574_reg_478;
                man_V_2_reg_433 <= man_V_2_fu_219_p3;
                p_Result_s_reg_418 <= ireg_fu_169_p1(63 downto 63);
                sh_amt_reg_450 <= sh_amt_fu_255_p3;
                tmp_4_reg_468 <= sh_amt_fu_255_p3(11 downto 3);
                tmp_data_V_reg_402_pp0_iter2_reg <= tmp_data_V_reg_402_pp0_iter1_reg;
                tmp_data_V_reg_402_pp0_iter3_reg <= tmp_data_V_reg_402_pp0_iter2_reg;
                tmp_data_V_reg_402_pp0_iter4_reg <= tmp_data_V_reg_402_pp0_iter3_reg;
                tmp_data_V_reg_402_pp0_iter5_reg <= tmp_data_V_reg_402_pp0_iter4_reg;
                tmp_data_V_reg_402_pp0_iter6_reg <= tmp_data_V_reg_402_pp0_iter5_reg;
                trunc_ln544_reg_413 <= trunc_ln544_fu_173_p1;
                trunc_ln554_reg_428 <= trunc_ln554_fu_195_p1;
                trunc_ln572_reg_462 <= trunc_ln572_fu_269_p1;
                trunc_ln572_reg_462_pp0_iter5_reg <= trunc_ln572_reg_462;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln560_reg_438 = ap_const_lv1_0))) then
                icmp_ln574_reg_478 <= icmp_ln574_fu_286_p2;
                icmp_ln592_reg_488 <= icmp_ln592_fu_300_p2;
                sext_ln570_reg_473 <= sext_ln570_fu_283_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln86_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_data_V_reg_402 <= input_r_TDATA_int_regslice;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    F2_fu_231_p2 <= std_logic_vector(unsigned(ap_const_lv12_433) - unsigned(zext_ln455_fu_199_p1));
    add_ln570_fu_243_p2 <= std_logic_vector(unsigned(F2_fu_231_p2) + unsigned(ap_const_lv12_FFA));
    add_ln86_fu_150_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_h_1) + unsigned(ap_const_lv5_1));
    and_ln570_fu_347_p2 <= (xor_ln571_fu_341_p2 and icmp_ln570_reg_445_pp0_iter5_reg);
    and_ln571_fu_325_p2 <= (xor_ln560_fu_320_p2 and icmp_ln571_reg_456_pp0_iter5_reg);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter7, icmp_ln86_fu_144_p2, ap_done_reg, features_in_data_V_full_n, ap_start_int, input_r_TVALID_int_regslice)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((features_in_data_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((icmp_ln86_fu_144_p2 = ap_const_lv1_0) and (input_r_TVALID_int_regslice = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter7, icmp_ln86_fu_144_p2, ap_done_reg, features_in_data_V_full_n, ap_start_int, input_r_TVALID_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((features_in_data_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((icmp_ln86_fu_144_p2 = ap_const_lv1_0) and (input_r_TVALID_int_regslice = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter7, icmp_ln86_fu_144_p2, ap_done_reg, features_in_data_V_full_n, ap_start_int, input_r_TVALID_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((features_in_data_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or ((icmp_ln86_fu_144_p2 = ap_const_lv1_0) and (input_r_TVALID_int_regslice = ap_const_logic_0)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(icmp_ln86_fu_144_p2, ap_done_reg, input_r_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or ((icmp_ln86_fu_144_p2 = ap_const_lv1_0) and (input_r_TVALID_int_regslice = ap_const_logic_0)));
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state8_pp0_stage0_iter7_assign_proc : process(features_in_data_V_full_n)
    begin
                ap_block_state8_pp0_stage0_iter7 <= (features_in_data_V_full_n = ap_const_logic_0);
    end process;


    ap_condition_209_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_209 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln86_fu_144_p2, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln86_fu_144_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter6_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_h_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, h_fu_104, ap_loop_init, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_h_1 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_h_1 <= h_fu_104;
        end if; 
    end process;


    features_in_data_V_blk_n_assign_proc : process(ap_enable_reg_pp0_iter7, features_in_data_V_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            features_in_data_V_blk_n <= features_in_data_V_full_n;
        else 
            features_in_data_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    features_in_data_V_din <= 
        ap_const_lv8_0 when (icmp_ln560_reg_438_pp0_iter6_reg(0) = '1') else 
        select_ln570_fu_377_p3;

    features_in_data_V_write_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            features_in_data_V_write <= ap_const_logic_1;
        else 
            features_in_data_V_write <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_133_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_133_ce <= ap_const_logic_1;
        else 
            grp_fu_133_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_133_p0 <= tmp_data_V_reg_402;

    grp_fu_295_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_295_ce <= ap_const_logic_1;
        else 
            grp_fu_295_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_295_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln570_fu_283_p1),54));
    icmp_ln560_fu_226_p2 <= "1" when (trunc_ln544_reg_413 = ap_const_lv63_0) else "0";
    icmp_ln570_fu_237_p2 <= "1" when (signed(F2_fu_231_p2) > signed(ap_const_lv12_6)) else "0";
    icmp_ln571_fu_263_p2 <= "1" when (F2_fu_231_p2 = ap_const_lv12_6) else "0";
    icmp_ln574_fu_286_p2 <= "1" when (unsigned(sh_amt_reg_450) < unsigned(ap_const_lv12_36)) else "0";
    icmp_ln592_fu_300_p2 <= "1" when (tmp_4_reg_468 = ap_const_lv9_0) else "0";
    icmp_ln86_fu_144_p2 <= "1" when (ap_sig_allocacmp_h_1 = ap_const_lv5_12) else "0";

    input_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln86_fu_144_p2, ap_done_reg, ap_block_pp0_stage0, ap_start_int, input_r_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_done_reg = ap_const_logic_0) and (icmp_ln86_fu_144_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_r_TDATA_blk_n <= input_r_TVALID_int_regslice;
        else 
            input_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    input_r_TREADY <= regslice_both_input_r_V_data_V_U_ack_in;

    input_r_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln86_fu_144_p2, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln86_fu_144_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_r_TREADY_int_regslice <= ap_const_logic_1;
        else 
            input_r_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    ireg_fu_169_p1 <= grp_fu_133_p1;
    man_V_1_fu_213_p2 <= std_logic_vector(unsigned(ap_const_lv54_0) - unsigned(zext_ln558_fu_209_p1));
    man_V_2_fu_219_p3 <= 
        man_V_1_fu_213_p2 when (p_Result_s_reg_418(0) = '1') else 
        zext_ln558_fu_209_p1;
    or_ln571_fu_337_p2 <= (icmp_ln571_reg_456_pp0_iter5_reg or icmp_ln560_reg_438_pp0_iter5_reg);
    p_Result_1_fu_202_p3 <= (ap_const_lv1_1 & trunc_ln554_reg_428);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln570_fu_377_p3 <= 
        select_ln574_fu_370_p3 when (and_ln570_reg_503(0) = '1') else 
        select_ln571_reg_498;
    select_ln571_fu_330_p3 <= 
        trunc_ln572_reg_462_pp0_iter5_reg when (and_ln571_fu_325_p2(0) = '1') else 
        select_ln592_fu_313_p3;
    select_ln574_1_fu_362_p3 <= 
        ap_const_lv8_FF when (tmp_fu_355_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln574_fu_370_p3 <= 
        trunc_ln575_fu_352_p1 when (icmp_ln574_reg_478_pp0_iter6_reg(0) = '1') else 
        select_ln574_1_fu_362_p3;
    select_ln592_fu_313_p3 <= 
        shl_ln593_fu_308_p2 when (icmp_ln592_reg_488(0) = '1') else 
        ap_const_lv8_0;
        sext_ln570_fu_283_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sh_amt_reg_450),32));

    sext_ln570cast_fu_305_p1 <= sext_ln570_reg_473(8 - 1 downto 0);
    sh_amt_fu_255_p3 <= 
        add_ln570_fu_243_p2 when (icmp_ln570_fu_237_p2(0) = '1') else 
        sub_ln570_fu_249_p2;
    shl_ln593_fu_308_p2 <= std_logic_vector(shift_left(unsigned(trunc_ln572_reg_462_pp0_iter5_reg),to_integer(unsigned('0' & sext_ln570cast_fu_305_p1(8-1 downto 0)))));
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln570_fu_249_p2 <= std_logic_vector(unsigned(ap_const_lv12_6) - unsigned(F2_fu_231_p2));
    tmp_fu_355_p3 <= tmp_data_V_reg_402_pp0_iter6_reg(31 downto 31);
    trunc_ln544_fu_173_p1 <= ireg_fu_169_p1(63 - 1 downto 0);
    trunc_ln554_fu_195_p1 <= ireg_fu_169_p1(52 - 1 downto 0);
    trunc_ln572_fu_269_p1 <= man_V_2_fu_219_p3(8 - 1 downto 0);
    trunc_ln575_fu_352_p1 <= ashr_ln575_reg_493(8 - 1 downto 0);
    xor_ln560_fu_320_p2 <= (icmp_ln560_reg_438_pp0_iter5_reg xor ap_const_lv1_1);
    xor_ln571_fu_341_p2 <= (or_ln571_fu_337_p2 xor ap_const_lv1_1);
    zext_ln455_fu_199_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_tmp_reg_423),12));
    zext_ln558_fu_209_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_1_fu_202_p3),54));
end behav;
