-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity inference_relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer8_out_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    layer8_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer8_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer8_out_empty_n : IN STD_LOGIC;
    layer8_out_read : OUT STD_LOGIC;
    layer9_out_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    layer9_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer9_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer9_out_full_n : IN STD_LOGIC;
    layer9_out_write : OUT STD_LOGIC );
end;


architecture behav of inference_relu_array_ap_fixed_16u_array_ap_fixed_8_2_5_3_0_16u_relu_config9_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_2E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101110";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_46 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000110";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_4E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001110";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_57 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010111";
    constant ap_const_lv32_56 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010110";
    constant ap_const_lv32_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_5E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011110";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv32_66 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100110";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_6E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101110";
    constant ap_const_lv32_76 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110110";
    constant ap_const_lv32_7E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111110";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer8_out_blk_n : STD_LOGIC;
    signal layer9_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal trunc_ln44_2_fu_135_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_2_reg_732 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_s_reg_737 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_35_reg_742 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_36_reg_747 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_37_reg_752 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_38_reg_757 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_39_reg_762 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_40_reg_767 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_41_reg_772 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_42_reg_777 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_43_reg_782 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_44_reg_787 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_45_reg_792 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_46_reg_797 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_47_reg_802 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln_reg_807 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln1649_fu_439_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_reg_812 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_32_fu_445_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_32_reg_817 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_33_fu_451_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_33_reg_822 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_34_fu_457_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_34_reg_827 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_35_fu_463_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_35_reg_832 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_36_fu_469_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_36_reg_837 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_37_fu_475_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_37_reg_842 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_38_fu_481_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_38_reg_847 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_39_fu_487_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_39_reg_852 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_40_fu_493_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_40_reg_857 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_41_fu_499_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_41_reg_862 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_42_fu_505_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_42_reg_867 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_43_fu_511_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_43_reg_872 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_44_fu_517_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_44_reg_877 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_45_fu_523_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_45_reg_882 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_46_fu_529_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_46_reg_887 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal in_data_data_fu_131_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_data_data_22_fu_159_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_data_data_23_fu_179_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_data_data_24_fu_199_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_data_data_25_fu_219_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_data_data_26_fu_239_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_data_data_27_fu_259_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_data_data_28_fu_279_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_299_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_319_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_21_fu_339_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_22_fu_359_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_23_fu_379_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_24_fu_399_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln44_33_fu_139_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln44_34_fu_149_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln51_fu_535_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_32_fu_545_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_33_fu_555_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_34_fu_565_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_35_fu_575_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_36_fu_585_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_37_fu_595_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_38_fu_605_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_39_fu_615_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_40_fu_625_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_41_fu_635_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_42_fu_645_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_43_fu_655_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_44_fu_665_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_45_fu_675_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_46_fu_685_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln1649_44_fu_681_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_43_fu_671_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_42_fu_661_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_41_fu_651_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_40_fu_641_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_39_fu_631_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_38_fu_621_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_37_fu_611_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_36_fu_601_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_35_fu_591_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_34_fu_581_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_33_fu_571_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_32_fu_561_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_31_fu_551_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_fu_541_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln57_s_fu_691_p17 : STD_LOGIC_VECTOR (126 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((layer9_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                icmp_ln1649_32_reg_817 <= icmp_ln1649_32_fu_445_p2;
                icmp_ln1649_33_reg_822 <= icmp_ln1649_33_fu_451_p2;
                icmp_ln1649_34_reg_827 <= icmp_ln1649_34_fu_457_p2;
                icmp_ln1649_35_reg_832 <= icmp_ln1649_35_fu_463_p2;
                icmp_ln1649_36_reg_837 <= icmp_ln1649_36_fu_469_p2;
                icmp_ln1649_37_reg_842 <= icmp_ln1649_37_fu_475_p2;
                icmp_ln1649_38_reg_847 <= icmp_ln1649_38_fu_481_p2;
                icmp_ln1649_39_reg_852 <= icmp_ln1649_39_fu_487_p2;
                icmp_ln1649_40_reg_857 <= icmp_ln1649_40_fu_493_p2;
                icmp_ln1649_41_reg_862 <= icmp_ln1649_41_fu_499_p2;
                icmp_ln1649_42_reg_867 <= icmp_ln1649_42_fu_505_p2;
                icmp_ln1649_43_reg_872 <= icmp_ln1649_43_fu_511_p2;
                icmp_ln1649_44_reg_877 <= icmp_ln1649_44_fu_517_p2;
                icmp_ln1649_45_reg_882 <= icmp_ln1649_45_fu_523_p2;
                icmp_ln1649_46_reg_887 <= icmp_ln1649_46_fu_529_p2;
                icmp_ln1649_reg_812 <= icmp_ln1649_fu_439_p2;
                trunc_ln44_2_reg_732 <= trunc_ln44_2_fu_135_p1;
                trunc_ln44_35_reg_742 <= layer8_out_dout(22 downto 16);
                trunc_ln44_36_reg_747 <= layer8_out_dout(30 downto 24);
                trunc_ln44_37_reg_752 <= layer8_out_dout(38 downto 32);
                trunc_ln44_38_reg_757 <= layer8_out_dout(46 downto 40);
                trunc_ln44_39_reg_762 <= layer8_out_dout(54 downto 48);
                trunc_ln44_40_reg_767 <= layer8_out_dout(62 downto 56);
                trunc_ln44_41_reg_772 <= layer8_out_dout(70 downto 64);
                trunc_ln44_42_reg_777 <= layer8_out_dout(78 downto 72);
                trunc_ln44_43_reg_782 <= layer8_out_dout(86 downto 80);
                trunc_ln44_44_reg_787 <= layer8_out_dout(94 downto 88);
                trunc_ln44_45_reg_792 <= layer8_out_dout(102 downto 96);
                trunc_ln44_46_reg_797 <= layer8_out_dout(110 downto 104);
                trunc_ln44_47_reg_802 <= layer8_out_dout(118 downto 112);
                trunc_ln44_s_reg_737 <= layer8_out_dout(14 downto 8);
                trunc_ln_reg_807 <= layer8_out_dout(126 downto 120);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, layer8_out_empty_n, layer9_out_full_n, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((real_start = ap_const_logic_0) or (layer8_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((layer9_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg, layer8_out_empty_n)
    begin
        if (((real_start = ap_const_logic_0) or (layer8_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(layer9_out_full_n)
    begin
        if ((layer9_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, layer8_out_empty_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (layer8_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer9_out_full_n, ap_CS_fsm_state2)
    begin
        if (((layer9_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    icmp_ln1649_32_fu_445_p2 <= "1" when (signed(in_data_data_22_fu_159_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_33_fu_451_p2 <= "1" when (signed(in_data_data_23_fu_179_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_34_fu_457_p2 <= "1" when (signed(in_data_data_24_fu_199_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_35_fu_463_p2 <= "1" when (signed(in_data_data_25_fu_219_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_36_fu_469_p2 <= "1" when (signed(in_data_data_26_fu_239_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_37_fu_475_p2 <= "1" when (signed(in_data_data_27_fu_259_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_38_fu_481_p2 <= "1" when (signed(in_data_data_28_fu_279_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_39_fu_487_p2 <= "1" when (signed(tmp_fu_299_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_40_fu_493_p2 <= "1" when (signed(tmp_s_fu_319_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_41_fu_499_p2 <= "1" when (signed(tmp_21_fu_339_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_42_fu_505_p2 <= "1" when (signed(tmp_22_fu_359_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_43_fu_511_p2 <= "1" when (signed(tmp_23_fu_379_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_44_fu_517_p2 <= "1" when (signed(tmp_24_fu_399_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_45_fu_523_p2 <= "1" when (signed(trunc_ln44_33_fu_139_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_46_fu_529_p2 <= "1" when (signed(trunc_ln44_34_fu_149_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_fu_439_p2 <= "1" when (signed(in_data_data_fu_131_p1) > signed(ap_const_lv8_0)) else "0";
    in_data_data_22_fu_159_p4 <= layer8_out_dout(15 downto 8);
    in_data_data_23_fu_179_p4 <= layer8_out_dout(23 downto 16);
    in_data_data_24_fu_199_p4 <= layer8_out_dout(31 downto 24);
    in_data_data_25_fu_219_p4 <= layer8_out_dout(39 downto 32);
    in_data_data_26_fu_239_p4 <= layer8_out_dout(47 downto 40);
    in_data_data_27_fu_259_p4 <= layer8_out_dout(55 downto 48);
    in_data_data_28_fu_279_p4 <= layer8_out_dout(63 downto 56);
    in_data_data_fu_131_p1 <= layer8_out_dout(8 - 1 downto 0);

    internal_ap_ready_assign_proc : process(layer9_out_full_n, ap_CS_fsm_state2)
    begin
        if (((layer9_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer8_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer8_out_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer8_out_blk_n <= layer8_out_empty_n;
        else 
            layer8_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer8_out_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer8_out_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (layer8_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer8_out_read <= ap_const_logic_1;
        else 
            layer8_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer9_out_blk_n_assign_proc : process(layer9_out_full_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            layer9_out_blk_n <= layer9_out_full_n;
        else 
            layer9_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer9_out_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln57_s_fu_691_p17),128));

    layer9_out_write_assign_proc : process(layer9_out_full_n, ap_CS_fsm_state2)
    begin
        if (((layer9_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            layer9_out_write <= ap_const_logic_1;
        else 
            layer9_out_write <= ap_const_logic_0;
        end if; 
    end process;

    or_ln57_s_fu_691_p17 <= (((((((((((((((select_ln51_46_fu_685_p3 & zext_ln1649_44_fu_681_p1) & zext_ln1649_43_fu_671_p1) & zext_ln1649_42_fu_661_p1) & zext_ln1649_41_fu_651_p1) & zext_ln1649_40_fu_641_p1) & zext_ln1649_39_fu_631_p1) & zext_ln1649_38_fu_621_p1) & zext_ln1649_37_fu_611_p1) & zext_ln1649_36_fu_601_p1) & zext_ln1649_35_fu_591_p1) & zext_ln1649_34_fu_581_p1) & zext_ln1649_33_fu_571_p1) & zext_ln1649_32_fu_561_p1) & zext_ln1649_31_fu_551_p1) & zext_ln1649_fu_541_p1);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln51_32_fu_545_p3 <= 
        trunc_ln44_s_reg_737 when (icmp_ln1649_32_reg_817(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_33_fu_555_p3 <= 
        trunc_ln44_35_reg_742 when (icmp_ln1649_33_reg_822(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_34_fu_565_p3 <= 
        trunc_ln44_36_reg_747 when (icmp_ln1649_34_reg_827(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_35_fu_575_p3 <= 
        trunc_ln44_37_reg_752 when (icmp_ln1649_35_reg_832(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_36_fu_585_p3 <= 
        trunc_ln44_38_reg_757 when (icmp_ln1649_36_reg_837(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_37_fu_595_p3 <= 
        trunc_ln44_39_reg_762 when (icmp_ln1649_37_reg_842(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_38_fu_605_p3 <= 
        trunc_ln44_40_reg_767 when (icmp_ln1649_38_reg_847(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_39_fu_615_p3 <= 
        trunc_ln44_41_reg_772 when (icmp_ln1649_39_reg_852(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_40_fu_625_p3 <= 
        trunc_ln44_42_reg_777 when (icmp_ln1649_40_reg_857(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_41_fu_635_p3 <= 
        trunc_ln44_43_reg_782 when (icmp_ln1649_41_reg_862(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_42_fu_645_p3 <= 
        trunc_ln44_44_reg_787 when (icmp_ln1649_42_reg_867(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_43_fu_655_p3 <= 
        trunc_ln44_45_reg_792 when (icmp_ln1649_43_reg_872(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_44_fu_665_p3 <= 
        trunc_ln44_46_reg_797 when (icmp_ln1649_44_reg_877(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_45_fu_675_p3 <= 
        trunc_ln44_47_reg_802 when (icmp_ln1649_45_reg_882(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_46_fu_685_p3 <= 
        trunc_ln_reg_807 when (icmp_ln1649_46_reg_887(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_fu_535_p3 <= 
        trunc_ln44_2_reg_732 when (icmp_ln1649_reg_812(0) = '1') else 
        ap_const_lv7_0;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_21_fu_339_p4 <= layer8_out_dout(87 downto 80);
    tmp_22_fu_359_p4 <= layer8_out_dout(95 downto 88);
    tmp_23_fu_379_p4 <= layer8_out_dout(103 downto 96);
    tmp_24_fu_399_p4 <= layer8_out_dout(111 downto 104);
    tmp_fu_299_p4 <= layer8_out_dout(71 downto 64);
    tmp_s_fu_319_p4 <= layer8_out_dout(79 downto 72);
    trunc_ln44_2_fu_135_p1 <= layer8_out_dout(7 - 1 downto 0);
    trunc_ln44_33_fu_139_p4 <= layer8_out_dout(119 downto 112);
    trunc_ln44_34_fu_149_p4 <= layer8_out_dout(127 downto 120);
    zext_ln1649_31_fu_551_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_32_fu_545_p3),8));
    zext_ln1649_32_fu_561_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_33_fu_555_p3),8));
    zext_ln1649_33_fu_571_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_34_fu_565_p3),8));
    zext_ln1649_34_fu_581_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_35_fu_575_p3),8));
    zext_ln1649_35_fu_591_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_36_fu_585_p3),8));
    zext_ln1649_36_fu_601_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_37_fu_595_p3),8));
    zext_ln1649_37_fu_611_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_38_fu_605_p3),8));
    zext_ln1649_38_fu_621_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_39_fu_615_p3),8));
    zext_ln1649_39_fu_631_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_40_fu_625_p3),8));
    zext_ln1649_40_fu_641_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_41_fu_635_p3),8));
    zext_ln1649_41_fu_651_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_42_fu_645_p3),8));
    zext_ln1649_42_fu_661_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_43_fu_655_p3),8));
    zext_ln1649_43_fu_671_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_44_fu_665_p3),8));
    zext_ln1649_44_fu_681_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_45_fu_675_p3),8));
    zext_ln1649_fu_541_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_fu_535_p3),8));
end behav;
