-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity inference_relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer4_out_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    layer4_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer4_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer4_out_empty_n : IN STD_LOGIC;
    layer4_out_read : OUT STD_LOGIC;
    layer5_out_din : OUT STD_LOGIC_VECTOR (255 downto 0);
    layer5_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer5_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer5_out_full_n : IN STD_LOGIC;
    layer5_out_write : OUT STD_LOGIC );
end;


architecture behav of inference_relu_array_ap_fixed_32u_array_ap_fixed_8_2_5_3_0_32u_relu_config5_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_F7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110111";
    constant ap_const_lv32_F8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_2E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101110";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_46 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000110";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_4E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001110";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_57 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010111";
    constant ap_const_lv32_56 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010110";
    constant ap_const_lv32_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_5E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011110";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv32_66 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100110";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_6E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101110";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_76 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110110";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_7E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111110";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_87 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000111";
    constant ap_const_lv32_86 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000110";
    constant ap_const_lv32_88 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001000";
    constant ap_const_lv32_8F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001111";
    constant ap_const_lv32_8E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001110";
    constant ap_const_lv32_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010000";
    constant ap_const_lv32_97 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010111";
    constant ap_const_lv32_96 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010110";
    constant ap_const_lv32_98 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_9E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011110";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_A7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100111";
    constant ap_const_lv32_A6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100110";
    constant ap_const_lv32_A8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101000";
    constant ap_const_lv32_AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101111";
    constant ap_const_lv32_AE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101110";
    constant ap_const_lv32_B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110000";
    constant ap_const_lv32_B7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110111";
    constant ap_const_lv32_B6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110110";
    constant ap_const_lv32_B8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_BE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111110";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_C7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000111";
    constant ap_const_lv32_C6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000110";
    constant ap_const_lv32_C8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001000";
    constant ap_const_lv32_CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001111";
    constant ap_const_lv32_CE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001110";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_D7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010111";
    constant ap_const_lv32_D6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010110";
    constant ap_const_lv32_D8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_DE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011110";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_E7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100111";
    constant ap_const_lv32_E6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100110";
    constant ap_const_lv32_E8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101000";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_EE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101110";
    constant ap_const_lv32_F6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110110";
    constant ap_const_lv32_FE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111110";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer4_out_blk_n : STD_LOGIC;
    signal layer5_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal trunc_ln44_1_fu_231_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_1_reg_1436 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_s_reg_1441 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_4_reg_1446 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_5_reg_1451 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_6_reg_1456 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_7_reg_1461 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_8_reg_1466 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_9_reg_1471 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_10_reg_1476 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_11_reg_1481 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_12_reg_1486 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_13_reg_1491 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_14_reg_1496 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_15_reg_1501 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_16_reg_1506 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_17_reg_1511 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_18_reg_1516 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_19_reg_1521 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_20_reg_1526 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_21_reg_1531 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_22_reg_1536 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_23_reg_1541 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_24_reg_1546 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_25_reg_1551 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_26_reg_1556 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_27_reg_1561 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_28_reg_1566 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_29_reg_1571 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_30_reg_1576 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_31_reg_1581 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln44_32_reg_1586 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln_reg_1591 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln1649_fu_855_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_reg_1596 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_1_fu_861_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_1_reg_1601 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_2_fu_867_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_2_reg_1606 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_3_fu_873_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_3_reg_1611 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_4_fu_879_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_4_reg_1616 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_5_fu_885_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_5_reg_1621 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_6_fu_891_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_6_reg_1626 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_7_fu_897_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_7_reg_1631 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_8_fu_903_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_8_reg_1636 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_9_fu_909_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_9_reg_1641 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_10_fu_915_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_10_reg_1646 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_11_fu_921_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_11_reg_1651 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_12_fu_927_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_12_reg_1656 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_13_fu_933_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_13_reg_1661 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_14_fu_939_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_14_reg_1666 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_15_fu_945_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_15_reg_1671 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_16_fu_951_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_16_reg_1676 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_17_fu_957_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_17_reg_1681 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_18_fu_963_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_18_reg_1686 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_19_fu_969_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_19_reg_1691 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_20_fu_975_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_20_reg_1696 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_21_fu_981_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_21_reg_1701 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_22_fu_987_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_22_reg_1706 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_23_fu_993_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_23_reg_1711 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_24_fu_999_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_24_reg_1716 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_25_fu_1005_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_25_reg_1721 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_26_fu_1011_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_26_reg_1726 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_27_fu_1017_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_27_reg_1731 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_28_fu_1023_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_28_reg_1736 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_29_fu_1029_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_29_reg_1741 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_30_fu_1035_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_30_reg_1746 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_31_fu_1041_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1649_31_reg_1751 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal in_data_data_fu_227_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_data_data_8_fu_255_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_data_data_9_fu_275_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_data_data_10_fu_295_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_data_data_11_fu_315_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_data_data_12_fu_335_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_data_data_13_fu_355_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_data_data_14_fu_375_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_395_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_415_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_435_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_455_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_475_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_495_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_fu_515_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_535_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_8_fu_555_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_9_fu_575_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_595_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_10_fu_615_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_fu_635_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_12_fu_655_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_13_fu_675_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_14_fu_695_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_15_fu_715_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_16_fu_735_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_17_fu_755_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_18_fu_775_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_19_fu_795_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_20_fu_815_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln44_2_fu_235_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln44_3_fu_245_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln51_fu_1047_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_1_fu_1057_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_2_fu_1067_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_3_fu_1077_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_4_fu_1087_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_5_fu_1097_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_6_fu_1107_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_7_fu_1117_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_8_fu_1127_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_9_fu_1137_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_10_fu_1147_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_11_fu_1157_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_12_fu_1167_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_13_fu_1177_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_14_fu_1187_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_15_fu_1197_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_16_fu_1207_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_17_fu_1217_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_18_fu_1227_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_19_fu_1237_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_20_fu_1247_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_21_fu_1257_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_22_fu_1267_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_23_fu_1277_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_24_fu_1287_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_25_fu_1297_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_26_fu_1307_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_27_fu_1317_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_28_fu_1327_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_29_fu_1337_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_30_fu_1347_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln51_31_fu_1357_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln1649_30_fu_1353_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_29_fu_1343_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_28_fu_1333_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_27_fu_1323_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_26_fu_1313_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_25_fu_1303_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_24_fu_1293_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_23_fu_1283_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_22_fu_1273_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_21_fu_1263_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_20_fu_1253_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_19_fu_1243_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_18_fu_1233_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_17_fu_1223_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_16_fu_1213_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_15_fu_1203_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_14_fu_1193_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_13_fu_1183_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_12_fu_1173_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_11_fu_1163_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_10_fu_1153_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_9_fu_1143_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_8_fu_1133_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_7_fu_1123_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_6_fu_1113_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_5_fu_1103_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_4_fu_1093_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_3_fu_1083_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_2_fu_1073_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_1_fu_1063_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1649_fu_1053_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln57_s_fu_1363_p33 : STD_LOGIC_VECTOR (254 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((layer5_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                icmp_ln1649_10_reg_1646 <= icmp_ln1649_10_fu_915_p2;
                icmp_ln1649_11_reg_1651 <= icmp_ln1649_11_fu_921_p2;
                icmp_ln1649_12_reg_1656 <= icmp_ln1649_12_fu_927_p2;
                icmp_ln1649_13_reg_1661 <= icmp_ln1649_13_fu_933_p2;
                icmp_ln1649_14_reg_1666 <= icmp_ln1649_14_fu_939_p2;
                icmp_ln1649_15_reg_1671 <= icmp_ln1649_15_fu_945_p2;
                icmp_ln1649_16_reg_1676 <= icmp_ln1649_16_fu_951_p2;
                icmp_ln1649_17_reg_1681 <= icmp_ln1649_17_fu_957_p2;
                icmp_ln1649_18_reg_1686 <= icmp_ln1649_18_fu_963_p2;
                icmp_ln1649_19_reg_1691 <= icmp_ln1649_19_fu_969_p2;
                icmp_ln1649_1_reg_1601 <= icmp_ln1649_1_fu_861_p2;
                icmp_ln1649_20_reg_1696 <= icmp_ln1649_20_fu_975_p2;
                icmp_ln1649_21_reg_1701 <= icmp_ln1649_21_fu_981_p2;
                icmp_ln1649_22_reg_1706 <= icmp_ln1649_22_fu_987_p2;
                icmp_ln1649_23_reg_1711 <= icmp_ln1649_23_fu_993_p2;
                icmp_ln1649_24_reg_1716 <= icmp_ln1649_24_fu_999_p2;
                icmp_ln1649_25_reg_1721 <= icmp_ln1649_25_fu_1005_p2;
                icmp_ln1649_26_reg_1726 <= icmp_ln1649_26_fu_1011_p2;
                icmp_ln1649_27_reg_1731 <= icmp_ln1649_27_fu_1017_p2;
                icmp_ln1649_28_reg_1736 <= icmp_ln1649_28_fu_1023_p2;
                icmp_ln1649_29_reg_1741 <= icmp_ln1649_29_fu_1029_p2;
                icmp_ln1649_2_reg_1606 <= icmp_ln1649_2_fu_867_p2;
                icmp_ln1649_30_reg_1746 <= icmp_ln1649_30_fu_1035_p2;
                icmp_ln1649_31_reg_1751 <= icmp_ln1649_31_fu_1041_p2;
                icmp_ln1649_3_reg_1611 <= icmp_ln1649_3_fu_873_p2;
                icmp_ln1649_4_reg_1616 <= icmp_ln1649_4_fu_879_p2;
                icmp_ln1649_5_reg_1621 <= icmp_ln1649_5_fu_885_p2;
                icmp_ln1649_6_reg_1626 <= icmp_ln1649_6_fu_891_p2;
                icmp_ln1649_7_reg_1631 <= icmp_ln1649_7_fu_897_p2;
                icmp_ln1649_8_reg_1636 <= icmp_ln1649_8_fu_903_p2;
                icmp_ln1649_9_reg_1641 <= icmp_ln1649_9_fu_909_p2;
                icmp_ln1649_reg_1596 <= icmp_ln1649_fu_855_p2;
                trunc_ln44_10_reg_1476 <= layer4_out_dout(70 downto 64);
                trunc_ln44_11_reg_1481 <= layer4_out_dout(78 downto 72);
                trunc_ln44_12_reg_1486 <= layer4_out_dout(86 downto 80);
                trunc_ln44_13_reg_1491 <= layer4_out_dout(94 downto 88);
                trunc_ln44_14_reg_1496 <= layer4_out_dout(102 downto 96);
                trunc_ln44_15_reg_1501 <= layer4_out_dout(110 downto 104);
                trunc_ln44_16_reg_1506 <= layer4_out_dout(118 downto 112);
                trunc_ln44_17_reg_1511 <= layer4_out_dout(126 downto 120);
                trunc_ln44_18_reg_1516 <= layer4_out_dout(134 downto 128);
                trunc_ln44_19_reg_1521 <= layer4_out_dout(142 downto 136);
                trunc_ln44_1_reg_1436 <= trunc_ln44_1_fu_231_p1;
                trunc_ln44_20_reg_1526 <= layer4_out_dout(150 downto 144);
                trunc_ln44_21_reg_1531 <= layer4_out_dout(158 downto 152);
                trunc_ln44_22_reg_1536 <= layer4_out_dout(166 downto 160);
                trunc_ln44_23_reg_1541 <= layer4_out_dout(174 downto 168);
                trunc_ln44_24_reg_1546 <= layer4_out_dout(182 downto 176);
                trunc_ln44_25_reg_1551 <= layer4_out_dout(190 downto 184);
                trunc_ln44_26_reg_1556 <= layer4_out_dout(198 downto 192);
                trunc_ln44_27_reg_1561 <= layer4_out_dout(206 downto 200);
                trunc_ln44_28_reg_1566 <= layer4_out_dout(214 downto 208);
                trunc_ln44_29_reg_1571 <= layer4_out_dout(222 downto 216);
                trunc_ln44_30_reg_1576 <= layer4_out_dout(230 downto 224);
                trunc_ln44_31_reg_1581 <= layer4_out_dout(238 downto 232);
                trunc_ln44_32_reg_1586 <= layer4_out_dout(246 downto 240);
                trunc_ln44_4_reg_1446 <= layer4_out_dout(22 downto 16);
                trunc_ln44_5_reg_1451 <= layer4_out_dout(30 downto 24);
                trunc_ln44_6_reg_1456 <= layer4_out_dout(38 downto 32);
                trunc_ln44_7_reg_1461 <= layer4_out_dout(46 downto 40);
                trunc_ln44_8_reg_1466 <= layer4_out_dout(54 downto 48);
                trunc_ln44_9_reg_1471 <= layer4_out_dout(62 downto 56);
                trunc_ln44_s_reg_1441 <= layer4_out_dout(14 downto 8);
                trunc_ln_reg_1591 <= layer4_out_dout(254 downto 248);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, layer4_out_empty_n, layer5_out_full_n, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((real_start = ap_const_logic_0) or (layer4_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((layer5_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg, layer4_out_empty_n)
    begin
        if (((real_start = ap_const_logic_0) or (layer4_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(layer5_out_full_n)
    begin
        if ((layer5_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, layer4_out_empty_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (layer4_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer5_out_full_n, ap_CS_fsm_state2)
    begin
        if (((layer5_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    icmp_ln1649_10_fu_915_p2 <= "1" when (signed(tmp_2_fu_435_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_11_fu_921_p2 <= "1" when (signed(tmp_3_fu_455_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_12_fu_927_p2 <= "1" when (signed(tmp_4_fu_475_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_13_fu_933_p2 <= "1" when (signed(tmp_5_fu_495_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_14_fu_939_p2 <= "1" when (signed(tmp_6_fu_515_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_15_fu_945_p2 <= "1" when (signed(tmp_7_fu_535_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_16_fu_951_p2 <= "1" when (signed(tmp_8_fu_555_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_17_fu_957_p2 <= "1" when (signed(tmp_9_fu_575_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_18_fu_963_p2 <= "1" when (signed(tmp_s_fu_595_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_19_fu_969_p2 <= "1" when (signed(tmp_10_fu_615_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_1_fu_861_p2 <= "1" when (signed(in_data_data_8_fu_255_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_20_fu_975_p2 <= "1" when (signed(tmp_11_fu_635_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_21_fu_981_p2 <= "1" when (signed(tmp_12_fu_655_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_22_fu_987_p2 <= "1" when (signed(tmp_13_fu_675_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_23_fu_993_p2 <= "1" when (signed(tmp_14_fu_695_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_24_fu_999_p2 <= "1" when (signed(tmp_15_fu_715_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_25_fu_1005_p2 <= "1" when (signed(tmp_16_fu_735_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_26_fu_1011_p2 <= "1" when (signed(tmp_17_fu_755_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_27_fu_1017_p2 <= "1" when (signed(tmp_18_fu_775_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_28_fu_1023_p2 <= "1" when (signed(tmp_19_fu_795_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_29_fu_1029_p2 <= "1" when (signed(tmp_20_fu_815_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_2_fu_867_p2 <= "1" when (signed(in_data_data_9_fu_275_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_30_fu_1035_p2 <= "1" when (signed(trunc_ln44_2_fu_235_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_31_fu_1041_p2 <= "1" when (signed(trunc_ln44_3_fu_245_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_3_fu_873_p2 <= "1" when (signed(in_data_data_10_fu_295_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_4_fu_879_p2 <= "1" when (signed(in_data_data_11_fu_315_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_5_fu_885_p2 <= "1" when (signed(in_data_data_12_fu_335_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_6_fu_891_p2 <= "1" when (signed(in_data_data_13_fu_355_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_7_fu_897_p2 <= "1" when (signed(in_data_data_14_fu_375_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_8_fu_903_p2 <= "1" when (signed(tmp_fu_395_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_9_fu_909_p2 <= "1" when (signed(tmp_1_fu_415_p4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_fu_855_p2 <= "1" when (signed(in_data_data_fu_227_p1) > signed(ap_const_lv8_0)) else "0";
    in_data_data_10_fu_295_p4 <= layer4_out_dout(31 downto 24);
    in_data_data_11_fu_315_p4 <= layer4_out_dout(39 downto 32);
    in_data_data_12_fu_335_p4 <= layer4_out_dout(47 downto 40);
    in_data_data_13_fu_355_p4 <= layer4_out_dout(55 downto 48);
    in_data_data_14_fu_375_p4 <= layer4_out_dout(63 downto 56);
    in_data_data_8_fu_255_p4 <= layer4_out_dout(15 downto 8);
    in_data_data_9_fu_275_p4 <= layer4_out_dout(23 downto 16);
    in_data_data_fu_227_p1 <= layer4_out_dout(8 - 1 downto 0);

    internal_ap_ready_assign_proc : process(layer5_out_full_n, ap_CS_fsm_state2)
    begin
        if (((layer5_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer4_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer4_out_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer4_out_blk_n <= layer4_out_empty_n;
        else 
            layer4_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer4_out_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer4_out_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (layer4_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer4_out_read <= ap_const_logic_1;
        else 
            layer4_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer5_out_blk_n_assign_proc : process(layer5_out_full_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            layer5_out_blk_n <= layer5_out_full_n;
        else 
            layer5_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer5_out_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln57_s_fu_1363_p33),256));

    layer5_out_write_assign_proc : process(layer5_out_full_n, ap_CS_fsm_state2)
    begin
        if (((layer5_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            layer5_out_write <= ap_const_logic_1;
        else 
            layer5_out_write <= ap_const_logic_0;
        end if; 
    end process;

    or_ln57_s_fu_1363_p33 <= (((((((((((((((((((((((((((((((select_ln51_31_fu_1357_p3 & zext_ln1649_30_fu_1353_p1) & zext_ln1649_29_fu_1343_p1) & zext_ln1649_28_fu_1333_p1) & zext_ln1649_27_fu_1323_p1) & zext_ln1649_26_fu_1313_p1) & zext_ln1649_25_fu_1303_p1) & zext_ln1649_24_fu_1293_p1) & zext_ln1649_23_fu_1283_p1) & zext_ln1649_22_fu_1273_p1) & zext_ln1649_21_fu_1263_p1) & zext_ln1649_20_fu_1253_p1) & zext_ln1649_19_fu_1243_p1) & zext_ln1649_18_fu_1233_p1) & zext_ln1649_17_fu_1223_p1) & zext_ln1649_16_fu_1213_p1) & zext_ln1649_15_fu_1203_p1) & zext_ln1649_14_fu_1193_p1) & zext_ln1649_13_fu_1183_p1) & zext_ln1649_12_fu_1173_p1) & zext_ln1649_11_fu_1163_p1) & zext_ln1649_10_fu_1153_p1) & zext_ln1649_9_fu_1143_p1) & zext_ln1649_8_fu_1133_p1) & zext_ln1649_7_fu_1123_p1) & zext_ln1649_6_fu_1113_p1) & zext_ln1649_5_fu_1103_p1) & zext_ln1649_4_fu_1093_p1) & zext_ln1649_3_fu_1083_p1) & zext_ln1649_2_fu_1073_p1) & zext_ln1649_1_fu_1063_p1) & zext_ln1649_fu_1053_p1);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln51_10_fu_1147_p3 <= 
        trunc_ln44_12_reg_1486 when (icmp_ln1649_10_reg_1646(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_11_fu_1157_p3 <= 
        trunc_ln44_13_reg_1491 when (icmp_ln1649_11_reg_1651(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_12_fu_1167_p3 <= 
        trunc_ln44_14_reg_1496 when (icmp_ln1649_12_reg_1656(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_13_fu_1177_p3 <= 
        trunc_ln44_15_reg_1501 when (icmp_ln1649_13_reg_1661(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_14_fu_1187_p3 <= 
        trunc_ln44_16_reg_1506 when (icmp_ln1649_14_reg_1666(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_15_fu_1197_p3 <= 
        trunc_ln44_17_reg_1511 when (icmp_ln1649_15_reg_1671(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_16_fu_1207_p3 <= 
        trunc_ln44_18_reg_1516 when (icmp_ln1649_16_reg_1676(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_17_fu_1217_p3 <= 
        trunc_ln44_19_reg_1521 when (icmp_ln1649_17_reg_1681(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_18_fu_1227_p3 <= 
        trunc_ln44_20_reg_1526 when (icmp_ln1649_18_reg_1686(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_19_fu_1237_p3 <= 
        trunc_ln44_21_reg_1531 when (icmp_ln1649_19_reg_1691(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_1_fu_1057_p3 <= 
        trunc_ln44_s_reg_1441 when (icmp_ln1649_1_reg_1601(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_20_fu_1247_p3 <= 
        trunc_ln44_22_reg_1536 when (icmp_ln1649_20_reg_1696(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_21_fu_1257_p3 <= 
        trunc_ln44_23_reg_1541 when (icmp_ln1649_21_reg_1701(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_22_fu_1267_p3 <= 
        trunc_ln44_24_reg_1546 when (icmp_ln1649_22_reg_1706(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_23_fu_1277_p3 <= 
        trunc_ln44_25_reg_1551 when (icmp_ln1649_23_reg_1711(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_24_fu_1287_p3 <= 
        trunc_ln44_26_reg_1556 when (icmp_ln1649_24_reg_1716(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_25_fu_1297_p3 <= 
        trunc_ln44_27_reg_1561 when (icmp_ln1649_25_reg_1721(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_26_fu_1307_p3 <= 
        trunc_ln44_28_reg_1566 when (icmp_ln1649_26_reg_1726(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_27_fu_1317_p3 <= 
        trunc_ln44_29_reg_1571 when (icmp_ln1649_27_reg_1731(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_28_fu_1327_p3 <= 
        trunc_ln44_30_reg_1576 when (icmp_ln1649_28_reg_1736(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_29_fu_1337_p3 <= 
        trunc_ln44_31_reg_1581 when (icmp_ln1649_29_reg_1741(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_2_fu_1067_p3 <= 
        trunc_ln44_4_reg_1446 when (icmp_ln1649_2_reg_1606(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_30_fu_1347_p3 <= 
        trunc_ln44_32_reg_1586 when (icmp_ln1649_30_reg_1746(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_31_fu_1357_p3 <= 
        trunc_ln_reg_1591 when (icmp_ln1649_31_reg_1751(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_3_fu_1077_p3 <= 
        trunc_ln44_5_reg_1451 when (icmp_ln1649_3_reg_1611(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_4_fu_1087_p3 <= 
        trunc_ln44_6_reg_1456 when (icmp_ln1649_4_reg_1616(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_5_fu_1097_p3 <= 
        trunc_ln44_7_reg_1461 when (icmp_ln1649_5_reg_1621(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_6_fu_1107_p3 <= 
        trunc_ln44_8_reg_1466 when (icmp_ln1649_6_reg_1626(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_7_fu_1117_p3 <= 
        trunc_ln44_9_reg_1471 when (icmp_ln1649_7_reg_1631(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_8_fu_1127_p3 <= 
        trunc_ln44_10_reg_1476 when (icmp_ln1649_8_reg_1636(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_9_fu_1137_p3 <= 
        trunc_ln44_11_reg_1481 when (icmp_ln1649_9_reg_1641(0) = '1') else 
        ap_const_lv7_0;
    select_ln51_fu_1047_p3 <= 
        trunc_ln44_1_reg_1436 when (icmp_ln1649_reg_1596(0) = '1') else 
        ap_const_lv7_0;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_10_fu_615_p4 <= layer4_out_dout(159 downto 152);
    tmp_11_fu_635_p4 <= layer4_out_dout(167 downto 160);
    tmp_12_fu_655_p4 <= layer4_out_dout(175 downto 168);
    tmp_13_fu_675_p4 <= layer4_out_dout(183 downto 176);
    tmp_14_fu_695_p4 <= layer4_out_dout(191 downto 184);
    tmp_15_fu_715_p4 <= layer4_out_dout(199 downto 192);
    tmp_16_fu_735_p4 <= layer4_out_dout(207 downto 200);
    tmp_17_fu_755_p4 <= layer4_out_dout(215 downto 208);
    tmp_18_fu_775_p4 <= layer4_out_dout(223 downto 216);
    tmp_19_fu_795_p4 <= layer4_out_dout(231 downto 224);
    tmp_1_fu_415_p4 <= layer4_out_dout(79 downto 72);
    tmp_20_fu_815_p4 <= layer4_out_dout(239 downto 232);
    tmp_2_fu_435_p4 <= layer4_out_dout(87 downto 80);
    tmp_3_fu_455_p4 <= layer4_out_dout(95 downto 88);
    tmp_4_fu_475_p4 <= layer4_out_dout(103 downto 96);
    tmp_5_fu_495_p4 <= layer4_out_dout(111 downto 104);
    tmp_6_fu_515_p4 <= layer4_out_dout(119 downto 112);
    tmp_7_fu_535_p4 <= layer4_out_dout(127 downto 120);
    tmp_8_fu_555_p4 <= layer4_out_dout(135 downto 128);
    tmp_9_fu_575_p4 <= layer4_out_dout(143 downto 136);
    tmp_fu_395_p4 <= layer4_out_dout(71 downto 64);
    tmp_s_fu_595_p4 <= layer4_out_dout(151 downto 144);
    trunc_ln44_1_fu_231_p1 <= layer4_out_dout(7 - 1 downto 0);
    trunc_ln44_2_fu_235_p4 <= layer4_out_dout(247 downto 240);
    trunc_ln44_3_fu_245_p4 <= layer4_out_dout(255 downto 248);
    zext_ln1649_10_fu_1153_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_10_fu_1147_p3),8));
    zext_ln1649_11_fu_1163_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_11_fu_1157_p3),8));
    zext_ln1649_12_fu_1173_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_12_fu_1167_p3),8));
    zext_ln1649_13_fu_1183_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_13_fu_1177_p3),8));
    zext_ln1649_14_fu_1193_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_14_fu_1187_p3),8));
    zext_ln1649_15_fu_1203_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_15_fu_1197_p3),8));
    zext_ln1649_16_fu_1213_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_16_fu_1207_p3),8));
    zext_ln1649_17_fu_1223_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_17_fu_1217_p3),8));
    zext_ln1649_18_fu_1233_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_18_fu_1227_p3),8));
    zext_ln1649_19_fu_1243_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_19_fu_1237_p3),8));
    zext_ln1649_1_fu_1063_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_1_fu_1057_p3),8));
    zext_ln1649_20_fu_1253_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_20_fu_1247_p3),8));
    zext_ln1649_21_fu_1263_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_21_fu_1257_p3),8));
    zext_ln1649_22_fu_1273_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_22_fu_1267_p3),8));
    zext_ln1649_23_fu_1283_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_23_fu_1277_p3),8));
    zext_ln1649_24_fu_1293_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_24_fu_1287_p3),8));
    zext_ln1649_25_fu_1303_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_25_fu_1297_p3),8));
    zext_ln1649_26_fu_1313_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_26_fu_1307_p3),8));
    zext_ln1649_27_fu_1323_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_27_fu_1317_p3),8));
    zext_ln1649_28_fu_1333_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_28_fu_1327_p3),8));
    zext_ln1649_29_fu_1343_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_29_fu_1337_p3),8));
    zext_ln1649_2_fu_1073_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_2_fu_1067_p3),8));
    zext_ln1649_30_fu_1353_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_30_fu_1347_p3),8));
    zext_ln1649_3_fu_1083_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_3_fu_1077_p3),8));
    zext_ln1649_4_fu_1093_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_4_fu_1087_p3),8));
    zext_ln1649_5_fu_1103_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_5_fu_1097_p3),8));
    zext_ln1649_6_fu_1113_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_6_fu_1107_p3),8));
    zext_ln1649_7_fu_1123_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_7_fu_1117_p3),8));
    zext_ln1649_8_fu_1133_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_8_fu_1127_p3),8));
    zext_ln1649_9_fu_1143_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_9_fu_1137_p3),8));
    zext_ln1649_fu_1053_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_fu_1047_p3),8));
end behav;
